import { LicenseRestriction } from '../types';

export const restriction_1c: LicenseRestriction = {
  code: '1C',
  name: 'Telescoping boom / loaders & backhoes',
  description: 'Boom trucks, loader-backhoes, wheel loaders.',
  equipmentCovered: ['Boom trucks', 'Loader-backhoes', 'Wheel loaders'],
  totalHours: 20,
  modules: [
    {
      id: '1c-m1',
      title: 'Legal & Regulatory Foundation',
      orderInCourse: 1,
      estimatedHours: 5,
      sessions: [
        {
          id: '1c-m1-s1',
          title: 'MGL & CMR Basics',
          durationHours: 2,
          learningObjectives: [
            'State the minimum age, exam passing score, and application fee for a 1C license',
            'Identify the three threshold conditions under MGL §53 that trigger a hoisting license requirement',
            'Explain the 1C license classification and which equipment it covers',
            'Describe the role of 230 CMR 6.00 relative to MGL Chapter 146',
          ],
          topics: [
            'MGL §53 — who must hold a hoisting license and the catch-all clause',
            'License threshold: over 10 ft OR over 500 lbs OR bucket over ¼ cubic yard',
            'Minimum age requirement: 18 years old',
            'Exam passing score: 70% minimum',
            '60-day waiting period after a failed exam attempt',
            '$75 non-refundable application fee per restriction class',
            'License valid for 2 years; renewal before expiration',
            '1C classification: telescoping boom trucks, loader-backhoes, wheel loaders',
            '230 CMR 6.00 — implementing regulation with specific technical and operational requirements',
            'Application through the MA Division of Occupational Licensure (DOL)',
            'MGL §54 — examination and issuance; MGL §54A — apprentice licenses',
          ],
          resources: [
            {
              label: 'MGL Chapter 146 § 53 — Licensing requirement',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146/Section53',
              type: 'regulation',
              required: true,
            },
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'Apply for a Hoisting Engineer License',
              url: 'https://www.mass.gov/how-to/apply-for-a-hoisting-engineer-license',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'What is the minimum passing score on the Massachusetts 1C hoisting engineer exam?',
              options: ['60%', '65%', '70%', '75%'],
              correctIndex: 2,
              explanation: 'The passing score is 70% for all MA hoisting license classes including 1C. Score below 70% and you must wait 60 days before retesting — use that time to review your weak areas.',
            },
            {
              question: 'Which combination of conditions ALONE triggers the MA hoisting license requirement?',
              options: [
                'Lifting 400 lbs to 9 ft with a ⅛ cubic yard bucket',
                'Lifting 400 lbs to 11 ft with a ⅛ cubic yard bucket',
                'Operating any self-propelled equipment on a job site',
                'Lifting 400 lbs to 9 ft with a ½ cubic yard bucket',
              ],
              correctIndex: 1,
              explanation: 'The threshold is OR, not AND: over 10 ft OR over 500 lbs OR bucket over ¼ cubic yard. Lifting to 11 ft exceeds the 10 ft height threshold, triggering the requirement on that condition alone.',
            },
            {
              question: 'A wheel loader operator on a construction site is 17 years old and experienced. Can they hold a 1C license?',
              options: [
                'Yes, if they pass the written exam',
                'Yes, if they have at least 6 months of documented experience',
                'No, the minimum age is 18 for all hoisting licenses',
                'Yes, with a parent or guardian signature',
              ],
              correctIndex: 2,
              explanation: 'MGL Chapter 146 sets the minimum age at 18 for all hoisting license classes. No exception exists for experience or parental consent.',
            },
            {
              question: 'How long is a Massachusetts 1C hoisting engineer license valid before renewal is required?',
              options: ['1 year', '2 years', '3 years', '5 years'],
              correctIndex: 1,
              explanation: 'All MA hoisting licenses, including 1C, are valid for 2 years. Always verify the current renewal cycle at mass.gov — renewal requirements can change.',
            },
            {
              question: 'A boom truck operator fails the 1C exam on a Tuesday. When is the earliest they can retake it?',
              options: [
                '7 days later',
                '30 days later',
                '60 days later',
                '90 days later',
              ],
              correctIndex: 2,
              explanation: 'MA regulations require a 60-day waiting period after any failed hoisting exam attempt. This applies to all restriction classes including 1C.',
            },
            {
              question: 'Which piece of equipment does the 1C license specifically authorize an operator to use?',
              options: [
                'Crawler excavator',
                'Tower crane',
                'Telescoping boom truck',
                'Pile driver',
              ],
              correctIndex: 2,
              explanation: 'The 1C license covers telescoping boom trucks, loader-backhoes, and wheel loaders. Crawler excavators are 2A; tower cranes are 1A; pile drivers require a separate classification.',
            },
            {
              question: 'What is the non-refundable application fee for each restriction class on a Massachusetts hoisting license?',
              options: ['$25', '$50', '$75', '$100'],
              correctIndex: 2,
              explanation: 'The application fee is $75 per restriction class as of current MA regulations. This fee is non-refundable even if you fail the exam or your application is denied.',
            },
          ],
        },
        {
          id: '1c-m1-s2',
          title: 'Load Restrictions',
          durationHours: 1.5,
          learningObjectives: [
            'Read and interpret a telescoping boom truck load chart',
            'Explain how radius, boom angle, and extension affect rated capacity',
            'Identify the consequences of exceeding rated load limits under MA law',
            'Describe how outrigger position affects the applicable load chart section',
          ],
          topics: [
            'ASME B30.5 rated capacity: the maximum load at a given radius and configuration',
            'Load chart sections: over-end vs. over-side capacities',
            'Gross vs. net capacity: deducting the weight of rigging and headache ball',
            'Radius: measured horizontally from center of rotation to load center',
            'Boom angle and length: how extending the boom increases radius and reduces capacity',
            'Two-blocking: boom tip block contacts headache ball — immediate shutdown required',
            'Anti-two-block (ATB) devices: required on telescoping booms by ASME B30.5',
            'Outrigger deployment: fully extended vs. partially extended changes which chart to use',
            'Outrigger float contact: all floats must bear on firm, level ground',
            'Side loading: telescoping booms are not designed for side loading',
            'MGL §65 — operator must not exceed rated capacity under any circumstance',
          ],
          resources: [
            {
              label: 'MGL Chapter 146 — General Safety (§§ 64–65)',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146',
              type: 'regulation',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926 Subpart CC — Cranes & Derricks in Construction',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1400',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'A boom truck load chart shows 8,000 lbs capacity at 20 ft radius. You plan to lift a 7,500 lb load with 600 lbs of rigging. Can you make the lift at 20 ft radius?',
              options: [
                'Yes — 7,500 lbs is under the 8,000 lb chart limit',
                'No — the total load including rigging is 8,100 lbs, which exceeds rated capacity',
                'Yes — rigging weight is never included in the load calculation',
                'Yes — you can exceed capacity by 10% for a short-duration lift',
              ],
              correctIndex: 1,
              explanation: 'Rated capacity is the maximum total suspended load — including the weight of all rigging, slings, hooks, and the headache ball. Total here is 8,100 lbs, which exceeds the 8,000 lb chart limit. The lift cannot be made at this radius.',
            },
            {
              question: 'A telescoping boom truck load chart has separate sections for "on outriggers fully extended" and "on outriggers retracted." You have deployed outriggers but only 75% extended. Which chart applies?',
              options: [
                'The fully extended chart, because outriggers are deployed',
                'The on-tires chart, because outriggers are not fully extended',
                'You must interpolate between both charts',
                'Either chart may be used at operator discretion',
              ],
              correctIndex: 1,
              explanation: 'If outriggers are not in the exact configuration shown on the load chart, you must use the more conservative (lower capacity) chart. Partial extension does not achieve the stability of full extension, so the on-tires (retracted) chart applies.',
            },
            {
              question: 'What is "two-blocking" on a telescoping boom truck?',
              options: [
                'Using two outrigger pads stacked under one float',
                'The condition where the upper load block contacts the boom tip',
                'Lifting two separate loads simultaneously',
                'Deploying both front and rear outriggers at the same time',
              ],
              correctIndex: 1,
              explanation: 'Two-blocking occurs when the traveling block (headache ball or hook block) rises and contacts the boom tip block, which can snap the wire rope or cause structural failure. Anti-two-block devices are required by ASME B30.5 to stop hoist motion before contact.',
            },
            {
              question: 'As you extend a telescoping boom to a longer length at the same angle, what happens to the rated capacity?',
              options: [
                'It stays the same — angle is the only variable',
                'It increases — a longer boom can reach more load',
                'It decreases — longer boom means greater radius and less capacity',
                'It depends on the load chart manufacturer',
              ],
              correctIndex: 2,
              explanation: 'Extending the boom at a fixed angle increases the horizontal radius. Greater radius creates a larger overturning moment, which reduces the rated capacity shown in the load chart.',
            },
            {
              question: 'What does the "over-end" section of a boom truck load chart describe?',
              options: [
                'Lifts made at maximum boom extension',
                'Lifts made with the boom positioned over the front or rear of the truck',
                'Lifts that require special over-the-side outrigger pads',
                'Lifts exceeding the gross vehicle weight rating',
              ],
              correctIndex: 1,
              explanation: 'Boom trucks have higher capacity when lifting over the front or rear (the structural strong axis) versus over the side. The load chart is divided into over-end and over-side sections to reflect this. Always verify your boom orientation before selecting the applicable column.',
            },
          ],
        },
        {
          id: '1c-m1-s3',
          title: 'Renewal & Compliance',
          durationHours: 1.5,
          learningObjectives: [
            'State the civil and criminal penalties for operating without a valid 1C license',
            'Explain employer obligations under MGL §66',
            'Describe the accident reporting requirements under MGL §67',
            'Outline the reinstatement process after a license lapse',
          ],
          topics: [
            'Civil penalty: up to $500 per day for unlicensed operation per MGL §53',
            'Criminal penalties for repeat or egregious violations',
            'Employer liability: MGL §66 makes employers responsible for verifying operator licenses',
            'Accident reporting obligations under MGL §67',
            'Renewal deadline: before the 2-year expiration date',
            'Reinstatement after lapse: re-application may require re-examination',
            'OSHA inspection authority: citations under 29 CFR 1926 Subpart CC',
            'Documenting compliance: keeping license copies on the job site',
          ],
          resources: [
            {
              label: 'MGL Chapter 146 §§ 53–67',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146',
              type: 'regulation',
              required: true,
            },
            {
              label: 'MA Hoisting License Renewal (mass.gov)',
              url: 'https://www.mass.gov/how-to/renew-a-hoisting-license',
              type: 'reference',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926 Subpart CC — Cranes & Derricks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1400',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'Your 1C license expired two weeks ago. A supervisor asks you to operate a boom truck for one day. What should you do?',
              options: [
                'Operate for one day — the risk is minimal',
                'Decline — an expired license is an invalid license and you face civil penalties',
                'Operate if the supervisor signs a waiver of liability',
                'Operate if no inspector is present on the job site',
              ],
              correctIndex: 1,
              explanation: 'An expired license is an invalid license. There is no grace period that permits continued operation. Both the operator and the employer face civil penalties of up to $500 per day per MGL §53.',
            },
            {
              question: 'Under MGL §66, who bears legal responsibility for ensuring a hoisting operator holds a valid license?',
              options: [
                'The operator alone',
                'Both the operator and the employer',
                'The general contractor only',
                'OPSI, which verifies licenses on every job site',
              ],
              correctIndex: 1,
              explanation: 'MGL §66 places responsibility on both the licensed operator to maintain their own valid license AND the employer who directs their work. An employer who knowingly uses an unlicensed operator faces separate penalties.',
            },
            {
              question: 'After an accident involving a boom truck on a MA job site, what is required under MGL §67?',
              options: [
                'Report only if someone was hospitalized',
                'No reporting is required if property damage is under $5,000',
                'Report the accident as required by law and cooperate with any investigation',
                'Only OSHA reporting is required; state reporting is optional',
              ],
              correctIndex: 2,
              explanation: 'MGL §67 requires accident reporting involving hoisting machinery and full cooperation with any investigation. Failing to report compounds any penalties the operator or employer may face.',
            },
            {
              question: 'A general contractor directs an unlicensed worker to operate a wheel loader "just for the morning." What is the legal consequence?',
              options: [
                'No consequence if no accident occurs',
                'The worker alone faces a verbal warning',
                'Both the worker and the contractor face civil penalties under MGL §53',
                'Only the contractor faces penalties; operators are protected individually',
              ],
              correctIndex: 2,
              explanation: 'MGL §53 creates liability for both the person operating without a license and the employer who directs or permits that operation. "Just for the morning" does not reduce penalties — each day of unlicensed operation is a separate violation.',
            },
            {
              question: 'If you allow your 1C license to lapse by not renewing, what is required to become licensed again?',
              options: [
                'Simply pay the $75 fee and the license is reinstated automatically',
                'Re-application and potentially a new examination, depending on the lapse duration',
                'A supervisor co-signs your renewal form and no exam is required',
                'No action needed — MA sends a courtesy renewal automatically',
              ],
              correctIndex: 1,
              explanation: 'A lapsed license requires re-application with OPSI. Depending on how long the license has been expired, re-examination may be required. Always renew before expiration to avoid this process.',
            },
          ],
        },
      ],
    },
    {
      id: '1c-m2',
      title: 'Equipment Systems',
      orderInCourse: 2,
      estimatedHours: 5,
      sessions: [
        {
          id: '1c-m2-s1',
          title: 'Boom Truck Anatomy',
          durationHours: 2,
          learningObjectives: [
            'Identify and name the major structural components of a telescoping boom truck',
            'Explain how the telescoping boom extends and the function of extend/retract cylinders',
            'Describe the outrigger system and why proper deployment is critical',
            'Explain the function of the load moment indicator (LMI) and anti-two-block device',
          ],
          topics: [
            'Carrier chassis vs. crane superstructure: the two main assemblies',
            'Turntable / slewing ring: allows rotation of superstructure on carrier',
            'Boom sections: base, inner, mid, and fly sections; telescoping cylinders',
            'Boom head/tip: houses the sheave(s), anti-two-block switch, boom tip lights',
            'Hook block (headache ball) and load hook: the lift points',
            'Wire rope: construction, drum reeving, and two-block risk',
            'Outrigger beams and floats: extend outward to widen the support base',
            'Outrigger pads: distribute point load across ground surface',
            'Swing brake and swing lock: prevent uncontrolled rotation',
            'Load moment indicator (LMI): continuous display of % rated capacity',
            'Anti-two-block (ATB) device: cuts hoist and boom-up motion before contact',
            'Counterweight: bolted to back of superstructure; must be correct for load chart used',
            'Operator controls: boom up/down, extend/retract, rotate, hoist up/down',
          ],
          resources: [
            {
              label: 'ASME B30.5 — Mobile and Locomotive Cranes (overview)',
              url: 'https://www.asme.org/codes-standards/find-codes-standards/b30-5-mobile-locomotive-cranes',
              type: 'manual',
              required: false,
            },
            {
              label: 'OSHA 29 CFR 1926 Subpart CC — Cranes & Derricks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1400',
              type: 'osha',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'What component allows the boom superstructure of a boom truck to rotate relative to the carrier chassis?',
              options: [
                'The boom extend cylinder',
                'The turntable (slewing ring) and swing motor',
                'The carrier drive axle',
                'The outrigger beam',
              ],
              correctIndex: 1,
              explanation: 'The turntable (slewing ring) is a large bearing that separates the rotating superstructure from the stationary carrier. The hydraulic swing motor drives the rotation. Both must be inspected for proper lubrication and integrity.',
            },
            {
              question: 'The anti-two-block (ATB) device on a telescoping boom truck is designed to:',
              options: [
                'Prevent the outriggers from retracting under load',
                'Stop hoist-up and boom-up motion before the load block contacts the boom tip',
                'Lock the swing brake when the engine is off',
                'Limit boom extension to the rated length on the load chart',
              ],
              correctIndex: 1,
              explanation: 'ATB devices sense when the traveling block (hook) approaches the boom tip and automatically cut hoist-up and boom-up hydraulic circuits. Two-blocking can snap wire rope or cause catastrophic structural failure.',
            },
            {
              question: 'You are setting up a boom truck and one outrigger float is on a soft patch of ground. What is the correct action?',
              options: [
                'Proceed — one soft float is acceptable if the other three are firm',
                'Place a timber or outrigger pad under that float to spread the load',
                'Operate at half capacity because one outrigger is compromised',
                'Extend only the three firm outriggers and leave the soft one retracted',
              ],
              correctIndex: 1,
              explanation: 'All four outrigger floats must bear on firm, stable ground. Outrigger pads or timber mats spread the point load across a larger area. Operating with an unsupported float can cause an outrigger to punch through, resulting in a tip-over.',
            },
            {
              question: 'What does the load moment indicator (LMI) display to the operator?',
              options: [
                'The exact weight of the load on the hook',
                'The current percentage of rated capacity being used',
                'The remaining fuel level and hydraulic oil temperature',
                'The wind speed at boom tip height',
              ],
              correctIndex: 1,
              explanation: 'The LMI continuously calculates and displays the percentage of rated capacity (based on boom angle, radius, and extension) so the operator can monitor proximity to the chart limit. It is a decision-support tool, not a substitute for reading the load chart.',
            },
            {
              question: 'A boom truck\'s load chart specifies a counterweight of 2,000 lbs. The operator has not installed the counterweight to save time. What is the consequence?',
              options: [
                'None — the LMI will compensate by reducing displayed capacity',
                'The load chart is no longer valid; all published capacities are void',
                'Capacity is reduced by exactly 10% and the operator may proceed',
                'The boom truck may still be used for lifts under 1,000 lbs',
              ],
              correctIndex: 1,
              explanation: 'Load charts are calculated for a specific counterweight configuration. Installing a different or missing counterweight invalidates all load chart values — the crane must not be used for any crane lift until correctly configured.',
            },
            {
              question: 'When is the swing lock on a boom truck engaged?',
              options: [
                'During all lifts to prevent unintended rotation',
                'When traveling on roads to prevent superstructure rotation',
                'Only when the boom is elevated above 60 degrees',
                'When a load exceeds 80% of rated capacity',
              ],
              correctIndex: 1,
              explanation: 'The swing lock (or swing brake/travel lock) is engaged when the machine is traveling on public roads to prevent the superstructure from rotating due to turns or road camber. It must be disengaged before any crane operations.',
            },
          ],
        },
        {
          id: '1c-m2-s2',
          title: 'Loader & Backhoe',
          durationHours: 1.5,
          learningObjectives: [
            'Identify the major components of a loader-backhoe (TLB) and a wheel loader',
            'Explain the function of stabilizers on a loader-backhoe during backhoe operations',
            'Describe the geometry and controls of the backhoe boom, dipperstick, and bucket',
            'Compare wheel loader and loader-backhoe load-handling capabilities',
          ],
          topics: [
            'Loader-backhoe (TLB) layout: loader end, articulation point, backhoe end',
            'Loader bucket: cutting edge, bolt-on teeth (optional), spill guard, attachment frame',
            'Loader lift arms: parallel linkage for level bucket during raise/lower',
            'Backhoe boom and dipperstick: digging geometry and maximum reach/depth',
            'Backhoe bucket: trapezoidal vs. ditching vs. general purpose buckets',
            'Stabilizers (outriggers): must be deployed before backhoe operation; prevent tip-over',
            'Stabilizer pads: protect pavement and distribute load',
            'TLB operator seat swing: rotates from loader-facing to backhoe-facing position',
            'Wheel loader: articulated frame steering, large bucket capacity, high dump height',
            'Wheel loader tire types: lug (off-road) vs. smooth (stockpile) vs. rock (quarry)',
            'Quick-attach systems: allow bucket and fork swap without tools',
            'Load-handling: loader-backhoe lifts from backhoe boom only; wheel loader from bucket',
          ],
          resources: [
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.602 — Material Handling Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'Before beginning backhoe operations with a loader-backhoe, what must the operator do with the stabilizers?',
              options: [
                'Leave them retracted — they are only used on slopes',
                'Deploy them to the ground so all four contact points bear weight',
                'Deploy only the two rear stabilizers directly behind the backhoe boom',
                'Partially lower them to reduce ground disturbance',
              ],
              correctIndex: 1,
              explanation: 'Both stabilizers must be fully deployed to firm ground before any backhoe digging begins. Without stabilizers deployed, the rear of the machine can lift or tip sideways when the bucket curls under load.',
            },
            {
              question: 'On a loader-backhoe, the operator\'s seat has a swing feature. What is its purpose?',
              options: [
                'It allows the operator to lean away from the backhoe during digging',
                'It rotates 180° so the operator faces the backhoe end when switching from loader to backhoe controls',
                'It tilts the operator\'s position to improve visibility over the loader bucket',
                'It locks the operator in position during travel on rough terrain',
              ],
              correctIndex: 1,
              explanation: 'The swing seat rotates approximately 180° so the operator faces the backhoe attachment and its dedicated control levers, rather than the loader controls. Always come to a complete stop before swinging the seat.',
            },
            {
              question: 'Which component allows a wheel loader to turn in a tight radius despite its large size?',
              options: [
                'Rear-wheel steering similar to a forklift',
                'Articulated frame steering — the front and rear halves pivot at a central joint',
                'Independent track steering',
                'All-wheel crab steering',
              ],
              correctIndex: 1,
              explanation: 'Wheel loaders use articulated frame steering: the front and rear halves of the machine pivot relative to each other at a central joint, allowing a very tight turning radius. This articulation point is a pinch-point hazard — never stand between the halves while the engine is running.',
            },
            {
              question: 'A loader-backhoe operator wants to pick up a concrete pipe using the backhoe. What must they verify before making the lift?',
              options: [
                'The loader bucket is raised to counterbalance the load',
                'The load is within the backhoe\'s rated lift capacity at the specific radius and angle',
                'The stabilizers are retracted to allow the machine to reposition',
                'The TLB has at least half a tank of fuel',
              ],
              correctIndex: 1,
              explanation: 'The backhoe end of a TLB has a rated lift capacity that varies with radius and boom/dipperstick angle. Exceeding this capacity can tip the machine over the rear. Stabilizers must be deployed for any lift, and the load chart or manufacturer rating must be respected.',
            },
            {
              question: 'What hazard does the articulation joint of a wheel loader create for ground personnel?',
              options: [
                'Electrical shock from hydraulic lines',
                'Crush hazard — the front and rear halves can pinch together during steering',
                'Slipping hazard from hydraulic fluid leaks at the joint',
                'No hazard; the joint is fully guarded by design',
              ],
              correctIndex: 1,
              explanation: 'The articulation joint is a severe crush/pinch-point hazard. Personnel must never stand between the front and rear halves of the machine while the engine is running. Always chock the frame before performing any maintenance in this area.',
            },
          ],
        },
        {
          id: '1c-m2-s3',
          title: 'Hydraulics',
          durationHours: 1.5,
          learningObjectives: [
            'Apply Pascal\'s principle to explain force multiplication in hydraulic cylinders',
            'Identify the function of pressure relief valves, flow control valves, and directional control valves',
            'Recognize the warning signs of hydraulic system problems (overheating, cavitation, contamination)',
            'Describe proper hydraulic fluid maintenance procedures',
          ],
          topics: [
            'Pascal\'s principle: pressure applied to a fluid transmits equally in all directions',
            'Force multiplication: F = P × A; large bore cylinder generates more force at same pressure',
            'Hydraulic pump types: gear, vane, piston — displacement and flow rate',
            'Pressure relief valve: opens at set pressure to divert flow back to tank, preventing damage',
            'Directional control valve (DCV): routes flow to correct cylinder or motor',
            'Flow control valve: regulates speed of cylinder or motor movement',
            'Hydraulic cylinders: single-acting (gravity return) vs. double-acting (powered both ways)',
            'Hydraulic accumulators: store pressurized fluid for emergency functions',
            'Hydraulic fluid: ISO VG 46 common in construction equipment; viscosity and cleanliness matter',
            'Fluid contamination: particles, water, and air cause valve wear, pump damage, and foaming',
            'Cavitation: pump starvation — air enters system, causes pitting and noise',
            'Overheating: exceeds fluid viscosity range, accelerates seal degradation',
            'Common inspection checks: fluid level, hose condition, fitting tightness, cooler fins',
          ],
          resources: [
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.602 — Material Handling Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'A hydraulic cylinder has a bore area of 10 in² and the system pressure is 2,000 psi. What is the theoretical pushing force?',
              options: [
                '200 lbs',
                '2,000 lbs',
                '20,000 lbs',
                '200,000 lbs',
              ],
              correctIndex: 2,
              explanation: 'Force = Pressure × Area = 2,000 psi × 10 in² = 20,000 lbs. This is Pascal\'s principle at work — small cylinders generate modest force; large bore cylinders can generate tens of thousands of pounds at typical construction equipment pressures.',
            },
            {
              question: 'If a hydraulic pressure relief valve is set at 3,000 psi, what happens when load pressure exceeds that setting?',
              options: [
                'The pump shuts down automatically',
                'The relief valve opens and diverts flow back to the tank',
                'System pressure slowly climbs above 3,000 psi until the hose bursts',
                'The directional control valve closes automatically',
              ],
              correctIndex: 1,
              explanation: 'Relief valves are normally-closed valves that open at a set cracking pressure, diverting excess flow back to the tank. This protects cylinders, hoses, and pump from overpressure damage — they do not shut the pump off.',
            },
            {
              question: 'You hear a whining or grinding noise from the hydraulic pump on your wheel loader. This most likely indicates:',
              options: [
                'The hydraulic fluid is too hot',
                'Cavitation — the pump is not receiving adequate fluid (low level or clogged strainer)',
                'The pressure relief valve is stuck open',
                'The hydraulic oil filter is full and needs replacement',
              ],
              correctIndex: 1,
              explanation: 'Cavitation occurs when the pump tries to move more fluid than is being supplied to its inlet — air fills the void. The characteristic whine or grinding is from air bubbles imploding inside the pump, causing pitting and accelerated wear. Check fluid level and inlet strainer immediately.',
            },
            {
              question: 'You notice the hydraulic oil on your loader-backhoe looks milky or foamy. What does this indicate?',
              options: [
                'The fluid is brand new and has not been broken in yet',
                'Water contamination — possibly from a failed cylinder rod seal or water in the reservoir',
                'The fluid temperature is too low for operation',
                'The fluid has reached optimal operating viscosity',
              ],
              correctIndex: 1,
              explanation: 'Milky or foamy hydraulic fluid is a clear sign of water contamination, which dramatically reduces lubrication quality and can cause corrosion and valve sticking. The system must be drained, flushed, and refilled before returning to service.',
            },
            {
              question: 'What is the purpose of a hydraulic flow control valve?',
              options: [
                'To set the maximum system pressure',
                'To determine which cylinder or motor receives fluid',
                'To regulate the speed of a cylinder or motor by controlling fluid flow rate',
                'To filter contaminants from the hydraulic fluid',
              ],
              correctIndex: 2,
              explanation: 'Flow control valves regulate speed: more flow = faster movement; less flow = slower movement. This is distinct from pressure relief valves (set max pressure) and directional control valves (route flow direction).',
            },
          ],
        },
      ],
    },
    {
      id: '1c-m3',
      title: 'Safe Operation',
      orderInCourse: 3,
      estimatedHours: 5,
      sessions: [
        {
          id: '1c-m3-s1',
          title: 'Inspections',
          durationHours: 2,
          learningObjectives: [
            'Conduct a systematic pre-shift inspection of boom trucks, loader-backhoes, and wheel loaders',
            'Identify defects that must remove a machine from service immediately',
            'Apply OSHA 29 CFR 1926 Subpart CC inspection requirements to boom trucks',
            'Document defects properly per MA and OSHA requirements',
          ],
          topics: [
            'OSHA 29 CFR 1926.1412: required crane/boom truck inspection frequency — shift, monthly, annual',
            'Pre-shift visual: structural cracks in boom sections, welds, and mounting points',
            'Wire rope inspection: broken wires, kinks, crushing, corrosion (ASME B30.5 discard criteria)',
            'Boom extension pins and locking systems: secure, not bent or missing',
            'Outrigger inspection: beam retract/extend function, float condition, hydraulic cylinders',
            'Anti-two-block device function test: required before each shift',
            'Load moment indicator (LMI) calibration and function test',
            'Hydraulic hoses and fittings: abrasion, bulging, weeping, improper routing',
            'Tires (loader-backhoe, wheel loader): pressure, tread depth, sidewall damage',
            'Bucket and attachment security: pins, retaining clips, quick-attach mechanism',
            'Stabilizer pads: cracks, wear, and size appropriate for ground conditions',
            'Fluid levels: engine oil, coolant, hydraulic oil, fuel — check before every shift',
            'Lights, horn, backup alarm: operational per OSHA 1926.602',
            'Tagging out: "Do Not Operate" tag procedure and authority',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1926.1412 — Inspections (Cranes/Boom Trucks)',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1412',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.602 — Material Handling Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'Under OSHA 29 CFR 1926.1412, how often must a boom truck undergo a shift inspection?',
              options: [
                'Once per week by the operator',
                'Before each shift by the operator or a qualified person',
                'Once per month by a certified inspector',
                'Only before lifts over 75% of rated capacity',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.1412 requires a visual inspection before each shift. The operator is the front line of this inspection — catching problems before the shift starts prevents accidents and equipment damage.',
            },
            {
              question: 'During a boom truck pre-shift inspection, you find the anti-two-block (ATB) device is not functioning. What must you do?',
              options: [
                'Operate carefully and watch the load block closely',
                'Tag the machine "Do Not Operate" — ATB must be functional before any crane use',
                'Operate at reduced height to prevent two-blocking',
                'Notify the supervisor but continue operating until a replacement arrives',
              ],
              correctIndex: 1,
              explanation: 'A non-functional ATB device is a go/no-go item under OSHA 1926 Subpart CC. Two-blocking can snap wire rope or destroy the boom. The machine must not be used for crane lifts until the ATB is repaired and tested.',
            },
            {
              question: 'Per ASME B30.5 wire rope discard criteria, how many broken wires in one lay length of a 6×19 rope is the maximum before it must be removed from service?',
              options: [
                '2 broken wires',
                '6 broken wires',
                '12 broken wires',
                '18 broken wires',
              ],
              correctIndex: 1,
              explanation: 'ASME B30.5 specifies that wire rope on cranes must be discarded when 6 or more broken wires appear in one lay length (one complete spiral) of a 6-strand rope. Additional criteria include kinking, crushing, bird-caging, and corrosion.',
            },
            {
              question: 'During a loader-backhoe pre-shift inspection, you find a hydraulic hose with a visible bulge but no leak. What is the correct action?',
              options: [
                'Continue operating — it is cosmetic until fluid appears',
                'Wrap the hose with tape and monitor it through the shift',
                'Tag the machine out of service — a bulge indicates internal delamination and imminent failure',
                'Reduce hydraulic operating pressure and monitor the bulge',
              ],
              correctIndex: 2,
              explanation: 'A bulge in a hydraulic hose indicates the inner lining has delaminated and the outer braid is containing the pressure. Failure is imminent. The machine must be tagged out until the hose is replaced — a burst hose can inject fluid at high pressure and cause loss of control.',
            },
            {
              question: 'OSHA 29 CFR 1926.602 requires all self-propelled construction equipment to have which safety feature when traveling in reverse?',
              options: [
                'A certified spotter walking behind the machine',
                'An audible backup alarm that sounds automatically when in reverse',
                'A flashing amber warning light',
                'Both a spotter and a backup alarm in all cases',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.602 requires an audible alarm that automatically sounds when equipment is put in reverse. The alarm must be audible above surrounding noise. A spotter is an additional best practice but the alarm is the mandatory baseline requirement.',
            },
            {
              question: 'You find a crack at the weld connecting the boom\'s base section to the turntable on a boom truck. What do you do?',
              options: [
                'Monitor it — small cracks are acceptable under ASME B30.5',
                'Grind the crack smooth and continue operating',
                'Remove the machine from service immediately and notify management',
                'Continue operating with reduced loads until a welder is available',
              ],
              correctIndex: 2,
              explanation: 'Any crack in a structural weld on a crane boom is a critical defect. This is a "remove from service" condition with no exception. Continued operation risks catastrophic boom failure under load. Only a qualified welder and inspector can return the machine to service.',
            },
          ],
        },
        {
          id: '1c-m3-s2',
          title: 'Operating Safely',
          durationHours: 1.5,
          learningObjectives: [
            'Apply safe setup procedures for boom truck lifts including ground assessment and outrigger deployment',
            'Identify overhead hazard clearance requirements for boom trucks near power lines',
            'Describe safe operating procedures for loader-backhoes and wheel loaders',
            'Explain swing-radius exclusion zones and their enforcement',
          ],
          topics: [
            'Ground assessment before outrigger deployment: soil type, underground voids, pavement thickness',
            'Overhead power line clearance: OSHA 1926.1408 — minimum 20 ft for lines up to 350 kV, greater for higher voltages',
            'Utility location (Dig Safe / 811) before any ground disturbance',
            'Swing-radius exclusion zones: 230 CMR 6.00 prohibits persons within full working radius during crane operations',
            'Load path planning: plan the full lift path before picking the load',
            'Tandem lifts: require separate written plan and both operators must communicate',
            'Loader-backhoe travel: loader bucket low, backhoe bucket curled and raised slightly',
            'Wheel loader bucket carry position: low for stability, raised only for dumping',
            'Ramp and slope operations: load faces uphill when traveling with a load',
            'Pedestrian awareness: maintain visibility and use spotters when backing',
            'Weather restrictions: wind speed limits on load charts; ice and mud affect ground bearing',
            'Refueling: engine off, no smoking, ground the fuel nozzle on metal to prevent static',
            'Emergency procedures: lower load and shut down if structural, hydraulic, or electrical failure',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1926.1408 — Power Line Safety (Cranes)',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1408',
              type: 'osha',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.602 — Material Handling Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'OSHA 29 CFR 1926.1408 requires a minimum clearance of how many feet from energized power lines rated up to 350 kV when operating a boom truck?',
              options: [
                '10 feet',
                '15 feet',
                '20 feet',
                '25 feet',
              ],
              correctIndex: 2,
              explanation: 'OSHA 1926.1408 sets the minimum clearance at 20 feet for lines up to 350 kV. This distance applies to the boom, load line, and load — not just the cab. When in doubt, contact the utility company and request a line de-energized or insulated before beginning work.',
            },
            {
              question: 'You are operating a wheel loader on a ramp. You have a loaded bucket. In which direction should the load face?',
              options: [
                'Load faces downhill to see where you are going',
                'Load faces uphill to keep weight over the drive axle and improve stability',
                'Direction does not matter on grades under 15%',
                'Load faces downhill so the bucket can be lowered quickly if needed',
              ],
              correctIndex: 1,
              explanation: 'With a loaded bucket on a ramp, always travel with the load facing uphill. This keeps the heavy end closer to the uphill slope, reducing the risk of tipping forward (over the load) if you stop suddenly or if a tire slips.',
            },
            {
              question: 'Under 230 CMR 6.00, what must be true before the operator can swing a boom truck\'s superstructure during a lift?',
              options: [
                'The site foreman must be watching',
                'The load must be less than 50% of rated capacity',
                'No persons may be within the full working radius of the machine',
                'The swing must be less than 90 degrees',
              ],
              correctIndex: 2,
              explanation: '230 CMR 6.00 prohibits any persons within the full working radius during boom/load operations. The operator must confirm the area is clear before initiating any swing movement — no exceptions, regardless of load weight.',
            },
            {
              question: 'Before setting up a boom truck on a paved surface (parking lot), what ground condition must you assess?',
              options: [
                'Asphalt color and age only',
                'Pavement thickness and subgrade capacity — pavement can shear under outrigger point loads',
                'Whether the lot is marked as private property',
                'Distance to the nearest storm drain',
              ],
              correctIndex: 1,
              explanation: 'Asphalt pavement may look stable but can punch through under concentrated outrigger loads, especially over soft subgrade or underground voids (utilities, drainage). Outrigger pads spread the load, but you must still assess and potentially probe for subsurface conditions.',
            },
            {
              question: 'When traveling a loader-backhoe on a job site between work areas, how should the machine be configured?',
              options: [
                'Loader bucket raised to see over obstacles; backhoe bucket on the ground as a brake',
                'Loader bucket low (just above ground); backhoe bucket curled and raised slightly off the ground',
                'Both buckets raised to maximize ground clearance',
                'Loader bucket dumped open; backhoe at full extension for balance',
              ],
              correctIndex: 1,
              explanation: 'During travel the loader bucket should be in the low carry position (12–18 inches off ground) for stability, and the backhoe bucket should be curled and held slightly above ground to prevent dragging and to keep the center of gravity low.',
            },
          ],
        },
        {
          id: '1c-m3-s3',
          title: 'Hand Signals',
          durationHours: 1.5,
          learningObjectives: [
            'Demonstrate the SAE J1307 hand signals required by 230 CMR 6.00 for boom truck operations',
            'Identify the designated signaler\'s responsibilities and positioning requirements',
            'Apply the Emergency Stop signal and explain when it takes absolute priority',
            'Explain radio communication protocols as an alternative to hand signals',
          ],
          topics: [
            '230 CMR 6.00 requires SAE J1307 hand signals for all 1C equipment operations',
            'Only approved signaler may direct the operator',
            'SAE J1307 signals: hoist up, hoist down, boom up, boom down, extend boom, retract boom, swing (left/right), travel, stop, emergency stop',
            'Emergency Stop: crossed arms — takes priority over all other instructions from any person',
            'Signaler positioning: clear line of sight to operator at all times',
            'Operator must stop immediately if signaler contact is lost',
            'One signaler per machine — no relay or substitute except for Emergency Stop',
            'Radio communication: acceptable alternative when both parties can communicate clearly',
            'Radio protocol: state machine/operator, describe intended movement, confirm receipt',
            'Night operations: illuminated signals or radio required',
            'Conflicting signals: STOP until conflict is resolved; Emergency Stop always wins',
          ],
          resources: [
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'SAE J1307 Hand Signals — Quick Reference Guide',
              url: '/hand-signals',
              type: 'reference',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'Under 230 CMR 6.00, who is the ONLY person authorized to direct a boom truck operator\'s movements on a job site?',
              options: [
                'The general contractor\'s site superintendent',
                'Any crew member present at the job site',
                'The approved signaler assigned to the machine',
                'Either the operator or the site safety officer',
              ],
              correctIndex: 2,
              explanation: '230 CMR 6.00 requires that only the approved signaler direct the operator. Taking direction from anyone else — even a supervisor — violates the regulation. The only exception is a universal Emergency Stop, which any person can give.',
            },
            {
              question: 'You are operating a boom truck and lose sight of your signaler mid-swing. What must you do?',
              options: [
                'Slow the swing and look for the signaler',
                'Complete the swing to a safe position and then stop',
                'Stop all machine movement immediately',
                'Switch to radio and ask the signaler to reposition',
              ],
              correctIndex: 2,
              explanation: 'If visual contact with the signaler is lost at any time, 230 CMR 6.00 requires the operator to stop immediately. A signaler you cannot see cannot safely direct the machine. No relay or substitution is permitted.',
            },
            {
              question: 'The SAE J1307 Emergency Stop signal is given by:',
              options: [
                'One hand raised with palm facing the operator',
                'Both arms raised straight above the head',
                'Arms crossed at the wrists in front of the chest',
                'Pointing downward rapidly with both index fingers',
              ],
              correctIndex: 2,
              explanation: 'Arms crossed at the wrists in front of the chest is the universal Emergency Stop signal per SAE J1307. This signal must be obeyed immediately regardless of who gives it — it takes absolute priority over any other instruction.',
            },
            {
              question: 'You receive a "hoist up" hand signal from your signaler and simultaneously a verbal "stop" from the site superintendent. What should you do?',
              options: [
                'Follow the site superintendent — they have overall authority',
                'Follow the signaler — they are the designated authority for directing movements',
                'Stop all motion and wait until you receive a clear, unambiguous single signal',
                'Follow whichever instruction you judge to be safer',
              ],
              correctIndex: 2,
              explanation: 'Conflicting signals require the operator to stop. Neither the superintendent\'s verbal instruction nor the signaler\'s hand signal takes priority over the other in a conflict — the correct action is to stop until the conflict is resolved and a single clear signal is received.',
            },
            {
              question: 'Which SAE J1307 standard specifies the required hand signals for 1C equipment under 230 CMR 6.00?',
              options: [
                'SAE J386-1969 (seat belts)',
                'SAE J1307-2023 (hand signals for excavating machinery)',
                'SAE J320a (rollover protective structures)',
                'SAE J237 (braking performance)',
              ],
              correctIndex: 1,
              explanation: 'SAE J1307 is the hand signal standard referenced by 230 CMR 6.00 for hoisting and excavating machinery in Massachusetts. SAE J386, J320a, and J237 cover different equipment safety topics entirely.',
            },
            {
              question: 'When is radio communication an acceptable substitute for hand signals on a 1C operation?',
              options: [
                'Never — 230 CMR 6.00 requires hand signals at all times',
                'When both the operator and signaler have reliable two-way radios and clear communication',
                'Only during night operations when visibility is reduced',
                'Only when a supervisor approves the deviation from hand signals',
              ],
              correctIndex: 1,
              explanation: 'Radio communication is an acceptable alternative to hand signals provided both parties have reliable two-way radios and communication is clear. The same one-signaler-per-machine rule applies. If communication becomes unclear, the operator must stop.',
            },
          ],
        },
      ],
    },
    {
      id: '1c-m4',
      title: 'OSHA & Review',
      orderInCourse: 4,
      estimatedHours: 5,
      sessions: [
        {
          id: '1c-m4-s1',
          title: 'OSHA Overview',
          durationHours: 1.5,
          learningObjectives: [
            'Apply OSHA 29 CFR 1926 Subpart CC requirements to telescoping boom truck operations',
            'Explain OSHA 29 CFR 1926.602 requirements for loader-backhoes and wheel loaders',
            'Identify common OSHA citations for 1C equipment operations',
            'Describe PPE and site safety requirements under OSHA 1926',
          ],
          topics: [
            '29 CFR 1926 Subpart CC — Cranes and Derricks in Construction: applies to boom trucks',
            '1926.1400 — scope: boom trucks used in construction are covered',
            '1926.1408 — power line safety: 20 ft minimum clearance to 350 kV lines',
            '1926.1412 — inspection: shift, monthly (30-day), and annual (qualified person)',
            '1926.1416 — operational aids: ATB device, LMI requirements',
            '1926.1417 — operations: operator must be certified or qualified; documentation required',
            '29 CFR 1926.602 — material handling: applies to loader-backhoes and wheel loaders',
            '1926.602(a) — earthmoving equipment: seat belts, rollover protection (ROPS), backup alarms',
            'PPE requirements: hard hat, safety glasses, high-visibility vest, steel-toed boots',
            'Lock-out / Tag-out (LOTO): before any maintenance on powered equipment',
            'Common citations: inadequate inspection records, ATB not functional, no backup alarm, no seat belt',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1926 Subpart CC — Cranes & Derricks in Construction',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1400',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.602 — Material Handling Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'OSHA 29 CFR 1926 Subpart CC applies to which 1C equipment?',
              options: [
                'Wheel loaders and loader-backhoes only',
                'Telescoping boom trucks used in construction',
                'All 1C equipment equally',
                'No 1C equipment — Subpart CC only covers tower cranes',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926 Subpart CC (Cranes and Derricks in Construction) covers telescoping boom trucks used as cranes in construction. Loader-backhoes and wheel loaders fall under 1926.602 (Material Handling Equipment) instead.',
            },
            {
              question: 'Under OSHA 1926.602, what rollover protection is required on a wheel loader?',
              options: [
                'No rollover protection is required — it is optional',
                'A rollover protective structure (ROPS) meeting SAE standards must be installed',
                'A rollover net around the operator\'s cab is sufficient',
                'Only machines over 10,000 lbs require ROPS',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.602 requires earthmoving equipment to be equipped with ROPS that meets SAE J320 or equivalent standards. ROPS must be combined with a seat belt — the operator must be restrained or the ROPS provides no protection in an actual rollover.',
            },
            {
              question: 'A boom truck operator on a construction site has not been certified or qualified per OSHA 1926.1417. This is an OSHA citation for:',
              options: [
                'A de minimis violation with no penalty',
                'An other-than-serious violation',
                'A serious violation — employer can be fined per occurrence',
                'Only a verbal warning for first offense',
              ],
              correctIndex: 2,
              explanation: 'Operator qualification/certification requirements under OSHA 1926.1417 are serious violations. OSHA can cite the employer for each day of non-compliance. Both MA licensing and OSHA qualification requirements must be met independently.',
            },
            {
              question: 'Under OSHA 1926.602, what must a loader-backhoe have when traveling in reverse?',
              options: [
                'A certified spotter walking behind the machine at all times',
                'An audible backup alarm that activates automatically when the machine reverses',
                'A flashing amber warning light on the roof',
                'Both an alarm and a spotter in all circumstances',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.602 requires an audible reverse alarm that activates automatically. The alarm must be loud enough to be heard above surrounding noise. A spotter supplements but does not replace the alarm requirement.',
            },
            {
              question: 'Which OSHA standard specifically addresses the minimum power line clearance distance for boom truck crane operations?',
              options: [
                '29 CFR 1926.502 — Fall Protection',
                '29 CFR 1926.602 — Material Handling Equipment',
                '29 CFR 1926.1408 — Power Line Safety',
                '29 CFR 1926.21 — Safety Training',
              ],
              correctIndex: 2,
              explanation: 'OSHA 29 CFR 1926.1408 specifically governs power line safety for cranes and derricks in construction (Subpart CC). It sets the 20 ft minimum clearance for lines up to 350 kV and provides procedures for working closer under controlled conditions.',
            },
          ],
        },
        {
          id: '1c-m4-s2',
          title: 'Practice Exam 1',
          durationHours: 1.5,
          learningObjectives: [
            'Apply knowledge from Modules 1–3 to scenario-based questions',
            'Identify correct answers when competing options appear plausible',
            'Manage time across a 30-question practice set',
            'Recognize common distractor patterns in hoisting exam questions',
          ],
          topics: [
            'Mixed scenario questions: regulatory, equipment, and operational safety',
            'Time management strategy: 70 seconds per question for a 30-question exam',
            'Eliminating clearly wrong answers first (process of elimination)',
            'Key numbers to memorize: 70% passing, 60-day wait, $75 fee, 18 minimum age, 2-year license, 20 ft power line clearance',
            'Load chart interpretation practice questions',
            'Inspection go/no-go decision questions',
          ],
          resources: [
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926 Subpart CC — Cranes & Derricks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1400',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'A boom truck load chart shows 5,000 lbs capacity at 30 ft radius with outriggers fully extended. The rigging weighs 400 lbs. What is the maximum net load you can lift?',
              options: [
                '5,400 lbs — rigging weight is additive',
                '5,000 lbs — rigging weight does not count',
                '4,600 lbs — rated capacity minus rigging weight',
                '4,500 lbs — apply a 10% safety deduction',
              ],
              correctIndex: 2,
              explanation: 'Rated capacity is the TOTAL suspended load. You subtract all rigging weight (400 lbs) from the chart capacity (5,000 lbs) to get the maximum net hook load: 4,600 lbs. Never add rigging weight on top of rated capacity.',
            },
            {
              question: 'You are checking outriggers before a boom truck lift and notice one float has a crack through its mounting weld. What do you do?',
              options: [
                'Proceed — one float is sufficient with three solid outriggers',
                'Tag the machine out of service — a cracked outrigger float weld is a structural defect',
                'Place extra cribbing under the cracked float and proceed',
                'Reduce the lift capacity by 25% and proceed',
              ],
              correctIndex: 1,
              explanation: 'A cracked weld on an outrigger float is a structural defect requiring removal from service. Outriggers carry the full weight of the machine plus load — a float that fails during a lift can cause a sudden tip-over.',
            },
            {
              question: 'The MA hoisting exam has a passing score of 70%. On a 40-question exam, what is the minimum number of correct answers needed to pass?',
              options: [
                '24 correct',
                '26 correct',
                '28 correct',
                '30 correct',
              ],
              correctIndex: 2,
              explanation: '70% of 40 questions = 28 correct answers needed to pass. Getting 27 or fewer means you score below 70% and must wait 60 days before retesting.',
            },
            {
              question: 'A coworker (not the designated signaler) gives you a "hoist up" signal because the signaler briefly stepped away. What should you do?',
              options: [
                'Comply — it is a simple lift and they clearly mean well',
                'Comply only if the coworker is a licensed operator',
                'Do not hoist — only the approved signaler may direct your movements',
                'Hoist slowly and watch for the signaler to return',
              ],
              correctIndex: 2,
              explanation: '230 CMR 6.00 allows only the approved signaler to direct the operator. Taking direction from any other person violates the regulation regardless of how simple the movement or how experienced the coworker is. Wait for the signaler or stop operations.',
            },
            {
              question: 'If you fail the 1C exam today, what is the earliest date you can retake it?',
              options: [
                '7 days from today',
                '30 days from today',
                '60 days from today',
                'Immediately — no waiting period applies',
              ],
              correctIndex: 2,
              explanation: 'MA regulations require 60 days after a failed attempt before retesting for any hoisting license class including 1C. Use this time to thoroughly review your weak areas rather than rushing back in unprepared.',
            },
            {
              question: 'An unlicensed worker operates a wheel loader because the licensed operator called out sick. No accident occurs. What is the potential legal consequence?',
              options: [
                'No consequence — only accidents trigger penalties',
                'A warning letter to the employer only',
                'Both the unlicensed worker and the employer face civil penalties of up to $500 per day under MGL §53',
                'Only the employee faces penalties — employers are not liable for employee decisions',
              ],
              correctIndex: 2,
              explanation: 'MGL §53 creates liability for both the unlicensed operator and the employer. The penalty is per day, per violation. The absence of an accident is irrelevant — unlicensed operation is the violation.',
            },
          ],
        },
        {
          id: '1c-m4-s3',
          title: 'Practice Exam 2',
          durationHours: 2,
          learningObjectives: [
            'Complete a comprehensive second practice exam covering all 1C content areas',
            'Review the highest-frequency topics from all four modules',
            'Develop a final exam-day strategy',
            'Identify remaining weak areas requiring last-minute review',
          ],
          topics: [
            'Comprehensive scenario-based questions across all modules',
            'Time pacing: simulating real exam conditions',
            'Final review: load chart reading, outrigger setup, ATB, inspection go/no-go',
            'Final review: 230 CMR 6.00 signaler rules, SAE J1307 signals',
            'Exam day logistics: valid MA ID, arrive early, no phones in exam room',
            'After the exam: how to check your score and apply for the license',
          ],
          resources: [
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: true,
            },
            {
              label: 'Apply for a Hoisting Engineer License',
              url: 'https://www.mass.gov/how-to/apply-for-a-hoisting-engineer-license',
              type: 'reference',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'Which of the following is a go/no-go defect requiring immediate removal from service on a boom truck?',
              options: [
                'Minor dirt accumulation on the outrigger beams',
                'A non-functional anti-two-block (ATB) device',
                'A slightly worn rubber pad on one outrigger float',
                'A small cosmetic dent on the carrier fender',
              ],
              correctIndex: 1,
              explanation: 'A non-functional ATB device is a hard stop — the machine cannot be used for crane lifts. Dirt, cosmetic dents, and normal wear items are not go/no-go conditions but should be documented. The ATB failure must be repaired and retested before returning to service.',
            },
            {
              question: 'Which MA regulation requires the use of SAE J1307 hand signals for 1C equipment operations?',
              options: [
                'MGL Chapter 146 §53',
                '230 CMR 6.00',
                'OSHA 29 CFR 1926.1408',
                'ASME B30.5',
              ],
              correctIndex: 1,
              explanation: '230 CMR 6.00 is the MA state regulation that mandates SAE J1307 hand signals for hoisting machinery including 1C equipment. MGL Chapter 146 is the statute; the other references are federal/industry standards.',
            },
            {
              question: 'A wheel loader is traveling on a job site road with a loaded bucket elevated at full height. Why is this unsafe?',
              options: [
                'The elevated bucket increases wind resistance and fuel consumption',
                'The high center of gravity greatly increases tip-over risk on uneven ground or during turns',
                'The bucket obscures the headlights',
                'It is only unsafe if the load exceeds 2,000 lbs',
              ],
              correctIndex: 1,
              explanation: 'Traveling with the bucket elevated raises the center of gravity, making the machine highly susceptible to tipping on slopes, soft ground, or during turns. The bucket carry position (12–18 inches off ground) keeps the center of gravity low and stable.',
            },
            {
              question: 'Before beginning a tandem lift with two boom trucks, what is required per OSHA Subpart CC?',
              options: [
                'Both operators must have 1C licenses — no additional planning required',
                'A written lift plan must be developed and both operators must review it',
                'Only the primary lift crane operator needs to review the load chart',
                'The site superintendent must be present but no written plan is required',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926 Subpart CC requires a written lift plan for tandem lifts. The plan must address load distribution between cranes, communication, signal responsibilities, and contingencies. Both operators must understand and follow the plan.',
            },
            {
              question: 'On exam day you encounter a question about a regulation you do not recognize. What is the best test-taking strategy?',
              options: [
                'Skip the question and return to it — it likely will not appear again',
                'Use process of elimination to remove clearly wrong answers, then select the best remaining option',
                'Guess "C" — it is statistically the most common correct answer',
                'Leave it blank — wrong answers are penalized more than blanks',
              ],
              correctIndex: 1,
              explanation: 'Process of elimination is the most effective strategy when you are unsure. MA hoisting exams do not penalize wrong answers, so always answer every question. Eliminating one or two clearly wrong choices significantly improves your odds on the remainder.',
            },
            {
              question: 'A loader-backhoe is being used to lift a concrete panel. The operator deploys only the two rear stabilizers (behind the backhoe boom) and leaves the front ones retracted. What is the risk?',
              options: [
                'None — only the rear stabilizers are needed for backhoe lifts',
                'The machine can tip sideways because one side has no stabilizer support',
                'The machine can tip forward over the rear stabilizers',
                'The front stabilizers are decorative; this is safe procedure',
              ],
              correctIndex: 1,
              explanation: 'All four stabilizers must be deployed before backhoe lifting operations. Only deploying the two on one side leaves the opposite side unsupported — a heavy lift with any lateral offset can tip the machine sideways. Both stabilizers and both rear outriggers must be down and bearing on solid ground.',
            },
            {
              question: 'What is the correct immediate action if the LMI on a boom truck alarms at 90% of rated capacity while you are mid-lift?',
              options: [
                'Continue the lift quickly to get the load to its destination before reaching 100%',
                'Extend the boom to increase the radius and reduce the percentage',
                'Stop all load movement, assess the situation, and set the load down safely if possible',
                'Override the LMI alarm — it is conservative and 10% overage is acceptable',
              ],
              correctIndex: 2,
              explanation: 'An LMI alarm at 90% means you are approaching the load chart limit. Stop, assess, and do not continue the lift without understanding why you are at 90%. Extending the boom increases radius and further reduces capacity — never the right response. Overriding alarms is never acceptable.',
            },
          ],
        },
      ],
    },
  ],
};
