import { LicenseRestriction } from '../types';

export const restriction_1d: LicenseRestriction = {
  code: '1D',
  name: 'Industrial lift trucks',
  description: 'Forklifts, reach trucks, telehandlers.',
  equipmentCovered: ['Forklifts', 'Reach trucks', 'Telehandlers'],
  totalHours: 18,
  modules: [
    {
      id: '1d-m1',
      title: 'Legal & Regulatory Foundation',
      orderInCourse: 1,
      estimatedHours: 4,
      sessions: [
        {
          id: '1d-m1-s1',
          title: 'Licensing Requirements',
          durationHours: 2,
          learningObjectives: [
            'State the minimum age and exam passing score for a 1D license',
            'Explain when a hoisting license is required to operate an industrial lift truck in Massachusetts',
            'Describe the company-property exemption for industrial lift trucks under MGL c.146 §53',
            'Explain the license duration and the application process through the Division of Occupational Licensure',
          ],
          topics: [
            'MGL Chapter 146 §53 — who must hold a hoisting license to operate hoisting machinery',
            'Class 1D scope: industrial lift trucks — counterbalanced forklifts and reach trucks; telehandlers and rough-terrain forklifts by special request',
            'License hierarchy: 1A covers the most equipment, 1D is the most restrictive Class 1 grade',
            'Minimum age requirement: 18 years old',
            'Exam passing score: 70% minimum',
            '60-day waiting period after a failed attempt',
            '$75 non-refundable application fee per restriction class',
            'Company-property exemption: a company operating lift trucks exclusively on its own property, where the general public has no access, may be exempt if it meets the §53 conditions (licensed supervisory employee on site, approved in-service training program)',
            'Application through the MA Division of Occupational Licensure (DOL), Office of Public Safety and Inspections',
          ],
          resources: [
            {
              label: 'MGL Chapter 146 § 53 — Necessity of licenses; classification; exemptions',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146/Section53',
              type: 'regulation',
              required: true,
            },
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: true,
            },
            {
              label: 'Apply for a Hoisting Engineer License',
              url: 'https://www.mass.gov/how-to/apply-for-a-hoisting-engineer-license',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'What is the minimum passing score on the Massachusetts 1D hoisting engineer exam?',
              options: ['60%', '65%', '70%', '75%'],
              correctIndex: 2,
              explanation: 'The passing score is 70%. Score below 70% and you must wait 60 days before retesting — budget your study time so you pass on the first attempt.',
            },
            {
              question: 'A warehouse company operates counterbalanced forklifts exclusively inside its own facility, and the general public has no access to any area where the forklifts run. Under MGL c.146 §53, this company may be:',
              options: [
                'Required to license every operator with no exception',
                'Exempt from the licensing requirement if it meets the §53 conditions, including having a licensed supervisory employee on site and an approved in-service training program',
                'Exempt only if every operator is over 21',
                'Exempt only if the forklifts are electric',
              ],
              correctIndex: 1,
              explanation: 'MGL §53 provides a narrow exemption for industrial lift trucks used exclusively on company property not open to the public — but only if the company meets the statutory conditions, including a licensed supervisory employee on site during operations and an approved in-service training program. The exemption is for the company, not a personal entitlement. Exam tip: the moment lift trucks operate where the public has access, or off company property, the exemption does not apply.',
            },
            {
              question: 'How long is a Massachusetts hoisting engineer license valid before renewal is required?',
              options: ['1 year', '2 years', '3 years', '5 years'],
              correctIndex: 1,
              explanation: 'The hoisting license is valid for 2 years. Always verify the current renewal cycle at mass.gov — renewal requirements can change.',
            },
            {
              question: 'What is the minimum age to obtain a Massachusetts 1D hoisting engineer license?',
              options: ['16', '17', '18', '21'],
              correctIndex: 2,
              explanation: 'MGL Chapter 146 sets the minimum age at 18. Applicants under 18 cannot obtain a hoisting license regardless of experience or training.',
            },
            {
              question: 'A landscaper uses a telehandler to place materials on a residential construction site. Does this work require a Massachusetts hoisting license?',
              options: [
                'No, telehandlers are never covered by the hoisting law',
                'No, because the operator works for a small company',
                'Yes — operating a lift truck on a job site that is not the operator\'s own company property requires a license',
                'Only if the telehandler lifts more than 5,000 lbs',
              ],
              correctIndex: 2,
              explanation: 'The company-property exemption only applies to lift trucks used exclusively on the company\'s own property where the public has no access. Construction and material-handling work on outside job sites requires a hoisting license — and a telehandler\'s variable-reach boom typically falls within Class 1 coverage.',
            },
            {
              question: 'What is the non-refundable application fee for each restriction class when applying for a Massachusetts hoisting engineer license?',
              options: ['$25', '$50', '$75', '$100'],
              correctIndex: 2,
              explanation: 'The application fee is $75 per restriction class and is non-refundable even if you fail the exam or your application is denied. Verify the current fee at mass.gov before applying.',
            },
            {
              question: 'How does the 1D license relate to the other Class 1 grades?',
              options: [
                '1D is the broadest license and covers all Class 1 equipment',
                '1D is the most restrictive Class 1 grade — it covers industrial lift trucks, while 1A covers the most equipment',
                '1D and 1A cover exactly the same equipment',
                '1D covers tower cranes and lattice-boom cranes',
              ],
              correctIndex: 1,
              explanation: 'In Class 1, the "A" grade covers the most equipment and each subsequent letter covers progressively less. 1D is the most restrictive grade, limited to industrial lift trucks. A 1A holder may operate 1D equipment, but a 1D holder may only operate lift trucks.',
            },
          ],
        },
        {
          id: '1d-m1-s2',
          title: 'Renewal Procedures',
          durationHours: 2,
          learningObjectives: [
            'Explain the renewal cycle and deadline for a 1D hoisting license',
            'Describe what happens to a license that lapses and how it is reinstated',
            'State the operating rules in 230 CMR 6.00 that apply to lift-truck operators, including the signaler and hand-signal requirements',
            'Explain employer and operator responsibilities for keeping a license valid',
          ],
          topics: [
            '230 CMR 6.00: the regulation that implements MGL Chapter 146 and sets minimum safety standards for hoisting machinery',
            'Renewal cycle: license valid 2 years; renew before expiration — no statutory grace period that permits continued operation',
            'Operating with an expired license is operating without a license under MGL §53',
            'Reinstatement after a lapse may require re-application and potentially re-examination',
            'SAE J1307 hand signals required by 230 CMR 6.00 — used when a signaler directs the operator',
            'Only an approved signaler may direct the operator; the operator stops if visual contact with the signaler is lost',
            'Civil penalties of up to $500 per day for unlicensed operation; employer liability for using unlicensed operators',
            'Operator responsibility to track expiration and renew on time; employer responsibility to verify valid licenses',
            'Keeping current with regulation changes through the Division of Occupational Licensure',
          ],
          resources: [
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'MGL Chapter 146 — full chapter text',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146',
              type: 'regulation',
              required: true,
            },
            {
              label: 'SAE J1307 Hand Signals — Quick Reference Guide',
              url: '/hand-signals',
              type: 'reference',
              required: true,
            },
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'Your 1D license expired three weeks ago. You plan to renew next week but need to move pallets today. Can you legally operate a forklift on a job site today?',
              options: [
                'Yes, there is a 30-day grace period after expiration',
                'Yes, if you have proof your renewal application was mailed',
                'No — an expired license is an invalid license, and operating with it violates MGL §53',
                'Yes, if your employer signs a liability waiver',
              ],
              correctIndex: 2,
              explanation: 'There is no grace period that permits continued operation. An expired license is an invalid license; operating with it exposes both you and your employer to civil penalties of up to $500 per day. Exam tip: renew before the expiration date, not after.',
            },
            {
              question: 'What is the relationship between MGL Chapter 146 and 230 CMR 6.00?',
              options: [
                'MGL Chapter 146 is federal law; 230 CMR 6.00 is state law',
                'MGL Chapter 146 is the statute passed by the legislature; 230 CMR 6.00 is the regulation that implements it',
                'They are two names for the same document',
                '230 CMR 6.00 replaced MGL Chapter 146 entirely',
              ],
              correctIndex: 1,
              explanation: 'MGL (Massachusetts General Law) is statute — passed by the legislature. 230 CMR 6.00 is the regulation that implements and expands Chapter 146 with specific technical and safety requirements.',
            },
            {
              question: 'Under 230 CMR 6.00, who is the only person authorized to direct a lift-truck operator\'s movements when a signaler is being used?',
              options: [
                'Any worker who happens to be nearby',
                'The site superintendent only',
                'The approved signaler assigned to direct the operation',
                'Either the operator or any supervisor',
              ],
              correctIndex: 2,
              explanation: 'Only an approved signaler may direct the operator. Taking direction from anyone else — even a supervisor — violates the regulation. SAE J1307 hand signals are the required signal standard.',
            },
            {
              question: 'How long is the waiting period before you may retake the hoisting exam after a failed attempt?',
              options: ['7 days', '30 days', '60 days', '90 days'],
              correctIndex: 2,
              explanation: 'You must wait 60 days after a failed attempt before retesting. Use that time to study the areas where you scored poorly rather than rushing back unprepared.',
            },
            {
              question: 'If a 1D license is allowed to lapse for an extended period, what is the most likely consequence?',
              options: [
                'The license automatically reactivates once you pay a small late fee',
                'Nothing — a hoisting license never truly expires',
                'Reinstatement may require re-application and potentially re-examination',
                'The license converts to a 1A license',
              ],
              correctIndex: 2,
              explanation: 'A lapsed license is not simply reactivated. Depending on how long it has lapsed, the Division of Occupational Licensure may require you to re-apply and re-test. The simplest path is to renew on time.',
            },
            {
              question: 'During a lift with a signaler, the operator loses sight of the signaler behind a rack. What must the operator do?',
              options: [
                'Continue slowly and watch for the signaler to reappear',
                'Stop all machine movement until visual contact with the signaler is restored',
                'Ask another worker to relay the signals',
                'Switch to operating by memory of the planned path',
              ],
              correctIndex: 1,
              explanation: '230 CMR 6.00 requires the operator to stop when visual contact with the signaler is lost. A signaler who cannot be seen cannot safely direct the machine, and no relay or substitute is permitted.',
            },
            {
              question: 'Who bears responsibility for ensuring a lift-truck operator holds a valid, current hoisting license?',
              options: [
                'The operator alone',
                'The employer alone',
                'Both the operator and the employer',
                'The Division of Occupational Licensure, which checks every job site',
              ],
              correctIndex: 2,
              explanation: 'The operator must keep their own license current, and the employer must verify that operators it directs are properly licensed. An employer who knowingly uses an unlicensed operator faces its own penalties under MGL Chapter 146.',
            },
          ],
        },
      ],
    },
    {
      id: '1d-m2',
      title: 'Equipment Systems',
      orderInCourse: 2,
      estimatedHours: 5,
      sessions: [
        {
          id: '1d-m2-s1',
          title: 'Forklift Anatomy',
          durationHours: 2,
          learningObjectives: [
            'Identify and name the major components of a counterbalanced forklift',
            'Explain the function of the mast, carriage, forks, and counterweight',
            'Describe how reach trucks and telehandlers differ from a standard counterbalanced forklift',
            'Explain the role of overhead guard and load backrest extension in operator and load protection',
          ],
          topics: [
            'Counterbalanced forklift: forks at the front, counterweight at the rear, no outriggers',
            'Mast: the vertical assembly that raises and lowers the carriage; channels, rollers, and lift chains',
            'Carriage: the plate the forks attach to; moves up and down the mast',
            'Forks (tines): rated as a set; heel wear and cracks are critical inspection points',
            'Load backrest extension: prevents the load from shifting back toward the mast and operator',
            'Counterweight: cast mass at the rear that balances the load on the forks — never alter or add to it without manufacturer approval',
            'Overhead guard (FOPS) and operator restraint system / seat belt',
            'Reach truck: forks extend forward on a pantograph or scissor mechanism; narrow-aisle warehouse use',
            'Telehandler / variable-reach rough-terrain forklift: telescoping boom, often outriggers, used on uneven ground',
          ],
          resources: [
            {
              label: 'OSHA Powered Industrial Trucks eTool — Types & Fundamentals',
              url: 'https://www.osha.gov/etools/powered-industrial-trucks/types-fundamentals',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1910.178 — Powered Industrial Trucks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.178',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'On a counterbalanced forklift, what is the purpose of the counterweight at the rear of the truck?',
              options: [
                'To add traction to the steer wheels',
                'To balance the weight of the load on the forks so the truck does not tip forward',
                'To protect the operator from falling objects',
                'To store the battery or fuel tank',
              ],
              correctIndex: 1,
              explanation: 'The counterweight offsets the load on the forks, keeping the combined center of gravity within the stability triangle. Exam tip: never add to or modify the counterweight without the manufacturer\'s written approval — it changes the truck\'s rated capacity and stability.',
            },
            {
              question: 'During an inspection you find a crack at the heel of one fork (where the blade meets the upright shank). What should you do?',
              options: [
                'Use the truck for light loads only',
                'Weld the crack and continue working',
                'Remove the truck from service until the forks are replaced',
                'Monitor the crack for the rest of the shift',
              ],
              correctIndex: 2,
              explanation: 'The heel carries the highest stress on a fork. A crack there can lead to sudden failure and a dropped load. Cracked forks must be taken out of service and replaced — field welding of forks is not acceptable.',
            },
            {
              question: 'How does a reach truck differ from a standard counterbalanced forklift?',
              options: [
                'A reach truck has no mast',
                'A reach truck\'s forks extend forward on a pantograph or scissor mechanism for narrow-aisle work',
                'A reach truck has a telescoping boom',
                'A reach truck cannot lift loads above shoulder height',
              ],
              correctIndex: 1,
              explanation: 'A reach truck uses a pantograph/scissor mechanism to extend the forks forward into a rack, allowing it to work in narrower aisles than a counterbalanced forklift. Its stability characteristics change as the forks reach out.',
            },
            {
              question: 'What is the function of the load backrest extension on a forklift carriage?',
              options: [
                'To increase the truck\'s rated capacity',
                'To keep the load from shifting rearward toward the mast and operator when the mast is tilted back or raised',
                'To act as a step for the operator',
                'To shield the hydraulic hoses',
              ],
              correctIndex: 1,
              explanation: 'The load backrest extension prevents the load — or part of it — from falling back toward the mast and operator. It is a required guard whenever the load could shift rearward.',
            },
            {
              question: 'Which feature distinguishes a telehandler from a standard warehouse forklift?',
              options: [
                'It has no overhead guard',
                'It uses a telescoping boom that extends up and out, and is built for uneven, rough-terrain ground',
                'It cannot carry palletized loads',
                'It has its counterweight at the front',
              ],
              correctIndex: 1,
              explanation: 'A telehandler (variable-reach rough-terrain forklift) has a telescoping boom that reaches both up and forward. Its capacity drops sharply as the boom extends, which is why it has a load chart, not a single rated capacity.',
            },
            {
              question: 'What is the primary purpose of the overhead guard on a forklift?',
              options: [
                'To keep rain off the operator',
                'To protect the operator from falling objects and small dropped loads',
                'To support the mast',
                'To house the lighting system',
              ],
              correctIndex: 1,
              explanation: 'The overhead guard is falling-object protection (FOPS-type). It is not designed to stop a full capacity load, but it protects the operator from smaller objects that could fall from an elevated load or from racking.',
            },
          ],
        },
        {
          id: '1d-m2-s2',
          title: 'Load Capacity & Stability',
          durationHours: 1.5,
          learningObjectives: [
            'Read a forklift data (capacity) plate and state the truck\'s rated capacity at its rated load center',
            'Explain the stability triangle and how the center of gravity must stay within it',
            'Explain how load weight and load center distance combine to create a load moment',
            'Explain how attachments and load center changes derate a truck\'s safe capacity',
          ],
          topics: [
            'Data / capacity plate: required by OSHA to be in place and legible; lists rated capacity, rated load center, mast height, fuel type, attachments',
            'Rated capacity stated at a rated load center — commonly 24 inches for trucks under 30,000 lb',
            'Load center: the horizontal distance from the face of the forks to the center of gravity of the load',
            'Stability triangle: the three support points — the two front wheels and the center pivot of the rear (steer) axle',
            'Center of gravity must stay inside the stability triangle or the truck tips; the combined CG shifts toward the load when loaded',
            'Load moment = load weight x load center distance; the truck stays stable only while the vehicle moment exceeds the load moment',
            'A load whose center of gravity is farther out than the rated load center reduces the safe capacity even if the weight is under the rated number',
            'Attachments add weight and often move the load center forward — both derate capacity; the plate must be updated for attachments',
            'Raising a load raises the combined center of gravity and reduces lateral stability',
          ],
          resources: [
            {
              label: 'OSHA 1910.178 App A — Stability of Powered Industrial Trucks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.178AppA',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA Powered Industrial Trucks eTool — Load Handling',
              url: 'https://www.osha.gov/etools/powered-industrial-trucks/load-handling',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1910.178 — Powered Industrial Trucks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.178',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'A forklift data plate reads "Rated capacity 5,000 lb at 24 in load center." You need to lift a load whose center of gravity is 36 inches from the fork face. What is true?',
              options: [
                'You can still lift 5,000 lb because the truck is rated for 5,000 lb',
                'The safe capacity is reduced because the load center is greater than the rated 24 inches',
                'The load center has no effect on capacity',
                'You can lift more than 5,000 lb because the load is spread out',
              ],
              correctIndex: 1,
              explanation: 'Rated capacity is only valid at the rated load center. A load center farther out than 24 inches increases the load moment, so the truck\'s safe capacity drops below 5,000 lb. Exam tip: both weight AND load center matter — never read the rating as a flat weight limit.',
            },
            {
              question: 'The forklift stability triangle is formed by which three points?',
              options: [
                'The two forks and the mast',
                'The two front wheels and the center pivot point of the rear axle',
                'The operator seat, the mast, and the counterweight',
                'The four wheels',
              ],
              correctIndex: 1,
              explanation: 'A counterbalanced forklift has a three-point suspension: the two front (drive) wheels and the pivot at the center of the rear (steer) axle. Connecting those three points forms the stability triangle. As long as the combined center of gravity stays inside it, the truck will not tip.',
            },
            {
              question: 'What does a forklift\'s "load moment" depend on?',
              options: [
                'Only the weight of the load',
                'Only the height the load is raised to',
                'Both the weight of the load and its load center distance from the fork face',
                'Only the fuel type of the truck',
              ],
              correctIndex: 2,
              explanation: 'Load moment = load weight x load center distance. A lighter load held far out can create the same tipping moment as a heavier load held close in. That is why rated capacity is always stated together with a load center.',
            },
            {
              question: 'You install a fork-mounted carton clamp attachment on a forklift. How does this affect the truck?',
              options: [
                'It has no effect on capacity or the data plate',
                'It increases the truck\'s capacity',
                'It adds weight and typically moves the load center forward, derating capacity — and the data plate must be updated',
                'It only matters if the attachment is hydraulic',
              ],
              correctIndex: 2,
              explanation: 'Attachments add weight and usually shift the load center forward, both of which reduce safe capacity. OSHA requires the capacity plate to be updated to reflect the truck-and-attachment combination.',
            },
            {
              question: 'Why does raising a load high on the mast reduce the truck\'s stability?',
              options: [
                'It increases the truck\'s rated capacity',
                'It raises the combined center of gravity, reducing lateral (sideways) stability',
                'It shifts the counterweight forward',
                'It has no effect on stability, only on speed',
              ],
              correctIndex: 1,
              explanation: 'Raising the load lifts the combined center of gravity. A higher CG is easier to push outside the stability triangle sideways, so an elevated load makes the truck much more prone to a lateral tipover, especially while turning.',
            },
            {
              question: 'OSHA requires that a forklift\'s capacity (data) plate be:',
              options: [
                'Removed when the truck is sold',
                'In place and maintained in a legible condition',
                'Painted over to prevent tampering',
                'Replaced every year regardless of condition',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1910.178 requires that all nameplates and markings be in place and legible. If the plate is missing or unreadable, the truck must not be operated until it is restored — the operator cannot safely judge capacity without it.',
            },
            {
              question: 'When a forklift picks up a load at its rated capacity and load center, where does the combined center of gravity move?',
              options: [
                'Toward the rear of the truck, behind the rear axle',
                'It does not move',
                'Forward, toward the front axle line — to the edge of the stability triangle',
                'Straight up out of the triangle',
              ],
              correctIndex: 2,
              explanation: 'An unloaded truck\'s CG sits between the axles. Picking up a rated load shifts the combined CG forward toward the front axle line — at rated capacity it sits near the front edge of the stability triangle, which is why overloading or a long load center pushes it past the edge and tips the truck.',
            },
          ],
        },
        {
          id: '1d-m2-s3',
          title: 'Hydraulics & Controls',
          durationHours: 1.5,
          learningObjectives: [
            'Describe the hydraulic system that powers the lift and tilt functions of a forklift',
            'Explain the function of the lift, tilt, and (where equipped) reach and side-shift controls',
            'Explain safe use of mast tilt when picking up, carrying, and placing loads',
            'Identify hydraulic warning signs that require taking a truck out of service',
          ],
          topics: [
            'Hydraulic system: pump, reservoir, control valves, lift cylinder(s), and tilt cylinders',
            'Lift control: raises and lowers the carriage; lower smoothly, never let a load free-fall',
            'Tilt control: tilts the mast forward and back; back-tilt cradles the load, forward-tilt is used only to pick up or set down',
            'Auxiliary functions: side-shift, fork positioners, reach mechanism, attachment controls',
            'Travel with the load tilted back and the forks low — only as high as needed to clear the surface',
            'Forward-tilting an elevated load moves the load center out and can tip the truck — keep tilt minimal when elevated',
            'Control discipline: operate hydraulics smoothly; never use lift or tilt with anyone near the load',
            'Hydraulic leaks, slow or jerky lift, mast drift, and unusual noise are out-of-service conditions',
            'Park procedure: forks flat on the ground, controls neutral, brake set, key off',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1910.178 — Powered Industrial Trucks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.178',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA Powered Industrial Trucks eTool — Operating the Forklift',
              url: 'https://www.osha.gov/etools/powered-industrial-trucks/operating-forklift',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'You have just picked up a palletized load. Before traveling, how should the mast be positioned?',
              options: [
                'Tilted fully forward to keep the load visible',
                'Tilted back to cradle the load, with the forks raised only as high as needed to clear the surface',
                'Tilted back and raised as high as the mast will go',
                'Vertical with the load resting on the ground',
              ],
              correctIndex: 1,
              explanation: 'Travel with the mast tilted back to cradle the load and the forks low — only high enough to clear the ground. A low, back-tilted load keeps the center of gravity low and inside the stability triangle. Exam tip: high loads and forward tilt while traveling are classic tipover causes.',
            },
            {
              question: 'Why is it dangerous to tilt the mast forward when a load is raised high?',
              options: [
                'It drains the hydraulic reservoir',
                'It moves the load center forward and raises the tipping moment, which can tip the truck forward',
                'It locks the steering',
                'It has no real effect as long as the load is under rated capacity',
              ],
              correctIndex: 1,
              explanation: 'Forward-tilting an elevated load pushes the load center out away from the front wheels, increasing the load moment. Combined with the higher center of gravity, this can tip the truck forward. Forward tilt at height should be minimal and done only to place a load.',
            },
            {
              question: 'During a pre-shift check the mast slowly drifts down on its own when raised and the controls are in neutral. What does this indicate?',
              options: [
                'Normal behavior for any forklift',
                'A hydraulic problem (e.g., cylinder or valve leakage) — the truck should be taken out of service',
                'The battery needs charging',
                'The forks are too long',
              ],
              correctIndex: 1,
              explanation: 'Mast drift means the hydraulic system is not holding pressure — a leaking cylinder seal or control valve. A load could settle or drop unexpectedly. This is an out-of-service condition until repaired.',
            },
            {
              question: 'What is the correct way to lower a load with the lift control?',
              options: [
                'Release the control fully so the load free-falls quickly',
                'Lower it smoothly and under control',
                'Bounce the control to ease the load down',
                'Lower it only while the truck is moving',
              ],
              correctIndex: 1,
              explanation: 'Loads should be lowered smoothly and under control. Letting a load free-fall or bouncing the control shock-loads the mast and chains and can cause the load to shift or fall.',
            },
            {
              question: 'A forklift has a visible hydraulic fluid leak dripping from a hose fitting. What is the correct action?',
              options: [
                'Top off the reservoir and keep working',
                'Wrap the fitting with tape and continue the shift',
                'Take the truck out of service and report the defect for repair',
                'Use the truck only for unloaded travel',
              ],
              correctIndex: 2,
              explanation: 'OSHA requires that a truck found defective or unsafe be taken out of service until repaired. A hydraulic leak can lead to loss of lift or tilt control and is a fire hazard near hot components — report it and tag it out.',
            },
            {
              question: 'When parking a forklift at the end of a task, the operator should:',
              options: [
                'Leave the forks raised so they are ready for the next load',
                'Lower the forks flat to the ground, put controls in neutral, set the brake, and turn the key off',
                'Leave it running with the brake off so it warms up',
                'Tilt the mast fully forward',
              ],
              correctIndex: 1,
              explanation: 'Proper park procedure is forks fully lowered flat on the ground, controls neutralized, parking brake set, and the engine/key off. Lowering the forks removes the risk of someone walking into raised tines and prevents hydraulic drift.',
            },
          ],
        },
      ],
    },
    {
      id: '1d-m3',
      title: 'Safe Operation',
      orderInCourse: 3,
      estimatedHours: 5,
      sessions: [
        {
          id: '1d-m3-s1',
          title: 'Daily Inspections',
          durationHours: 2,
          learningObjectives: [
            'State the OSHA requirement to examine a forklift before it is placed in service each shift',
            'Perform a key-off visual pre-start inspection of a forklift',
            'Perform an operational check of the truck with the engine running or power on',
            'Explain what to do when an inspection reveals a defect',
          ],
          topics: [
            'OSHA 1910.178: industrial trucks must be examined before being placed in service; trucks used around the clock are examined after each shift',
            'Key-off visual check: tires/wheels, forks (heel cracks, wear, bend), mast and chains, hoses and fittings, leaks under the truck, data plate legible, overhead guard and load backrest in place',
            'Fluid checks: hydraulic, engine oil, coolant, fuel/LP connection or battery condition and water level',
            'Operational (key-on) check: lift and tilt functions, service brake and parking brake, steering, horn, lights, backup alarm, gauges and warning lights',
            'Seat belt / operator restraint condition and function',
            'A defect found in inspection must be reported immediately',
            'A truck that is defective or in any way unsafe must be taken out of service until restored to safe operating condition',
            'Inspection records and tag-out of an out-of-service truck',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1910.178 — Powered Industrial Trucks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.178',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA Powered Industrial Trucks eTool — Pre-Operation Inspection',
              url: 'https://www.osha.gov/etools/powered-industrial-trucks/operating-forklift/pre-operation',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA Sample Daily Checklists for Powered Industrial Trucks',
              url: 'https://www.osha.gov/training/library/powered-industrial-trucks/checklist',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'How often does OSHA require a forklift to be examined?',
              options: [
                'Once a week',
                'Once a month',
                'Before it is placed in service each day (and after each shift if used around the clock)',
                'Only when a problem is suspected',
              ],
              correctIndex: 2,
              explanation: 'OSHA 1910.178 requires that industrial trucks be examined before being placed in service, and trucks used on a round-the-clock basis be examined after each shift. Exam tip: the pre-shift inspection is a legal requirement, not optional.',
            },
            {
              question: 'Which of the following is checked during the KEY-OFF (visual) portion of a forklift inspection?',
              options: [
                'Service brake feel',
                'Horn and backup alarm function',
                'Forks for heel cracks and wear, hoses for leaks, and that the data plate is legible',
                'Steering response',
              ],
              correctIndex: 2,
              explanation: 'The key-off visual check covers the things you inspect without power: forks, mast and chains, tires, hoses and fittings, leaks under the truck, fluid levels, and the condition of the data plate and guards. Brakes, horn, and steering are checked in the operational (key-on) portion.',
            },
            {
              question: 'During your inspection you find the service brake goes nearly to the floor before engaging. What must you do?',
              options: [
                'Use the parking brake instead and keep working',
                'Drive slowly and pump the brake as needed',
                'Take the truck out of service and report the defect — do not operate it until repaired',
                'Finish the current task, then report it',
              ],
              correctIndex: 2,
              explanation: 'A truck found defective or in any way unsafe must be taken out of service until restored to safe operating condition. Compromised brakes are an immediate out-of-service condition — there is no "finish this load first."',
            },
            {
              question: 'When a defect is found during a pre-shift inspection, OSHA requires that it be:',
              options: [
                'Logged at the end of the month',
                'Reported immediately',
                'Ignored if the truck still runs',
                'Fixed by the operator on the spot regardless of training',
              ],
              correctIndex: 1,
              explanation: 'OSHA requires defects to be reported immediately and corrected. The operator does not have to be the one who repairs it, but the defect must be reported and the truck kept out of service until it is fixed.',
            },
            {
              question: 'Why should the operator check the seat belt / operator restraint during the daily inspection?',
              options: [
                'It is only required on outdoor trucks',
                'The restraint is the operator\'s primary protection in a tipover — it keeps them in the protected zone of the cab',
                'It only matters if the truck has doors',
                'Seat belts are optional on forklifts',
              ],
              correctIndex: 1,
              explanation: 'In a tipover, the most dangerous thing an operator can do is jump — they can be crushed by the overhead guard. The operator restraint keeps them in the seat within the protected zone, so it must be present and functional.',
            },
            {
              question: 'A forklift used non-stop across three shifts should be examined:',
              options: [
                'Once at the start of the first shift only',
                'After each shift',
                'Once a week',
                'Only when the operator changes',
              ],
              correctIndex: 1,
              explanation: 'OSHA requires trucks used on a round-the-clock basis to be examined after each shift, so problems that develop during one shift are caught before the next operator takes over.',
            },
          ],
        },
        {
          id: '1d-m3-s2',
          title: 'Safe Operating Practices',
          durationHours: 1.5,
          learningObjectives: [
            'Apply safe traveling practices for loaded and unloaded lift trucks, including on grades',
            'Apply pedestrian-safety rules around lift trucks in shared work areas',
            'Explain safe load handling — stacking, picking, and placing',
            'Describe the hazards of refueling, charging, and operating different fuel types',
          ],
          topics: [
            'Travel with the load trailing (in reverse) when the load blocks the forward view',
            'On grades over 10 percent, drive a loaded truck with the load pointed upgrade — going up or down',
            'Keep forks low and mast tilted back while traveling; raise the load only to stack or pick',
            'Slow down and sound the horn at intersections, blind corners, and doorways',
            'Pedestrian rules: never drive up to anyone standing in front of a fixed object; no one walks or stands under elevated forks or load; no unauthorized riders',
            'Keep arms, legs, and head inside the running lines of the truck; never reach through the mast',
            'Maintain a safe following distance — about three truck lengths — and travel at a speed that allows a safe stop',
            'Load handling: center the load on the forks, get the forks fully under the load, stack squarely, do not stack beyond rated capacity',
            'Fuel-type hazards: LP refueling away from buildings and ignition sources with no engine running; battery charging in ventilated areas, acid into water, no smoking or sparks; diesel/gasoline — no open flame to check fuel, fix leaks before operating',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1910.178 — Powered Industrial Trucks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.178',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA Powered Industrial Trucks eTool — Operating the Forklift',
              url: 'https://www.osha.gov/etools/powered-industrial-trucks/operating-forklift',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA Powered Industrial Trucks — Forklifts Overview',
              url: 'https://www.osha.gov/powered-industrial-trucks',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'You must drive a loaded forklift down a grade steeper than 10 percent. Which way should the load face?',
              options: [
                'Downgrade (load pointing down the slope)',
                'Upgrade (load pointing up the slope)',
                'It does not matter on a forklift',
                'Sideways across the slope',
              ],
              correctIndex: 1,
              explanation: 'On grades over 10 percent, a loaded truck must be driven with the load upgrade — whether going up or down. This keeps the load from running away downhill and keeps the truck stable. Exam tip: load upgrade, always, on steep grades.',
            },
            {
              question: 'A load on your forks is tall enough to block your view straight ahead. What should you do?',
              options: [
                'Lift the load higher so you can see under it',
                'Travel with the load trailing (drive in reverse), looking in the direction of travel',
                'Have a coworker sit on the load to watch ahead',
                'Drive faster to spend less time with the blocked view',
              ],
              correctIndex: 1,
              explanation: 'When the load obstructs the forward view, OSHA requires the operator to travel with the load trailing — driving in reverse and looking in the direction of travel. Raising the load higher only makes the truck less stable.',
            },
            {
              question: 'A coworker is standing between your forklift and a fixed workbench. What does OSHA require?',
              options: [
                'Drive up slowly until they notice you',
                'Sound the horn once and continue',
                'Do not drive up to anyone standing in front of a bench or other fixed object',
                'It is allowed as long as the forks are lowered',
              ],
              correctIndex: 2,
              explanation: 'OSHA prohibits driving a truck up to anyone standing in front of a fixed object — the person could be pinned. Wait for them to move clear before approaching that area.',
            },
            {
              question: 'A coworker asks for a ride on the forks of your forklift to reach an upper shelf. What is the correct response?',
              options: [
                'Allow it if they hold on tightly',
                'Allow it if you go slowly',
                'Refuse — riding on the forks or on the truck by unauthorized personnel is prohibited, and no one may be under or on elevated forks',
                'Allow it only if a supervisor approves',
              ],
              correctIndex: 2,
              explanation: 'Unauthorized personnel may not ride on a powered industrial truck, and no one may stand or pass under elevated forks. Lifting a person requires a properly secured work platform and the correct procedures — never bare forks.',
            },
            {
              question: 'Which is the correct procedure for charging a forklift battery?',
              options: [
                'Charge anywhere convenient and smoke breaks are fine nearby',
                'Charge in a designated, well-ventilated area; keep flames, sparks, and smoking away; when adding electrolyte, pour acid into water',
                'Pour water into acid to dilute it faster',
                'Charge the battery while the truck is being driven',
              ],
              correctIndex: 1,
              explanation: 'Charging batteries release hydrogen gas, which is explosive. OSHA requires a designated, ventilated charging area free of flames, sparks, and smoking. When mixing electrolyte, always pour acid into water — never water into acid, which can cause a violent reaction.',
            },
            {
              question: 'What is the safe practice when refueling an LP (propane) forklift?',
              options: [
                'Leave the engine running so the tank fills faster',
                'Refuel inside a closed room to keep the cylinder warm',
                'Shut the engine off, refuel away from buildings and ignition sources, and wear appropriate gloves and eye protection',
                'Use an open flame to check the connection for leaks',
              ],
              correctIndex: 2,
              explanation: 'LP refueling is done with the engine off, away from buildings and ignition sources, and only by trained personnel using proper PPE — liquid propane can cause instant freeze burns. Never use a flame to check for leaks; LP vapor is heavier than air and can collect and ignite.',
            },
          ],
        },
        {
          id: '1d-m3-s3',
          title: 'OSHA 1910.178',
          durationHours: 1.5,
          learningObjectives: [
            'Explain the scope of OSHA 29 CFR 1910.178 and what equipment it covers',
            'State the OSHA operator training and evaluation requirements for powered industrial trucks',
            'Describe what triggers OSHA refresher training and re-evaluation',
            'Explain how OSHA 1910.178 and the Massachusetts hoisting license work together',
          ],
          topics: [
            'OSHA 29 CFR 1910.178: the federal standard for powered industrial trucks — fork trucks, tractors, platform lift trucks, and similar',
            'It excludes compressed-air trucks, farm vehicles, and earth-moving equipment',
            'Operator training combines formal instruction, practical training/demonstration, and a workplace performance evaluation',
            'Training content: truck-specific topics (controls, capacity, stability, inspection) and workplace topics (surfaces, pedestrian traffic, ramps, hazardous locations)',
            'Operators must be evaluated at least once every three years',
            'Refresher training and re-evaluation required after an accident or near-miss, observed unsafe operation, a poor evaluation, assignment to a different truck type, or a workplace change affecting safe operation',
            'Employer certification: must document the operator name, training date, evaluation date, and the identity of the trainer/evaluator',
            'OSHA 1910.178 is the employer-based federal training standard; the Massachusetts hoisting license is a separate state requirement under MGL c.146 — an operator generally needs both',
            'Outdoor/rough-terrain forklift work on construction sites also falls under OSHA construction rules (29 CFR 1926.602)',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1910.178 — Powered Industrial Trucks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.178',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA Powered Industrial Trucks eTool — Operator Training',
              url: 'https://www.osha.gov/etools/powered-industrial-trucks/training',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.602 — Material Handling Equipment (construction)',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'Which equipment is NOT covered by OSHA 29 CFR 1910.178?',
              options: [
                'Counterbalanced fork trucks',
                'Platform lift trucks',
                'Earth-moving equipment such as excavators',
                'Motorized hand trucks',
              ],
              correctIndex: 2,
              explanation: 'OSHA 1910.178 covers powered industrial trucks — fork trucks, tractors, platform lift trucks, motorized hand trucks, and similar. It specifically excludes compressed-air trucks, farm vehicles, and earth-moving equipment, which fall under other standards.',
            },
            {
              question: 'Under OSHA 1910.178, how often must a powered industrial truck operator\'s performance be evaluated?',
              options: [
                'Every shift',
                'Once, at initial hire only',
                'At least once every three years',
                'Every six months',
              ],
              correctIndex: 2,
              explanation: 'OSHA requires an evaluation of each operator\'s performance at least once every three years, in addition to refresher training whenever a triggering event occurs. Exam tip: remember "every 3 years" for the routine evaluation cycle.',
            },
            {
              question: 'Which of the following triggers OSHA-required refresher training and re-evaluation?',
              options: [
                'The operator takes a two-week vacation',
                'The operator is involved in a near-miss incident',
                'The truck gets a routine oil change',
                'The operator is promoted to a new pay grade',
              ],
              correctIndex: 1,
              explanation: 'Refresher training is required after an accident or near-miss, observed unsafe operation, a poor evaluation, assignment to a different type of truck, or a workplace change affecting safe operation. A near-miss is one of the explicit triggers.',
            },
            {
              question: 'What must an employer\'s forklift operator training certification include under OSHA 1910.178?',
              options: [
                'Only the operator\'s signature',
                'The operator\'s name, the training date, the evaluation date, and the identity of the trainer/evaluator',
                'A copy of the operator\'s driver\'s license only',
                'Just the make and model of the truck',
              ],
              correctIndex: 1,
              explanation: 'OSHA requires the employer to certify training with the operator\'s name, the date of training, the date of evaluation, and the identity of the person(s) who did the training or evaluation.',
            },
            {
              question: 'How do OSHA 1910.178 training and the Massachusetts 1D hoisting license relate?',
              options: [
                'They are the same thing — passing one satisfies the other',
                'OSHA 1910.178 is a federal employer-based training standard; the MA hoisting license is a separate state requirement, and an operator generally needs both',
                'The MA license replaces the need for any OSHA training',
                'OSHA 1910.178 only applies outside Massachusetts',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1910.178 is a federal standard requiring the employer to train and evaluate operators. The Massachusetts hoisting license is a separate state credential under MGL c.146. They are independent requirements — a forklift operator in Massachusetts generally must satisfy both.',
            },
            {
              question: 'An operator is trained and certified on a sit-down counterbalanced forklift and is then assigned to run a stand-up reach truck. What does OSHA require?',
              options: [
                'Nothing — a forklift is a forklift',
                'Refresher training and evaluation for the different type of truck',
                'A new Massachusetts license class only',
                'A waiver signed by a coworker',
              ],
              correctIndex: 1,
              explanation: 'Assignment to a different type of truck is an explicit OSHA trigger for refresher training and evaluation. A reach truck handles, steers, and balances differently from a counterbalanced forklift, so the operator must be trained and evaluated on it before operating it.',
            },
          ],
        },
      ],
    },
    {
      id: '1d-m4',
      title: 'Practice & Review',
      orderInCourse: 4,
      estimatedHours: 4,
      sessions: [
        {
          id: '1d-m4-s1',
          title: 'Practice Exam 1',
          durationHours: 2,
          learningObjectives: [
            'Apply legal and regulatory knowledge to exam-style questions',
            'Apply load capacity, load center, and stability concepts to scenario questions',
            'Apply daily inspection and safe operating rules to exam-style questions',
            'Identify weak topic areas to target before the licensing exam',
          ],
          topics: [
            'Mixed-topic practice covering MGL Chapter 146, 230 CMR 6.00, and the company-property exemption',
            'Capacity-plate reading, rated capacity vs. load center, and stability-triangle scenarios',
            'Attachment derating and combined center-of-gravity questions',
            'Daily inspection: key-off vs. key-on checks and out-of-service conditions',
            'Safe operating practices: grades, blocked-view travel, pedestrian rules, following distance',
            'Fuel-type hazards: LP refueling, battery charging, diesel/gasoline handling',
            'OSHA 1910.178 training, the three-year evaluation cycle, and refresher triggers',
            'Reviewing wrong answers and explanations to close knowledge gaps',
          ],
          resources: [
            {
              label: 'MGL Chapter 146 § 53 — Necessity of licenses; classification; exemptions',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146/Section53',
              type: 'regulation',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1910.178 — Powered Industrial Trucks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.178',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'A forklift is rated "4,000 lb at 24 in load center." You need to move a uniform 4,000 lb load whose center of gravity sits 30 inches from the fork face. What is the correct conclusion?',
              options: [
                'The lift is safe — the weight matches the rating exactly',
                'The lift exceeds safe capacity because the load center is farther out than the rated 24 inches, increasing the load moment',
                'The lift is safe if you tilt the mast forward',
                'Load center has no bearing on whether the lift is safe',
              ],
              correctIndex: 1,
              explanation: 'Rated capacity only holds at the rated load center. At 30 inches, the load moment is larger than the truck is rated for, so the safe capacity is below 4,000 lb. The lift is not safe as planned.',
            },
            {
              question: 'A company runs forklifts only inside its own plant and the public has no access to those areas. Which statement about the Massachusetts hoisting license is most accurate?',
              options: [
                'The company can never qualify for any exemption',
                'The company may qualify for the §53 industrial-lift-truck exemption if it meets the statutory conditions, including a licensed supervisory employee on site and an approved in-service training program',
                'Every operator is automatically exempt with no conditions',
                'The exemption applies even on public roadways',
              ],
              correctIndex: 1,
              explanation: 'MGL §53 allows a narrow exemption for industrial lift trucks used exclusively on company property not open to the public, but the company must meet the statutory conditions — notably a licensed supervisory employee on site during operations and an approved in-service training program. It is not automatic and does not extend off company property.',
            },
            {
              question: 'During a pre-shift inspection you find a hydraulic leak, the horn does not sound, and the data plate is unreadable. How many of these are out-of-service conditions?',
              options: [
                'None — these are minor',
                'Only the hydraulic leak',
                'All three — each one makes the truck unsafe to place in service',
                'Only the unreadable data plate',
              ],
              correctIndex: 2,
              explanation: 'A hydraulic leak, an inoperative horn, and an illegible data plate are each conditions that make the truck unsafe or non-compliant. OSHA requires a truck that is defective or in any way unsafe to be taken out of service until restored.',
            },
            {
              question: 'You are driving a loaded forklift and the load blocks your forward view. The path ahead also has a downhill grade of about 12 percent. What two rules apply?',
              options: [
                'Lift the load high to see under it, and drive load-downgrade',
                'Travel with the load trailing (in reverse), and keep the load pointed upgrade on the steep grade',
                'Drive faster to clear the area quickly, and ignore the grade',
                'Have a rider direct you, and tilt the mast forward',
              ],
              correctIndex: 1,
              explanation: 'A blocked forward view means traveling with the load trailing. A grade steeper than 10 percent means a loaded truck must keep the load upgrade. Both rules apply at once — plan the travel direction so you satisfy both.',
            },
            {
              question: 'An operator certified on a counterbalanced forklift is reassigned to operate a telehandler on an outdoor job site. What is required?',
              options: [
                'Nothing additional — the existing certification covers it',
                'OSHA refresher training and evaluation for the different truck type, plus the appropriate Massachusetts hoisting license coverage for that equipment',
                'Only a verbal briefing',
                'Only a new pair of work gloves',
              ],
              correctIndex: 1,
              explanation: 'A telehandler handles very differently from a warehouse forklift, so assignment to it triggers OSHA refresher training and evaluation. The operator also needs Massachusetts hoisting license coverage appropriate to that equipment — telehandler/rough-terrain forklift work is not the company-property warehouse scenario.',
            },
            {
              question: 'Which set of actions is correct for charging an electric forklift battery?',
              options: [
                'Charge in any closed room, smoking allowed, pour water into acid',
                'Charge in a designated ventilated area, keep flames and sparks away, pour acid into water when adding electrolyte',
                'Charge while driving the truck, no ventilation needed',
                'Charge near a space heater to keep the battery warm',
              ],
              correctIndex: 1,
              explanation: 'Charging releases explosive hydrogen gas, so OSHA requires a designated, ventilated area free of flames, sparks, and smoking. When adding electrolyte, always pour acid into water — never the reverse.',
            },
            {
              question: 'After failing the 1D exam, how soon can you retest, and what score do you need to pass?',
              options: [
                'Retest after 7 days; pass with 60%',
                'Retest after 30 days; pass with 65%',
                'Retest after 60 days; pass with 70%',
                'Retest immediately; pass with 75%',
              ],
              correctIndex: 2,
              explanation: 'A failed attempt means a 60-day wait before retesting, and the passing score is 70%. The wait exists so you can study and re-test prepared rather than rushing back.',
            },
          ],
        },
        {
          id: '1d-m4-s2',
          title: 'Final Review',
          durationHours: 2,
          learningObjectives: [
            'Recall the highest-yield legal and regulatory facts for the 1D exam',
            'Summarize the core technical concepts: capacity plate, load center, stability triangle, mast handling',
            'Summarize the core safety rules: inspection, traveling, pedestrian protection, fuel hazards',
            'Build a focused last-week study plan from identified weak areas',
          ],
          topics: [
            'Legal recap: 18-year minimum age, 70% passing score, 60-day retest wait, $75 fee per class, 2-year license, MGL c.146 and 230 CMR 6.00, the company-property lift-truck exemption and its conditions',
            'Signaling recap: only an approved signaler directs the operator; SAE J1307 hand signals; stop if you lose sight of the signaler',
            'Technical recap: read the data plate; rated capacity is valid only at the rated load center; load moment = weight x load center; the stability triangle is the two front wheels plus the rear-axle pivot',
            'Stability recap: the combined center of gravity must stay inside the triangle; raising or forward-tilting a load reduces stability; attachments derate capacity',
            'Operation recap: travel forks low and mast back; load trailing when the view is blocked; load upgrade on grades over 10 percent; horn and slow at blind spots; no riders, no one under elevated forks',
            'Inspection recap: examine the truck before each shift; key-off visual then key-on operational checks; any defect means out of service until repaired',
            'Fuel recap: LP refuel engine-off away from ignition sources; charge batteries in ventilated areas, acid into water; fix fuel leaks before operating',
            'OSHA 1910.178 recap: employer training plus evaluation at least every 3 years; refresher after accidents, unsafe operation, new truck type, or workplace change',
            'Test-taking strategy: read scenario questions fully, watch for "both rules apply" cases, eliminate clearly wrong options',
          ],
          resources: [
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1910.178 — Powered Industrial Trucks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.178',
              type: 'osha',
              required: true,
            },
            {
              label: 'SAE J1307 Hand Signals — Quick Reference Guide',
              url: '/hand-signals',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'Which list correctly states the core MA licensing facts for the 1D class?',
              options: [
                'Age 16, pass 60%, retest in 7 days, license valid 5 years',
                'Age 18, pass 70%, retest after 60 days, license valid 2 years, $75 per restriction class',
                'Age 21, pass 80%, retest after 90 days, license valid 1 year',
                'Age 18, pass 65%, no retest wait, license valid 3 years',
              ],
              correctIndex: 1,
              explanation: 'The core facts: minimum age 18, passing score 70%, 60-day wait after a failed attempt, license valid 2 years, $75 non-refundable fee per restriction class. These are the most commonly tested numbers — memorize them.',
            },
            {
              question: 'A truck rated "5,000 lb at 24 in" is fitted with an attachment that weighs 800 lb and shifts the load center forward. What is the effect on safe capacity?',
              options: [
                'Safe capacity stays exactly 5,000 lb',
                'Safe capacity increases because the truck is now heavier',
                'Safe capacity is reduced — the attachment adds weight and moves the load center out, and the data plate must be updated',
                'There is no effect until the load exceeds 5,000 lb',
              ],
              correctIndex: 2,
              explanation: 'An attachment both adds weight and usually moves the load center forward, increasing the load moment for any given load. Safe capacity drops, and OSHA requires the capacity plate to reflect the truck-and-attachment combination.',
            },
            {
              question: 'In a tipover, what should a seated forklift operator wearing the restraint do?',
              options: [
                'Jump clear of the truck immediately',
                'Stay in the seat, hold on, brace, and lean away from the direction of the fall — staying within the protected zone',
                'Stand up and climb out the side',
                'Reach out to push off the ground',
              ],
              correctIndex: 1,
              explanation: 'Jumping is the most dangerous response — the operator can be crushed by the overhead guard. The correct action is to stay belted in the seat, hold on, brace the feet, and lean away from the fall, staying inside the protected operator zone.',
            },
            {
              question: 'You lose sight of your signaler behind a stack of pallets mid-task. What do you do?',
              options: [
                'Keep moving slowly until the signaler reappears',
                'Stop all movement until visual contact with the signaler is restored',
                'Have any nearby worker take over signaling',
                'Finish the current motion, then stop',
              ],
              correctIndex: 1,
              explanation: 'If you cannot see the approved signaler, you must stop. A signaler out of sight cannot safely direct the machine, and 230 CMR 6.00 permits no relay or substitute signaler.',
            },
            {
              question: 'Which statement about the company-property lift-truck exemption is correct?',
              options: [
                'It lets any forklift operator skip the license anywhere in Massachusetts',
                'It applies to lift trucks used exclusively on company property where the public has no access, and only when the company meets the §53 conditions such as a licensed supervisory employee on site',
                'It applies to telehandler work on public construction sites',
                'It eliminates the need for OSHA training',
              ],
              correctIndex: 1,
              explanation: 'The exemption is narrow: lift trucks used exclusively on the company\'s own property not open to the public, and only when the company meets the statutory conditions. It does not reach public job sites, and it does not remove the separate OSHA 1910.178 training requirement.',
            },
            {
              question: 'A forklift will be used non-stop across three shifts. What is the correct inspection practice?',
              options: [
                'Inspect once at the start of the day only',
                'Inspect after each shift so each operator gets a truck that has been checked',
                'Inspect once a week',
                'Inspect only when a defect is reported',
              ],
              correctIndex: 1,
              explanation: 'OSHA requires trucks used on a round-the-clock basis to be examined after each shift. That way any problem developing on one shift is caught before the next operator takes the truck.',
            },
            {
              question: 'Under OSHA 1910.178, beyond initial training, how often must each operator be evaluated, and name one event that triggers refresher training.',
              options: [
                'Every 10 years; trigger is a pay raise',
                'At least every 3 years; a trigger is an accident or near-miss, unsafe operation, assignment to a different truck type, or a workplace change',
                'Never again after initial training',
                'Every shift; trigger is changing gloves',
              ],
              correctIndex: 1,
              explanation: 'OSHA requires an evaluation at least once every three years, plus refresher training whenever a triggering event occurs — an accident or near-miss, observed unsafe operation, a poor evaluation, assignment to a different truck type, or a workplace change affecting safe operation.',
            },
          ],
        },
      ],
    },
  ],
};
