import { LicenseRestriction } from '../types';

export const restriction_1e: LicenseRestriction = {
  code: '1E',
  name: 'Specialty Cranes',
  description: 'Specialty hoisting equipment per OPSI scope.',
  equipmentCovered: ['Specialty equipment'],
  totalHours: 20,
  modules: [
    {
      id: '1e-m1',
      title: 'Foundation',
      orderInCourse: 1,
      estimatedHours: 5,
      sessions: [
        {
          id: '1e-m1-s1',
          title: 'Regulations',
          durationHours: 2,
          learningObjectives: [
            'State the minimum age and exam passing score for a Massachusetts hoisting license',
            'Identify when a hoisting license is required to operate a specialty crane',
            'Explain the relationship between MGL Chapter 146 and 230 CMR 6.00',
            'List the key exemptions from the hoisting license requirement',
          ],
          topics: [
            'MGL Chapter 146 §§ 53–54A — who must hold a hoisting license',
            'Minimum age requirement: 18 years old',
            'Exam passing score: 70% minimum',
            '60-day waiting period after a failed attempt',
            '$75 non-refundable application fee per restriction class',
            'License duration: 2-year cycle',
            '230 CMR 6.00 — the regulation implementing MGL Chapter 146 for hoisting machinery',
            'Exemptions: agricultural operators, public utility supervised programs, certain industrial lift trucks on company property, approved apprenticeship and vocational programs',
            'Application through the MA Division of Occupational Licensure, Office of Public Safety and Inspections (OPSI)',
          ],
          resources: [
            {
              label: 'MGL Chapter 146 § 53 — Licensing requirement',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146/Section53',
              type: 'regulation',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: true,
            },
            {
              label: 'Apply for a Hoisting Engineer License',
              url: 'https://www.mass.gov/how-to/apply-for-a-hoisting-engineer-license',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'What is the minimum passing score on the Massachusetts hoisting engineer exam?',
              options: ['60%', '65%', '70%', '75%'],
              correctIndex: 2,
              explanation: 'The passing score is 70%. If you score below 70% you must wait 60 days before retesting, so plan your study time to pass on the first attempt.',
            },
            {
              question: 'What is the minimum age to obtain a Massachusetts hoisting license?',
              options: ['16', '17', '18', '21'],
              correctIndex: 2,
              explanation: 'MGL Chapter 146 sets the minimum age at 18. Applicants under 18 cannot obtain a hoisting license regardless of experience or training.',
            },
            {
              question: 'Which statement best describes the relationship between MGL Chapter 146 and 230 CMR 6.00?',
              options: [
                'MGL Chapter 146 is federal law; 230 CMR 6.00 is state law',
                'MGL Chapter 146 is the statute passed by the legislature; 230 CMR 6.00 is the implementing regulation',
                'They are two names for the same document',
                '230 CMR 6.00 replaced MGL Chapter 146',
              ],
              correctIndex: 1,
              explanation: 'MGL (Massachusetts General Law) is statute passed by the legislature. 230 CMR 6.00 is the regulation that implements the statute with specific technical and safety requirements for hoisting machinery.',
            },
            {
              question: 'How long must you wait to retake the hoisting exam after a failed attempt?',
              options: ['7 days', '30 days', '60 days', '90 days'],
              correctIndex: 2,
              explanation: 'You must wait 60 days after a failed attempt. Use that time to study the areas where you scored poorly rather than rushing back unprepared.',
            },
            {
              question: 'How long is a Massachusetts hoisting license valid before renewal is required?',
              options: ['1 year', '2 years', '3 years', '5 years'],
              correctIndex: 1,
              explanation: 'The license is valid for 2 years. Always confirm the current renewal cycle and requirements at mass.gov, as they can change.',
            },
            {
              question: 'Which operator is EXEMPT from the Massachusetts hoisting license requirement?',
              options: [
                'A contractor operating a loader crane on a public road project',
                'A farmhand operating hoisting equipment exclusively on agricultural land',
                'A delivery driver using a truck-mounted loader crane to unload building materials at a job site',
                'A rigger operating a knuckle-boom crane on a commercial construction site',
              ],
              correctIndex: 1,
              explanation: 'Agricultural operators working exclusively on agricultural land are explicitly exempt under MGL §53. Construction, utility, and commercial delivery work requires a license regardless of who owns the property.',
            },
            {
              question: 'What is the non-refundable application fee for each restriction class?',
              options: ['$25', '$50', '$75', '$100'],
              correctIndex: 2,
              explanation: 'The application fee is $75 per restriction class and is non-refundable, even if you fail the exam or your application is denied.',
            },
          ],
        },
        {
          id: '1e-m1-s2',
          title: 'Scope & Equipment',
          durationHours: 1.5,
          learningObjectives: [
            'Describe the equipment a 1E specialty crane restriction is intended to authorize',
            'Distinguish a 1E specialty crane from equipment covered by other Class 1 restrictions',
            'Explain why operating outside your licensed restriction is a violation',
            'Identify where to verify the exact scope of a restriction class',
          ],
          topics: [
            'Class 1 restriction structure: 1A friction/lattice cranes, 1B telescoping-boom cranes, 1C hydraulic telescoping booms and loaders/backhoes, 1D industrial lift trucks',
            '1E specialty cranes: articulating (knuckle-boom) loader cranes and truck-mounted loader cranes used for material handling and delivery',
            'How an articulating crane differs from a telescoping-boom crane: multiple hinged boom sections instead of a single extending boom',
            'Each restriction authorizes only the equipment listed for that class',
            'Operating equipment outside your restriction is the same as operating with no license',
            'License hierarchy: higher Class 1 restrictions may cover lower ones — confirm the current OPSI hierarchy rules',
            'Specialty equipment is subject to 230 CMR 6.00 even when truck-mounted',
            'Verifying restriction scope with OPSI before testing or accepting work',
          ],
          resources: [
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: true,
            },
            {
              label: 'Apply for a Hoisting Engineer License',
              url: 'https://www.mass.gov/how-to/apply-for-a-hoisting-engineer-license',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'What is the defining structural feature of an articulating (knuckle-boom) crane?',
              options: [
                'A single boom that extends and retracts hydraulically',
                'Multiple hinged boom sections that fold at "knuckle" joints',
                'A lattice boom assembled from bolted sections',
                'A fixed boom with a wire rope hoist line only',
              ],
              correctIndex: 1,
              explanation: 'An articulating crane uses multiple boom sections connected by hinged joints (knuckles) that fold against one another. This lets it reach over obstacles and fold compactly for transport, unlike a telescoping boom that extends in a straight line.',
            },
            {
              question: 'You hold only a 1E specialty crane restriction. A supervisor asks you to operate a crawler crane with a friction winch drum. What should you do?',
              options: [
                'Operate it — a hoisting license is a hoisting license',
                'Operate it only if a licensed 1A operator supervises you',
                'Decline; that equipment requires a 1A restriction you do not hold',
                'Operate it for less than one shift without penalty',
              ],
              correctIndex: 2,
              explanation: 'Each restriction authorizes only the equipment listed for that class. Operating a crane outside your restriction is treated the same as operating with no license at all and exposes you and your employer to penalties.',
            },
            {
              question: 'Where should you confirm exactly what equipment your 1E restriction authorizes?',
              options: [
                'A crane manufacturer brochure',
                'The MA Office of Public Safety and Inspections (OPSI) / mass.gov hoisting pages',
                'A coworker who has held the license longer',
                'The truck registration documents',
              ],
              correctIndex: 1,
              explanation: 'The authoritative source for restriction scope is OPSI through the mass.gov hoisting pages. Restriction definitions and the license hierarchy can change, so verify before testing or accepting work.',
            },
            {
              question: 'How does an articulating loader crane differ from a 1C hydraulic telescoping-boom crane?',
              options: [
                'The articulating crane has no hydraulic system',
                'The articulating crane folds at hinged joints rather than extending a single straight boom',
                'The articulating crane cannot be truck-mounted',
                'There is no functional difference; the names are interchangeable',
              ],
              correctIndex: 1,
              explanation: 'A telescoping boom extends in a straight line; an articulating boom folds at hinged knuckle joints. The motions, blind spots, and stability behavior differ enough that they are treated as distinct equipment for licensing.',
            },
            {
              question: 'A truck-mounted loader crane is being used on a public construction site. Is it subject to 230 CMR 6.00?',
              options: [
                'No, because it is mounted on a registered truck',
                'No, because loader cranes are exempt material-handling equipment',
                'Yes, truck-mounted specialty hoisting machinery is subject to 230 CMR 6.00',
                'Only if the lifted load exceeds 10 tons',
              ],
              correctIndex: 2,
              explanation: 'Being mounted on a truck does not exempt hoisting machinery. A truck-mounted loader crane used for hoisting is subject to 230 CMR 6.00 and requires an appropriately licensed operator.',
            },
            {
              question: 'Why does Massachusetts divide hoisting licenses into specific restriction classes rather than issuing one universal license?',
              options: [
                'To generate more application fee revenue',
                'Because different equipment types require distinct knowledge, controls, and hazard awareness',
                'Because federal law requires exactly five classes',
                'To limit the number of licensed operators in the state',
              ],
              correctIndex: 1,
              explanation: 'Restriction classes exist because each equipment type has its own controls, stability characteristics, and hazards. An operator proven competent on one class is not automatically competent on another, so the license reflects demonstrated, equipment-specific knowledge.',
            },
          ],
        },
        {
          id: '1e-m1-s3',
          title: 'Renewal',
          durationHours: 1.5,
          learningObjectives: [
            'State the renewal cycle and explain the consequence of letting a license lapse',
            'Describe the civil penalties for operating without a valid license',
            'Explain employer and operator responsibilities under MGL Chapter 146',
            'Summarize the reinstatement process after a license expires',
          ],
          topics: [
            'Renewal cycle: every 2 years, before expiration',
            'No official grace period — an expired license is an invalid license',
            'Civil penalty: up to $500 per day for unlicensed operation',
            'Each day of unlicensed operation is treated as a separate violation',
            'Employer liability for knowingly using unlicensed operators (MGL §66)',
            'Accident reporting obligations under MGL §67',
            'Reinstatement after a lapse may require re-application and re-examination',
            'Keeping the physical license available during operation',
            'Verifying current renewal requirements at mass.gov, as procedures can change',
          ],
          resources: [
            {
              label: 'MGL Chapter 146 (full chapter)',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146',
              type: 'regulation',
              required: true,
            },
            {
              label: 'Apply for a Hoisting Engineer License',
              url: 'https://www.mass.gov/how-to/apply-for-a-hoisting-engineer-license',
              type: 'reference',
              required: true,
            },
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'Your 1E license expired two weeks ago. Can you legally operate a knuckle-boom crane today while your renewal is "in the mail"?',
              options: [
                'Yes, there is a 30-day grace period after expiration',
                'Yes, as long as you can show the renewal was submitted',
                'No, an expired license is invalid and operating violates MGL §53',
                'Yes, if your employer signs a liability waiver',
              ],
              correctIndex: 2,
              explanation: 'There is no grace period that permits continued operation. An expired license is an invalid license, and operating with it exposes both you and your employer to civil penalties of up to $500 per day.',
            },
            {
              question: 'What is the maximum civil penalty per day for operating hoisting equipment without a valid license?',
              options: ['$100/day', '$250/day', '$500/day', '$1,000/day'],
              correctIndex: 2,
              explanation: 'MGL Chapter 146 allows civil penalties of up to $500 per day for unlicensed operation, and each day is a separate violation, so the total can climb quickly.',
            },
            {
              question: 'Under MGL §66, who bears legal responsibility for ensuring an operator holds a valid license?',
              options: [
                'The operator alone',
                'Both the operator and the employer',
                'The general contractor only',
                'OPSI, which checks every job site',
              ],
              correctIndex: 1,
              explanation: 'Responsibility falls on both the operator, to maintain a valid license, and the employer, who must not knowingly direct an unlicensed operator. Both can be penalized.',
            },
            {
              question: 'How often must a Massachusetts hoisting license be renewed?',
              options: ['Annually', 'Every 2 years', 'Every 3 years', 'Every 5 years'],
              correctIndex: 1,
              explanation: 'The license must be renewed every 2 years, before it expires. Track your expiration date and renew early to avoid any lapse in eligibility to operate.',
            },
            {
              question: 'What may be required to reinstate a hoisting license that has lapsed for an extended period?',
              options: [
                'Nothing — it reactivates automatically once you reapply',
                'Re-application and potentially re-examination',
                'A one-time $25 late fee only',
                'A letter from your employer',
              ],
              correctIndex: 1,
              explanation: 'A lapsed license may require re-application and, depending on how long it has been expired, re-examination. This is far more costly and time-consuming than renewing on time.',
            },
            {
              question: 'A delivery company tells an unlicensed driver to run the truck-mounted loader crane "just for today." What is the legal exposure?',
              options: [
                'None, if no accident occurs',
                'A verbal warning to the driver only',
                'Both the driver and the company can face civil penalties under MGL §53',
                'Only the company is liable; drivers are protected from individual liability',
              ],
              correctIndex: 2,
              explanation: 'MGL §53 creates liability for both the person operating without a license and the employer who directs that operation. "Just for today" does not reduce the penalty — it is still a violation.',
            },
          ],
        },
      ],
    },
    {
      id: '1e-m2',
      title: 'Equipment',
      orderInCourse: 2,
      estimatedHours: 5,
      sessions: [
        {
          id: '1e-m2-s1',
          title: 'Systems',
          durationHours: 2,
          learningObjectives: [
            'Identify the major structural systems of an articulating loader crane',
            'Explain how the lift boom, articulating boom, and extensions work together',
            'Describe the slewing (rotation) system and its working range',
            'Explain the role of the truck chassis and subframe as the crane base',
          ],
          topics: [
            'Crane base: truck chassis, subframe, and mounting that ties the crane to the vehicle',
            'Column and slewing system: provides rotation, often through a limited slew arc rather than full continuous rotation',
            'Inner (lift) boom: the first powered boom section off the column',
            'Outer (articulating) boom: folds at the knuckle joint to position the load',
            'Hydraulic boom extensions: telescoping sections that increase reach',
            'Stabilizer (outrigger) legs and beams: extend to widen the support footprint',
            'Load-handling end: hook, winch, or attachment such as a grapple or pallet fork',
            'Control stations: ground-level dual controls and/or top-seat or radio remote operation',
            'Load chart and capacity decals located on the crane',
          ],
          resources: [
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'OSHA 1926 Subpart CC — Cranes & Derricks in Construction',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926SubpartCC',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'On an articulating loader crane, what is the function of the outer (articulating) boom?',
              options: [
                'It rotates the crane on its column',
                'It folds at the knuckle joint to position the load and reach over obstacles',
                'It extends and retracts the stabilizer beams',
                'It is the truck chassis the crane is mounted on',
              ],
              correctIndex: 1,
              explanation: 'The outer boom folds at the knuckle joint, letting the operator place a load over a wall or into a tight space. This articulation is the defining capability of a knuckle-boom crane.',
            },
            {
              question: 'Many articulating loader cranes have a slewing system that provides:',
              options: [
                'Unlimited continuous 360-degree rotation in all cases',
                'A limited slew arc, often less than full rotation, that the operator must respect',
                'No rotation at all — the whole truck must be repositioned',
                'Rotation only when the engine is off',
              ],
              correctIndex: 1,
              explanation: 'Many loader cranes slew through a limited arc rather than rotating continuously. The operator must know the machine\'s slew range and never force the boom past its limits, which can damage the column and hoses.',
            },
            {
              question: 'What is the purpose of the subframe on a truck-mounted loader crane?',
              options: [
                'It stores the load chart and operating manual',
                'It is a decorative cover for the hydraulic lines',
                'It ties the crane to the truck chassis and distributes lifting loads into the vehicle',
                'It is the operator seat assembly',
              ],
              correctIndex: 2,
              explanation: 'The subframe is the structural link between the crane and the truck chassis. It spreads the forces from lifting into the vehicle frame; a cracked or improperly mounted subframe is a serious defect.',
            },
            {
              question: 'Why do many articulating cranes offer both ground-level controls and a top-seat or remote control option?',
              options: [
                'To let two operators run the crane at once',
                'So the operator can choose the position with the best view of the load and stay clear of hazards',
                'Because regulations require three control stations',
                'The extra controls are only for maintenance technicians',
              ],
              correctIndex: 1,
              explanation: 'Multiple control positions let the operator work from wherever they have the clearest view of the load and landing zone while staying out of the danger zone. The operator must still control only one station at a time.',
            },
            {
              question: 'On a loader crane, the hydraulic boom extensions primarily serve to:',
              options: [
                'Increase the lifting capacity at the column',
                'Increase the crane\'s reach (working radius)',
                'Replace the need for stabilizer legs',
                'Lower the crane\'s center of gravity',
              ],
              correctIndex: 1,
              explanation: 'Extensions add reach. Remember that capacity drops as reach increases — extending the boom moves the load farther from the crane and reduces what it can safely lift.',
            },
            {
              question: 'Where on the machine should an operator find the rated capacity information for an articulating loader crane?',
              options: [
                'Only in the truck\'s glovebox registration folder',
                'On the load chart and capacity decals affixed to the crane',
                'It does not exist for loader cranes',
                'Stamped on the hook only',
              ],
              correctIndex: 1,
              explanation: 'The manufacturer\'s load chart and capacity decals on the crane are the authoritative capacity reference. They must be legible and present; an operator cannot safely work without knowing the rated capacities.',
            },
          ],
        },
        {
          id: '1e-m2-s2',
          title: 'Components',
          durationHours: 1.5,
          learningObjectives: [
            'Identify load-handling components such as the hook, winch, and attachments',
            'Explain the purpose of stabilizer legs and beams in the support system',
            'Describe safety devices including the hook latch and load-limiting devices',
            'Recognize wear and damage indicators on key components',
          ],
          topics: [
            'Hook and hook latch (safety catch): keeps slings and rigging from coming off the hook',
            'Winch and wire rope (when equipped): used for hook-and-line lifts rather than rigid boom-tip lifts',
            'Attachments: grapples, pallet forks, clamshell buckets, work platforms — each changes capacity and balance',
            'Stabilizer (outrigger) legs, beams, and pads: extend and set to widen the support base',
            'Load-limiting / overload protection devices: warn or stop the crane as it approaches rated capacity',
            'Boom rest and transport locks for road travel',
            'Hydraulic hoses, fittings, and cylinders as wear points',
            'Pins, bushings, and knuckle joints: inspect for elongation, cracks, and excessive play',
            'Decals, load charts, and warning labels — must be legible',
          ],
          resources: [
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'OSHA 1926 Subpart CC — Cranes & Derricks in Construction',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926SubpartCC',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'What is the purpose of the hook latch (safety catch) on a loader crane hook?',
              options: [
                'It increases the rated capacity of the hook',
                'It keeps slings, chains, and rigging from slipping off the hook',
                'It locks the boom for road transport',
                'It measures the weight of the load',
              ],
              correctIndex: 1,
              explanation: 'The hook latch closes the throat opening so rigging cannot slip off, especially when the load swings or the line goes slack. A missing or broken latch is a defect that must be corrected before lifting.',
            },
            {
              question: 'You install a grapple attachment in place of the hook. How does this affect the crane?',
              options: [
                'It has no effect on capacity or balance',
                'It changes the crane\'s capacity and balance; the load chart must be re-checked for that configuration',
                'It automatically doubles the rated capacity',
                'It exempts the crane from inspection',
              ],
              correctIndex: 1,
              explanation: 'Any attachment adds weight at the boom tip and changes the load chart that applies. The operator must work from the capacity information for the actual configuration in use, not the bare-hook chart.',
            },
            {
              question: 'During inspection you find one stabilizer pad is missing. What is the correct action?',
              options: [
                'Operate normally; pads are optional',
                'Operate but lift only light loads',
                'Take the crane out of service until the stabilizer system is complete and functional',
                'Substitute a piece of scrap wood and continue',
              ],
              correctIndex: 2,
              explanation: 'The stabilizer system is what keeps the crane from tipping. A missing pad means the support base is compromised. The crane must be taken out of service until the stabilizer system is complete and properly functioning.',
            },
            {
              question: 'A load-limiting (overload protection) device on a loader crane is designed to:',
              options: [
                'Increase the speed of the boom functions',
                'Warn the operator and/or stop crane functions as the load approaches rated capacity',
                'Replace the need to read the load chart',
                'Allow controlled lifting above rated capacity',
              ],
              correctIndex: 1,
              explanation: 'The device warns or interrupts functions near rated capacity to help prevent overload tip-overs and structural failure. It is a backup, not a substitute — the operator is still responsible for knowing the load and the chart.',
            },
            {
              question: 'When inspecting knuckle joints, pins, and bushings on an articulating crane, you are checking primarily for:',
              options: [
                'Fresh paint and a clean appearance',
                'Cracks, elongation, and excessive play or wear',
                'Manufacturer brand decals',
                'The serial number',
              ],
              correctIndex: 1,
              explanation: 'Pins and bushings carry the articulation loads. Cracks, elongated holes, or excessive play indicate wear that can lead to sudden failure under load and must be corrected before operation.',
            },
            {
              question: 'Why must load charts, capacity decals, and warning labels on the crane be kept legible?',
              options: [
                'For resale value only',
                'So the operator can correctly determine safe lifting limits and follow warnings',
                'They are decorative and have no operational role',
                'Only inspectors need to read them',
              ],
              correctIndex: 1,
              explanation: 'The operator relies on these decals every shift to determine safe capacities and heed hazard warnings. Illegible or missing decals leave the operator guessing, so they must be replaced when damaged.',
            },
          ],
        },
        {
          id: '1e-m2-s3',
          title: 'Hydraulics',
          durationHours: 1.5,
          learningObjectives: [
            'Describe the basic components of a loader crane hydraulic system',
            'Explain how the PTO and pump supply hydraulic power on a truck-mounted crane',
            'Identify common hydraulic faults: leaks, contamination, and overheating',
            'State the safety hazards of hydraulic fluid under pressure',
          ],
          topics: [
            'Power take-off (PTO): draws power from the truck transmission to drive the hydraulic pump',
            'Hydraulic pump, reservoir, filter, and fluid: the source side of the system',
            'Control valves: direct flow to the boom, slew, extension, and stabilizer cylinders',
            'Cylinders and hydraulic motors: convert fluid pressure into boom and slew motion',
            'Hoses, fittings, and quick couplers: common leak and failure points',
            'Relief valves and holding (counterbalance) valves: limit pressure and hold the load if a hose bursts',
            'Common faults: external leaks, fluid contamination, aeration, and overheating',
            'Hazards: high-pressure pinhole leaks can inject fluid into skin — never search for leaks by hand',
            'Checking fluid level, condition, and temperature as part of the daily inspection',
          ],
          resources: [
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'OSHA 1926 Subpart CC — Cranes & Derricks in Construction',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926SubpartCC',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'On a truck-mounted loader crane, what is the role of the power take-off (PTO)?',
              options: [
                'It is a backup braking system for the truck',
                'It draws power from the truck transmission to drive the hydraulic pump',
                'It is the operator control joystick',
                'It locks the boom for transport',
              ],
              correctIndex: 1,
              explanation: 'The PTO taps mechanical power from the truck transmission and uses it to turn the hydraulic pump. If the PTO is not engaged correctly, the crane has no hydraulic power.',
            },
            {
              question: 'You suspect a pressurized hydraulic hose has a small leak. How should you locate it?',
              options: [
                'Run your bare hand along the hose to feel for spray',
                'Use a piece of cardboard or paper, keeping hands and body clear, with the system depressurized when possible',
                'Look directly at the suspected spot from a few inches away',
                'Wipe the hose with a rag while the system is at full pressure',
              ],
              correctIndex: 1,
              explanation: 'A high-pressure pinhole leak can inject hydraulic fluid through skin, causing severe injury. Never search by hand — use cardboard, keep clear, and depressurize the system where possible.',
            },
            {
              question: 'What is the function of a holding (counterbalance) valve on a boom cylinder?',
              options: [
                'It speeds up boom movement',
                'It holds the load in place and prevents the boom from dropping if a hose fails',
                'It heats the hydraulic fluid in cold weather',
                'It disengages the PTO automatically',
              ],
              correctIndex: 1,
              explanation: 'Holding or counterbalance valves keep the cylinder from collapsing if downstream pressure is lost, such as from a burst hose. They are a critical safety feature that prevents sudden uncontrolled load drops.',
            },
            {
              question: 'During a daily check you find the hydraulic fluid is milky and foamy. This most likely indicates:',
              options: [
                'The fluid is fresh and ready to use',
                'Air or water contamination in the system',
                'The crane has extra lifting capacity',
                'The PTO is over-engaged',
              ],
              correctIndex: 1,
              explanation: 'Milky or foamy fluid indicates aeration or water contamination. Contaminated fluid causes spongy, unpredictable control response and accelerates wear; the cause must be found and corrected.',
            },
            {
              question: 'Why is hydraulic system overheating a concern on a loader crane?',
              options: [
                'It improves lifting performance',
                'It degrades the fluid, reduces lubrication, and can cause seal failure and erratic operation',
                'It only matters in winter',
                'It has no operational effect',
              ],
              correctIndex: 1,
              explanation: 'Overheated fluid thins out, loses its lubricating and sealing properties, and breaks down chemically. This leads to seal failure, erratic control, and component damage, so rising temperature should not be ignored.',
            },
            {
              question: 'Which of the following is part of a proper daily hydraulic check?',
              options: [
                'Disassembling the pump to inspect internal gears',
                'Checking fluid level and condition and looking for leaks at hoses, fittings, and cylinders',
                'Refilling the reservoir with motor oil',
                'Adjusting the relief valve pressure setting',
              ],
              correctIndex: 1,
              explanation: 'The daily check is visual and external: verify fluid level and condition and scan hoses, fittings, and cylinders for leaks or damage. Internal repairs and valve adjustments are for qualified technicians, not the daily routine.',
            },
          ],
        },
      ],
    },
    {
      id: '1e-m3',
      title: 'Operation',
      orderInCourse: 3,
      estimatedHours: 5,
      sessions: [
        {
          id: '1e-m3-s1',
          title: 'Safety',
          durationHours: 2,
          learningObjectives: [
            'Explain how to set up an articulating crane on a stable, level base',
            'Describe load-chart use and the effect of working radius on capacity',
            'Identify the hazards of overhead power lines and required clearances',
            'Apply safe practices for working near people and the crane danger zone',
          ],
          topics: [
            'Site setup: level ground, firm support, stabilizers fully set with pads and cribbing as needed',
            'Reading the load chart: capacity decreases as working radius and boom configuration change',
            'Never exceed rated capacity; account for the weight of rigging and attachments',
            'Overhead power line hazards and minimum approach distances under OSHA 1926 Subpart CC',
            'Keeping people out of the danger zone and never carrying loads over workers',
            'Avoiding side loading and dragging loads — articulating cranes are built for vertical lifting',
            'Controlling load swing: lift smoothly, avoid sudden boom or slew movements',
            'Weather limits: wind on the load, ice, and poor visibility',
            'Securing the crane: stow the boom, retract stabilizers, and apply transport locks before traveling',
          ],
          resources: [
            {
              label: 'OSHA 1926 Subpart CC — Cranes & Derricks in Construction',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926SubpartCC',
              type: 'osha',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'SAE J1307 Hand Signals — Quick Reference Guide',
              url: '/hand-signals',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'You arrive at a site to make a lift, but the ground under one stabilizer is soft fill. What should you do?',
              options: [
                'Lift quickly before the ground can settle',
                'Set that stabilizer on adequate cribbing/pads to spread the load, or relocate to firm ground',
                'Skip that stabilizer and use the other three',
                'Lift only on the opposite side of the truck',
              ],
              correctIndex: 1,
              explanation: 'A stabilizer on soft ground can sink under load and cause a tip-over. Use proper cribbing and pads to spread the load onto firm bearing, or move the crane to stable ground.',
            },
            {
              question: 'As you extend the boom to reach a load farther away, the crane\'s rated capacity:',
              options: [
                'Increases because the boom is longer',
                'Stays exactly the same at any radius',
                'Decreases because the load is at a greater working radius',
                'Is no longer governed by the load chart',
              ],
              correctIndex: 2,
              explanation: 'Capacity decreases as working radius increases — the load creates more tipping leverage the farther it is from the crane. Always read the chart for the actual radius you will be working at.',
            },
            {
              question: 'A load you must place sits beyond an energized overhead power line. What is the correct approach?',
              options: [
                'Move quickly under the line so the boom is exposed only briefly',
                'Maintain the required minimum clearance from the line; if that is not possible, stop and have the line de-energized or relocated',
                'Touch the line first with the boom to test if it is live',
                'Proceed if the load is non-conductive',
              ],
              correctIndex: 1,
              explanation: 'Power line contact is a leading cause of crane fatalities. You must keep the required minimum approach distance under OSHA 1926 Subpart CC; if the lift cannot be done safely within clearance, the line must be de-energized or the work relocated.',
            },
            {
              question: 'Why should you never use an articulating loader crane to drag a load sideways?',
              options: [
                'It wastes hydraulic fluid',
                'Side loading applies forces the boom is not designed for and can cause structural failure or tip-over',
                'It is allowed as long as the load is light',
                'It only voids the truck warranty',
              ],
              correctIndex: 1,
              explanation: 'Loader crane booms are designed for vertical lifting, not side pulls. Side loading and dragging impose dangerous lateral forces that can buckle the boom or tip the crane.',
            },
            {
              question: 'A worker needs to stand directly under a suspended load "just for a second" to guide it. What do you do?',
              options: [
                'Allow it if the load is light',
                'Allow it if they wear a hard hat',
                'Do not move or hold the load over anyone — wait until they are clear of the danger zone',
                'Allow it if the signaler approves',
              ],
              correctIndex: 2,
              explanation: 'No one may be under a suspended load. Rigging can fail and loads can shift; keep all personnel out of the danger zone and never carry or hold a load over a worker.',
            },
            {
              question: 'Before driving the truck away from a completed lift, the operator must:',
              options: [
                'Leave the boom extended for the next job',
                'Stow the boom, retract and secure the stabilizers, and apply transport locks',
                'Only retract the stabilizers; the boom can stay up',
                'Nothing — the crane is road-ready as soon as the load is set down',
              ],
              correctIndex: 1,
              explanation: 'Traveling with the boom up or stabilizers out is unstable and a serious hazard to traffic and structures. The crane must be fully stowed, stabilizers retracted and secured, and transport locks applied before moving.',
            },
            {
              question: 'Gusty wind is pushing the suspended load and making it hard to control. The safest response is to:',
              options: [
                'Increase slew speed to beat the gusts',
                'Stop the lift and wait for conditions to improve, or postpone the work',
                'Add more weight to the load to steady it',
                'Continue — wind never affects loader cranes',
              ],
              correctIndex: 1,
              explanation: 'Wind on the load increases swing and side forces and reduces control. If you cannot control the load, stop and wait for conditions to improve rather than risk a dropped or swinging load.',
            },
          ],
        },
        {
          id: '1e-m3-s2',
          title: 'Inspection',
          durationHours: 1.5,
          learningObjectives: [
            'Perform a daily pre-operational inspection of an articulating loader crane',
            'Distinguish a defect that requires removing the crane from service from a minor item',
            'Explain the operator\'s duty to document inspections and report defects',
            'Describe periodic and annual inspection requirements',
          ],
          topics: [
            'Daily pre-operational (shift) inspection before first use',
            'Structural check: boom sections, knuckle joint, column, subframe, and mounting for cracks and deformation',
            'Hydraulic check: fluid level and condition, leaks at hoses, fittings, and cylinders',
            'Stabilizer system: legs, beams, pads, locks, and controls',
            'Load-handling check: hook, hook latch, wire rope and winch (if equipped), attachments',
            'Controls, gauges, warning devices, and load-limiting device function',
            'Decals and load charts present and legible',
            'Defect handling: tag out and remove from service until repaired by qualified personnel',
            'Periodic and annual inspections by a qualified inspector; recordkeeping requirements',
          ],
          resources: [
            {
              label: 'OSHA 1926 Subpart CC — Cranes & Derricks in Construction',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926SubpartCC',
              type: 'osha',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'When must the operator perform the daily pre-operational inspection?',
              options: [
                'Once a week is sufficient',
                'Before the crane is first used on the shift',
                'Only after a load is dropped',
                'Only when an inspector is on site',
              ],
              correctIndex: 1,
              explanation: 'A pre-operational inspection must be done before the crane is first used each shift. Catching a defect before work begins is the entire point — it is the operator\'s responsibility, not the inspector\'s.',
            },
            {
              question: 'During inspection you find a crack in the knuckle joint area of the boom. What is the correct action?',
              options: [
                'Monitor it through the shift and report it tomorrow',
                'Field-weld the crack and keep working',
                'Tag the crane out of service and remove it from use until repaired by qualified personnel',
                'Reduce lifts to half capacity and continue',
              ],
              correctIndex: 2,
              explanation: 'A crack in a load-bearing structural member can fail suddenly under load. The crane must be tagged out and removed from service until properly repaired and re-inspected by qualified personnel.',
            },
            {
              question: 'You find the hook latch is bent and will not close fully. Is this a "minor" item you can defer?',
              options: [
                'Yes, the latch is optional equipment',
                'Yes, as long as you only lift with chains',
                'No, a non-functioning hook latch is a defect that must be corrected before lifting',
                'Yes, if you lift slowly',
              ],
              correctIndex: 2,
              explanation: 'The hook latch keeps rigging from coming off the hook. A latch that will not close is a real defect that must be repaired before the crane is used for lifting.',
            },
            {
              question: 'Who is responsible for documenting the daily inspection and reporting defects found?',
              options: [
                'Only the annual inspector',
                'The operator who performs the pre-operational inspection',
                'The truck dealership',
                'No documentation is needed for loader cranes',
              ],
              correctIndex: 1,
              explanation: 'The operator who performs the daily inspection is responsible for documenting it and reporting any defects so they can be corrected. Good records also protect the operator if a question arises later.',
            },
            {
              question: 'In addition to daily operator inspections, articulating cranes require:',
              options: [
                'No further inspections of any kind',
                'Periodic and annual inspections by a qualified inspector',
                'Inspection only when sold to a new owner',
                'Inspection only after an accident',
              ],
              correctIndex: 1,
              explanation: 'Daily operator inspections are the first layer. More thorough periodic and annual inspections by a qualified inspector are also required, with records kept to show the crane has been properly maintained.',
            },
            {
              question: 'During the stabilizer portion of your inspection, you should verify that:',
              options: [
                'Only the paint color is correct',
                'Legs, beams, pads, locks, and controls are present, undamaged, and function properly',
                'The stabilizers are welded permanently in the stowed position',
                'The stabilizers match the truck\'s tire brand',
              ],
              correctIndex: 1,
              explanation: 'The stabilizer system prevents tip-over, so the inspection must confirm the legs, beams, pads, locks, and controls are all present, undamaged, and working before any lift is attempted.',
            },
          ],
        },
        {
          id: '1e-m3-s3',
          title: 'Signals',
          durationHours: 1.5,
          learningObjectives: [
            'Identify who is authorized to direct a crane operator under 230 CMR 6.00',
            'State the hand signal standard required by 230 CMR 6.00',
            'Recognize the standard hand signals and the emergency stop signal',
            'Explain operator duties when signals are unclear, lost, or conflicting',
          ],
          topics: [
            'Only an approved signaler may direct the operator\'s movements',
            'SAE J1307 hand signals required by 230 CMR 6.00',
            'Standard signals: hoist, lower, boom up, boom down, swing, stop, and emergency stop',
            'Emergency stop (crossed arms) may be given by anyone and always takes precedence',
            'If the operator loses sight of the signaler, all crane movement must stop',
            'Conflicting signals: stop until the conflict is resolved',
            'When radio communication is used, agree on procedures and a "lost-signal" rule beforehand',
            'Pre-lift communication: operator and signaler agree on the plan before the lift',
            'The operator may always refuse an unsafe signal or lift',
          ],
          resources: [
            {
              label: 'SAE J1307 Hand Signals — Quick Reference Guide',
              url: '/hand-signals',
              type: 'reference',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'OSHA 1926 Subpart CC — Cranes & Derricks in Construction',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926SubpartCC',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'Under 230 CMR 6.00, who is the only person authorized to direct the crane operator\'s movements?',
              options: [
                'Any worker on the job site',
                'The general contractor\'s superintendent',
                'The approved signaler assigned to the lift',
                'Whoever is closest to the load',
              ],
              correctIndex: 2,
              explanation: 'Only an approved signaler may direct the operator. Taking direction from anyone else, even a supervisor, violates the regulation and creates confusion that leads to accidents.',
            },
            {
              question: 'Which hand signal standard does 230 CMR 6.00 require for hoisting machinery in Massachusetts?',
              options: ['SAE J1307', 'SAE J386', 'OSHA J1', 'There is no required standard'],
              correctIndex: 0,
              explanation: 'SAE J1307 is the hand signal standard required by 230 CMR 6.00. Both the operator and the signaler must know and use these standard signals.',
            },
            {
              question: 'A laborer who is not the designated signaler suddenly gives the emergency stop signal. What does the operator do?',
              options: [
                'Ignore it because it is not from the designated signaler',
                'Stop all crane movement immediately',
                'Ask the signaler whether to stop',
                'Finish the current motion first',
              ],
              correctIndex: 1,
              explanation: 'The emergency stop signal may be given by anyone and always takes precedence. The operator must stop immediately — that person may see a hazard the operator and signaler cannot.',
            },
            {
              question: 'Mid-lift, the operator loses sight of the signaler behind a stack of materials. The correct action is to:',
              options: [
                'Keep moving slowly until the signaler reappears',
                'Stop all crane movement until visual contact (or agreed communication) is restored',
                'Have a nearby worker relay signals',
                'Guess where the load should go',
              ],
              correctIndex: 1,
              explanation: 'If visual contact with the signaler is lost, the operator must stop. A signaler who cannot see the operator and load cannot safely direct the lift, and informal relays introduce errors.',
            },
            {
              question: 'The operator receives conflicting signals from two people at once. What should the operator do?',
              options: [
                'Follow whichever signal seems easier',
                'Follow the louder or more senior person',
                'Stop until the conflict is resolved; an emergency stop from anyone takes immediate priority',
                'Average the two signals',
              ],
              correctIndex: 2,
              explanation: 'Conflicting signals mean the situation is not clear, so the operator stops until it is resolved. The one exception is that an emergency stop from anyone overrides everything and is obeyed immediately.',
            },
            {
              question: 'A signaler directs a lift that the operator can see would overload the crane. What may the operator do?',
              options: [
                'Nothing — the operator must always follow the signaler',
                'Refuse the lift; the operator may always decline an unsafe signal or lift',
                'Perform the lift but blame the signaler afterward',
                'Perform half the lift',
              ],
              correctIndex: 1,
              explanation: 'The operator is the last line of defense. Even when directed by an approved signaler, the operator may and should refuse any signal or lift that would be unsafe — the operator is responsible for the machine.',
            },
          ],
        },
      ],
    },
    {
      id: '1e-m4',
      title: 'Review',
      orderInCourse: 4,
      estimatedHours: 5,
      sessions: [
        {
          id: '1e-m4-s1',
          title: 'OSHA',
          durationHours: 2,
          learningObjectives: [
            'Explain how OSHA 1926 Subpart CC applies to cranes used in construction',
            'Describe OSHA requirements for power line clearance and ground conditions',
            'Identify operator and employer duties under the OSHA crane standard',
            'Distinguish the roles of OSHA standards and Massachusetts hoisting regulations',
          ],
          topics: [
            'OSHA 29 CFR 1926 Subpart CC — Cranes & Derricks in Construction',
            'Power line safety: assessing the work zone and maintaining minimum approach distances',
            'Ground conditions: firm, drained, graded support adequate for the crane and load',
            'Assembly/disassembly and setup carried out per manufacturer instructions',
            'Operator competency and the employer\'s duty to ensure it',
            'Inspection requirements: shift, monthly, and annual inspections',
            'Prohibition on hoisting personnel except under the standard\'s specific conditions',
            'How OSHA federal standards work alongside MGL Chapter 146 and 230 CMR 6.00',
            'OSHA general duty: employers must provide a workplace free of recognized hazards',
          ],
          resources: [
            {
              label: 'OSHA 1926 Subpart CC — Cranes & Derricks in Construction',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926SubpartCC',
              type: 'osha',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'MGL Chapter 146 (full chapter)',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146',
              type: 'regulation',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'OSHA 29 CFR 1926 Subpart CC primarily governs:',
              options: [
                'Forklifts used only inside warehouses',
                'Cranes and derricks used in construction work',
                'Passenger elevators',
                'Truck registration requirements',
              ],
              correctIndex: 1,
              explanation: 'Subpart CC is the federal standard for cranes and derricks in construction. When an articulating crane is used in construction work, its operation falls under Subpart CC in addition to Massachusetts requirements.',
            },
            {
              question: 'Under the OSHA crane standard, before setting up a crane the ground conditions must be:',
              options: [
                'Any surface, since stabilizers compensate for everything',
                'Firm, drained, and graded sufficiently to support the crane and load, with supporting materials as needed',
                'Freshly paved asphalt only',
                'Inspected only after the lift is complete',
              ],
              correctIndex: 1,
              explanation: 'The standard requires ground conditions adequate to support the crane and the planned loads. Soft, sloped, or poorly drained ground must be addressed with cribbing, mats, or relocation before setup.',
            },
            {
              question: 'How do OSHA standards relate to Massachusetts hoisting regulations for a 1E operator?',
              options: [
                'OSHA replaces all Massachusetts requirements',
                'They apply together — the operator must follow OSHA standards and MGL Chapter 146 / 230 CMR 6.00',
                'Massachusetts rules apply only on weekends',
                'OSHA standards do not apply to truck-mounted cranes',
              ],
              correctIndex: 1,
              explanation: 'Federal OSHA standards and Massachusetts statute and regulation apply together. The operator must satisfy both — meeting one does not excuse violating the other.',
            },
            {
              question: 'Under OSHA Subpart CC, who has the duty to ensure a crane operator is competent for the equipment they run?',
              options: [
                'The operator alone, with no employer involvement',
                'The employer',
                'The crane manufacturer',
                'The load being lifted',
              ],
              correctIndex: 1,
              explanation: 'The employer has a duty to ensure operators are competent and properly qualified for the equipment. This parallels MGL §66, which also places responsibility on the employer.',
            },
            {
              question: 'OSHA Subpart CC generally prohibits hoisting personnel with a crane except when:',
              options: [
                'The crew is in a hurry',
                'Specific conditions in the standard are met and conventional means would be more hazardous or infeasible',
                'The load is light',
                'It is never prohibited',
              ],
              correctIndex: 1,
              explanation: 'Hoisting personnel is allowed only under the narrow conditions the standard sets, and generally only when other access methods would be more hazardous or are infeasible. It is not a routine practice.',
            },
            {
              question: 'OSHA requires crane inspections on which schedule?',
              options: [
                'Only once when the crane is purchased',
                'Shift (each work shift), monthly, and annual inspections',
                'Annual only',
                'Only after a reportable accident',
              ],
              correctIndex: 1,
              explanation: 'The standard layers inspections: an inspection each shift, a more detailed monthly inspection, and a comprehensive annual inspection, each by appropriately qualified persons.',
            },
            {
              question: 'A crane is set up where the boom could swing within the minimum approach distance of an energized power line. Under OSHA, the employer must:',
              options: [
                'Do nothing if the operator is experienced',
                'Take measures such as de-energizing the line, maintaining clearance, or using other Subpart CC encroachment-prevention options',
                'Simply warn workers to be careful',
                'Speed up the work to limit exposure time',
              ],
              correctIndex: 1,
              explanation: 'Power line encroachment must be actively prevented — by de-energizing and grounding the line, keeping the required clearance, or using the other specific options in Subpart CC. Verbal warnings alone are not compliance.',
            },
          ],
        },
        {
          id: '1e-m4-s2',
          title: 'Practice 1',
          durationHours: 1.5,
          learningObjectives: [
            'Apply licensing and regulatory knowledge to exam-style questions',
            'Reinforce articulating crane equipment and component knowledge',
            'Self-assess readiness on the legal and equipment portions of the exam',
            'Identify weak areas to review before the next practice set',
          ],
          topics: [
            'Mixed review: MGL Chapter 146 licensing, age, fees, and renewal',
            'Mixed review: 230 CMR 6.00 operating rules and signaler requirements',
            'Mixed review: 1E scope and how it differs from other Class 1 restrictions',
            'Mixed review: articulating crane systems, components, and hydraulics',
            'Test-taking strategy: read every option, eliminate clearly wrong answers',
            'Flagging uncertain questions for focused review',
          ],
          resources: [
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'An applicant scores 68% on the hoisting exam. What happens next?',
              options: [
                'They pass; 68% is above the cutoff',
                'They fail and must wait 60 days before retesting',
                'They may retest the same day',
                'They automatically get a temporary license',
              ],
              correctIndex: 1,
              explanation: 'The passing score is 70%, so 68% is a fail. After a failed attempt the applicant must wait 60 days to retest — a strong reason to be fully prepared the first time.',
            },
            {
              question: 'Which best describes the boom of an articulating loader crane?',
              options: [
                'A single straight boom that telescopes in and out only',
                'Multiple boom sections hinged at knuckle joints, often with hydraulic extensions',
                'A lattice structure assembled from bolted steel sections',
                'A fixed jib with no moving parts',
              ],
              correctIndex: 1,
              explanation: 'An articulating crane uses hinged boom sections that fold at knuckle joints, frequently combined with hydraulic extensions for added reach. This is what separates it from a 1C-style telescoping boom.',
            },
            {
              question: 'You need to add the 1E restriction to an existing hoisting license. What fee applies?',
              options: [
                'No fee for adding a restriction',
                'A $75 non-refundable fee for the additional restriction',
                'A flat $10 processing fee',
                'Double the original license fee',
              ],
              correctIndex: 1,
              explanation: 'Each restriction class carries its own $75 non-refundable application fee, whether it is a first license or an added restriction.',
            },
            {
              question: 'Why must stabilizers be fully set before lifting with a loader crane?',
              options: [
                'To make the truck easier to steer',
                'To widen the support base and keep the crane from tipping under load',
                'To cool the hydraulic fluid',
                'It is optional on level ground',
              ],
              correctIndex: 1,
              explanation: 'Stabilizers extend the crane\'s footprint so the load stays within a stable base. Lifting without them fully set, even on level ground, dramatically raises tip-over risk.',
            },
            {
              question: 'A milky, foamy hydraulic fluid sample most likely means:',
              options: [
                'The fluid is brand new',
                'Air or water has contaminated the system and the cause must be found',
                'The crane can lift more than rated',
                'The PTO is disengaged',
              ],
              correctIndex: 1,
              explanation: 'Aerated or water-contaminated fluid looks milky and foamy and causes erratic, spongy control. The contamination source must be identified and corrected before the crane is trusted with a lift.',
            },
            {
              question: 'Operating a crane outside the equipment your restriction authorizes is treated as:',
              options: [
                'A minor paperwork issue',
                'Equivalent to operating with no license, exposing operator and employer to penalties',
                'Acceptable if a licensed operator is nearby',
                'Acceptable for one shift',
              ],
              correctIndex: 1,
              explanation: 'A restriction authorizes only specific equipment. Running equipment outside it is the same as having no license for that machine, and both operator and employer can face civil penalties.',
            },
          ],
        },
        {
          id: '1e-m4-s3',
          title: 'Practice 2',
          durationHours: 1.5,
          learningObjectives: [
            'Apply safe-operation and inspection knowledge to exam-style questions',
            'Reinforce signaling rules and OSHA crane requirements',
            'Confirm overall readiness across all four modules',
            'Build a final review plan targeting any remaining weak areas',
          ],
          topics: [
            'Mixed review: site setup, load charts, and the radius–capacity relationship',
            'Mixed review: power line clearance and danger-zone control',
            'Mixed review: daily inspection and defect handling',
            'Mixed review: SAE J1307 signals, lost-signal and conflicting-signal rules',
            'Mixed review: OSHA 1926 Subpart CC duties and inspection schedule',
            'Final readiness self-assessment and targeted review planning',
          ],
          resources: [
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: true,
            },
            {
              label: 'OSHA 1926 Subpart CC — Cranes & Derricks in Construction',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926SubpartCC',
              type: 'osha',
              required: false,
            },
            {
              label: 'SAE J1307 Hand Signals — Quick Reference Guide',
              url: '/hand-signals',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'You are lifting near an energized overhead power line and cannot maintain the required minimum clearance. The correct action is to:',
              options: [
                'Move faster so the boom is exposed only briefly',
                'Stop and have the line de-energized or relocated, or move the work, before continuing',
                'Continue if the load is non-conductive',
                'Lower the boom and proceed underneath the line',
              ],
              correctIndex: 1,
              explanation: 'If you cannot keep the required clearance, the lift cannot proceed safely. The line must be de-energized and grounded, relocated, or the work moved — power line contact is a leading cause of crane fatalities.',
            },
            {
              question: 'Mid-lift you lose sight of your signaler. What do you do?',
              options: [
                'Continue at reduced speed',
                'Stop all crane movement until visual contact or agreed communication is restored',
                'Have any nearby worker relay signals',
                'Set the load down wherever the boom currently points',
              ],
              correctIndex: 1,
              explanation: 'Loss of visual contact with the signaler requires an immediate stop. A signaler who cannot see the load cannot safely direct it, and casual relays introduce dangerous errors.',
            },
            {
              question: 'During your daily inspection you find a structural crack near the knuckle joint. You should:',
              options: [
                'Finish the day\'s lifts, then report it',
                'Tag the crane out of service until it is repaired and re-inspected by qualified personnel',
                'Weld it yourself and keep working',
                'Lift only light loads for the rest of the shift',
              ],
              correctIndex: 1,
              explanation: 'A crack in a load-bearing member can fail without warning. The crane must be removed from service and not used until properly repaired and re-inspected.',
            },
            {
              question: 'As the working radius increases, an articulating crane\'s rated capacity:',
              options: [
                'Increases',
                'Decreases',
                'Stays the same',
                'No longer matters',
              ],
              correctIndex: 1,
              explanation: 'Capacity decreases as radius increases because the load exerts more tipping leverage farther from the crane. Always read the load chart for the actual radius of the lift.',
            },
            {
              question: 'Under OSHA Subpart CC, crane inspections are required:',
              options: [
                'Once at purchase only',
                'Each shift, monthly, and annually',
                'Annually only',
                'Only after an accident',
              ],
              correctIndex: 1,
              explanation: 'Subpart CC requires layered inspections: a shift inspection, a monthly inspection, and a comprehensive annual inspection, each performed by appropriately qualified persons.',
            },
            {
              question: 'An approved signaler directs a lift the operator can see would overload the crane. The operator should:',
              options: [
                'Always follow the signaler without question',
                'Refuse the unsafe lift — the operator may always decline an unsafe signal',
                'Perform the lift and document the signaler\'s name',
                'Perform the lift at reduced speed',
              ],
              correctIndex: 1,
              explanation: 'The operator is the final safeguard. Even when directed by an approved signaler, the operator may and must refuse any signal or lift that would be unsafe.',
            },
            {
              question: 'Before driving a loader crane truck on the road after a lift, the operator must:',
              options: [
                'Leave the boom up to save time at the next stop',
                'Fully stow the boom, retract and secure the stabilizers, and apply transport locks',
                'Retract only the stabilizers',
                'Do nothing — it is road-ready once the load is down',
              ],
              correctIndex: 1,
              explanation: 'Traveling with the boom raised or stabilizers extended is unstable and endangers traffic and structures. The crane must be fully stowed and locked for transport before the truck moves.',
            },
          ],
        },
      ],
    },
  ],
};
