import { LicenseRestriction } from '../types';

export const restriction_2a: LicenseRestriction = {
  code: '2A',
  name: 'Excavating Machinery',
  description: 'Covers all crawler and rubber-tired excavators, track hoes, backhoes, and skid steer loaders. The most common single-restriction license for site work and utility crews.',
  equipmentCovered: ['Crawler excavators', 'Rubber-tired excavators', 'Track hoes', 'Backhoes', 'Skid steer loaders'],
  totalHours: 20,
  modules: [
    {
      id: '2a-m1',
      title: 'Legal & Regulatory Foundation',
      orderInCourse: 1,
      estimatedHours: 5,
      sessions: [
        {
          id: '2a-m1-s1',
          title: 'MGL Chapter 146 — Licensing Requirements',
          durationHours: 2,
          learningObjectives: [
            'State the minimum age and exam passing score for a 2A license',
            'Identify the three threshold conditions that trigger a hoisting license requirement',
            'List the key exemptions under MGL §53',
            'Explain the license duration and renewal cycle',
          ],
          topics: [
            'MGL §53 — who must hold a hoisting license',
            'Minimum age requirement: 18 years old',
            'License duration and renewal: 2-year cycle',
            'Exam passing score: 70% minimum',
            '60-day waiting period after a failed attempt',
            '$75 non-refundable application fee per restriction class',
            'Exemptions: agricultural operators, public utility supervised programs, industrial lift trucks on company property, vocational schools, approved apprenticeship programs',
            'License classification: Group 2 excavating equipment',
            'Application through the MA Division of Occupational Licensure (DOL)',
          ],
          resources: [
            {
              label: 'MGL Chapter 146 — Licensing Requirements Reference',
              url: '/reference/2a-m1-s1',
              type: 'reference',
              required: true,
            },

            {
              label: 'MGL Chapter 146 § 53 — Licensing requirement',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146/Section53',
              type: 'regulation',
              required: true,
            },
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: true,
            },
            {
              label: 'Apply for a Hoisting Engineer License',
              url: 'https://www.mass.gov/how-to/apply-for-a-hoisting-engineer-license',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'What is the minimum passing score on the Massachusetts 2A hoisting engineer exam?',
              options: ['60%', '65%', '70%', '75%'],
              correctIndex: 2,
              explanation: 'The passing score is 70%. Score below 70% and you must wait 60 days before retesting — plan your study time accordingly.',
            },
            {
              question: 'Which of the following operators is EXEMPT from holding a Massachusetts hoisting license?',
              options: [
                'A utility contractor operating an excavator on a city street',
                'A farmhand operating an excavator exclusively on agricultural land',
                'A landscaper operating a skid steer on a residential job site',
                'A demolition worker operating a track hoe on private property',
              ],
              correctIndex: 1,
              explanation: 'Agricultural operators on their own land are explicitly exempt under MGL §53. The other operators are doing construction or utility work that requires a 2A license regardless of the property owner.',
            },
            {
              question: 'How long is a Massachusetts hoisting engineer license valid before renewal is required?',
              options: ['1 year', '2 years', '3 years', '5 years'],
              correctIndex: 1,
              explanation: 'The 2A hoisting license is valid for 2 years. Always verify the current renewal cycle at mass.gov — renewal requirements can change.',
            },
            {
              question: 'What is the minimum age to obtain a Massachusetts 2A hoisting engineer license?',
              options: ['16', '17', '18', '21'],
              correctIndex: 2,
              explanation: 'MGL Chapter 146 sets the minimum age at 18 years old. Applicants under 18 cannot obtain a hoisting license regardless of experience or training.',
            },
            {
              question: 'How long must you wait before retaking the 2A hoisting exam after a failed attempt?',
              options: ['7 days', '30 days', '60 days', '90 days'],
              correctIndex: 2,
              explanation: 'You must wait 60 days after a failed attempt before retesting. This is specifically to prevent rushed, unprepared re-attempts — use that time to study the areas where you scored poorly.',
            },
            {
              question: 'Which of the following best describes the relationship between MGL Chapter 146 and 230 CMR 6.00?',
              options: [
                'MGL Chapter 146 is federal law; 230 CMR 6.00 is state law',
                'MGL Chapter 146 is the statute passed by the legislature; 230 CMR 6.00 is the implementing regulation',
                'They are two different names for the same regulation',
                '230 CMR 6.00 supersedes MGL Chapter 146 in all cases',
              ],
              correctIndex: 1,
              explanation: 'MGL (Massachusetts General Law) is statute — passed by the legislature and signed by the governor. 230 CMR 6.00 is a regulation that implements and expands MGL Chapter 146 with specific technical requirements.',
            },
            {
              question: 'What is the non-refundable application fee for each restriction class when applying for a Massachusetts hoisting engineer license?',
              options: ['$25', '$50', '$75', '$100'],
              correctIndex: 2,
              explanation: 'As of current MA regulations, the application fee is $75 per restriction class. This fee is non-refundable even if you fail the exam or your application is denied.',
            },
          ],
        },
        {
          id: '2a-m1-s2',
          title: '230 CMR 6.00 — Rules Specific to Excavating Machinery',
          durationHours: 1.5,
          learningObjectives: [
            'Explain the role of 230 CMR 6.00 relative to MGL Chapter 146',
            'List the four 230 CMR 6.00 operating rules that apply to all 2A equipment',
            'State the SAE hand signal standard required by 230 CMR 6.00',
            'Identify who may ride on or operate the machine during a job',
          ],
          topics: [
            '230 CMR 6.00: minimum safety standards for hoisting machinery in MA',
            'SAE J1307-2023: the required hand signal standard for excavating machinery',
            'Only approved signaler may direct operator movements',
            'No unauthorized personnel on machine during operation',
            'Crew may include operator plus one apprentice under direct supervision',
            'No persons within full working radius during bucket/boom swing',
            'Prohibition on straddling open trenches with excavating machinery',
            'Operators must follow all manufacturer specifications',
            'Differences between 230 CMR and 520 CMR references',
          ],
          resources: [
            {
              label: '230 CMR 6.00 — Operating Rules Reference',
              url: '/reference/2a-m1-s2',
              type: 'reference',
              required: true,
            },

            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'SAE J1307 Hand Signals — Quick Reference Guide',
              url: '/hand-signals',
              type: 'reference',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'Under 230 CMR 6.00, who is the ONLY person authorized to direct an excavator operator\'s movements on a job site?',
              options: [
                'The general contractor\'s site superintendent',
                'Any crew member present at the job site',
                'The approved signaler assigned to the machine',
                'Either the operator or the site safety officer',
              ],
              correctIndex: 2,
              explanation: '230 CMR 6.00 requires that only an approved signaler direct the operator. Taking direction from anyone else — even a supervisor — violates the regulation and creates unsafe conditions.',
            },
            {
              question: 'You are operating an excavator and need to swing the boom. A coworker is standing within the full working radius. What must you do?',
              options: [
                'Sound the horn and proceed carefully',
                'Ask the signaler to wave them off, then proceed',
                'Stop the swing until the worker clears the radius',
                'Slow your swing speed and maintain visual contact',
              ],
              correctIndex: 2,
              explanation: '230 CMR 6.00 prohibits any persons within the full working radius during boom/bucket operation. The only correct action is to stop and wait until the area is clear — no exceptions.',
            },
            {
              question: 'Under 230 CMR 6.00, is an excavator allowed to straddle an open trench?',
              options: [
                'Yes, if the trench is less than 5 feet deep',
                'Yes, if a competent person approves the position',
                'No, straddling open trenches is prohibited',
                'Yes, if outriggers are deployed for stabilization',
              ],
              correctIndex: 2,
              explanation: '230 CMR 6.00 explicitly prohibits excavating machinery from straddling open trenches. The weight and vibration of a machine positioned over a trench dramatically increases cave-in risk.',
            },
            {
              question: 'Beyond the licensed operator, how many additional people may be on an excavator during operation under 230 CMR 6.00?',
              options: [
                'No additional personnel — operator only',
                'One apprentice under the direct supervision of the operator',
                'Two helpers if the site superintendent approves',
                'As many as can safely fit in the cab',
              ],
              correctIndex: 1,
              explanation: '230 CMR 6.00 allows one apprentice in addition to the licensed operator, but only under direct supervision. Unauthorized passengers on the machine at any time violate the regulation.',
            },
            {
              question: 'Which SAE standard specifies the hand signals required by 230 CMR 6.00 for excavating machinery?',
              options: ['SAE J386-1969', 'SAE J1307-2023', 'SAE J320a', 'SAE J237'],
              correctIndex: 1,
              explanation: 'SAE J1307 (most recently revised 2023) is the standard hand signal set for excavators and backhoes required by 230 CMR 6.00. SAE J386 covers seat belts, J320a covers ROPS, and J237 covers braking.',
            },
            {
              question: 'If the operator cannot see the designated signaler during an operation, what must the operator do?',
              options: [
                'Slow down and proceed with extra caution',
                'Stop all machine movement immediately',
                'Switch to radio communication',
                'Ask a nearby worker to relay signals',
              ],
              correctIndex: 1,
              explanation: 'If visual contact with the signaler is lost, 230 CMR 6.00 requires the operator to stop immediately. A signaler out of sight cannot safely direct the machine — no relay system or substitute is permitted.',
            },
            {
              question: 'An excavator operator receives conflicting hand signals from the site superintendent and the designated signaler simultaneously. Which signal takes priority?',
              options: [
                'The site superintendent\'s signal, as they have overall authority',
                'Whichever signal the operator judges to be safer',
                'The designated signaler\'s signal',
                'The Emergency Stop signal if either person gives it; otherwise stop until resolved',
              ],
              correctIndex: 3,
              explanation: 'If conflicting signals are received, the operator must stop until the conflict is resolved. However, if either person gives an Emergency Stop (crossed arms), that always takes immediate precedence over everything else.',
            },
          ],
        },
        {
          id: '2a-m1-s3',
          title: 'MGL §§ 64–67 — Safety, Penalties & Renewal',
          durationHours: 1.5,
          learningObjectives: [
            'Summarize the safety obligations imposed by MGL §§ 64–67',
            'State the civil and criminal penalties for operating without a valid 2A license',
            'Explain the renewal deadline and grace period',
            'Describe the reinstatement process after a license lapse',
          ],
          topics: [
            'MGL §64 — general safety requirements for hoisting equipment',
            'MGL §65 — operator examination and qualification standards',
            'MGL §66 — employer responsibilities for licensed operators',
            'MGL §67 — accident reporting requirements',
            'Civil penalty: up to $500 per day for unlicensed operation',
            'Criminal penalties for repeat violations',
            'Renewal deadline: before expiration; no official "grace period" under current law',
            'Reinstatement after lapse requires re-application and potentially re-examination',
            'Employer liability when using unlicensed operators',
          ],
          resources: [
            {
              label: 'MGL §§ 64–67 — Safety, Penalties & Renewal Reference',
              url: '/reference/2a-m1-s3',
              type: 'reference',
              required: true,
            },

            {
              label: 'MGL Chapter 146 §§ 64–67',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146',
              type: 'regulation',
              required: true,
            },
            {
              label: 'Education requirements for hoisting engineer license',
              url: 'https://www.mass.gov/info-details/education-requirements-for-hoisting-engineer-license',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'What is the maximum civil penalty per day for operating hoisting equipment without a valid Massachusetts license?',
              options: ['$100/day', '$250/day', '$500/day', '$1,000/day'],
              correctIndex: 2,
              explanation: 'MGL §53 allows civil penalties of up to $500 per day for each day of unlicensed operation. Employers who knowingly use unlicensed operators also face liability.',
            },
            {
              question: 'Under MGL §67, what must an operator do after an accident involving hoisting machinery?',
              options: [
                'File a report only if someone was injured',
                'Notify OSHA within 24 hours if a fatality occurred',
                'Report the accident as required by law and cooperate with any investigation',
                'No reporting is required if damage is under $5,000',
              ],
              correctIndex: 2,
              explanation: 'MGL §67 requires reporting accidents involving hoisting machinery. Operators must comply with all reporting requirements and cooperate with inspections — failure to report compounds any penalties.',
            },
            {
              question: 'Under MGL §66, who bears legal responsibility for ensuring a hoisting operator holds a valid license?',
              options: [
                'The operator alone',
                'Both the operator and the employer',
                'The general contractor only',
                'OPSI, which verifies licenses on every job site',
              ],
              correctIndex: 1,
              explanation: 'MGL §66 places responsibility on both the licensed operator to maintain their own valid license AND the employer who directs their work. An employer who knowingly uses an unlicensed operator faces separate penalties.',
            },
            {
              question: 'Your 2A license expired last month. You need the income and plan to "renew next week." Can you legally operate an excavator today?',
              options: [
                'Yes, there is a 30-day grace period after expiration',
                'Yes, as long as you have proof that your renewal application was submitted',
                'No, operating with an expired license violates MGL §53',
                'Yes, if your employer signs a waiver of liability',
              ],
              correctIndex: 2,
              explanation: 'An expired license is an invalid license. There is no grace period that permits continued operation. Operating with an expired 2A license subjects both you and your employer to civil penalties of up to $500 per day.',
            },
            {
              question: 'MGL §65 governs which aspect of the hoisting licensing process?',
              options: [
                'Penalty amounts for unlicensed operation',
                'Accident reporting requirements',
                'Operator examination and qualification standards',
                'Equipment inspection schedules',
              ],
              correctIndex: 2,
              explanation: 'MGL §65 covers the examination and qualification standards — it is the legal basis for requiring operators to pass a written or practical exam and meet experience/training criteria before receiving a license.',
            },
            {
              question: 'A general contractor tells an unlicensed worker to operate an excavator "just for the afternoon." What is the legal consequence?',
              options: [
                'No consequence if no accident occurs',
                'The worker faces a verbal warning only',
                'Both the worker and the contractor can face civil penalties under MGL §53',
                'Only the contractor faces penalties; workers are protected from individual liability',
              ],
              correctIndex: 2,
              explanation: 'MGL §53 creates liability for both the person operating without a license and the employer who directs or permits that operation. "Just for the afternoon" does not reduce the penalty — each day of unlicensed operation is a separate violation.',
            },
          ],
        },
      ],
    },
    {
      id: '2a-m2',
      title: 'Equipment Systems & Components',
      orderInCourse: 2,
      estimatedHours: 5,
      sessions: [
        {
          id: '2a-m2-s1',
          title: 'Excavator & Track Hoe Anatomy',
          durationHours: 2,
          learningObjectives: [
            'Identify and name the major structural components of a crawler excavator',
            'Explain the function of the boom, stick (arm), and bucket',
            'Describe the undercarriage system and its maintenance checkpoints',
            'Explain the slew ring and how 360° rotation is achieved',
          ],
          topics: [
            'Upperstructure vs. undercarriage: the two main assemblies',
            'Boom: the main lifting arm attached to the upperstructure',
            'Stick (dipper arm): connects boom to bucket; controls reach',
            'Bucket: cutting edge, teeth, side cutters, mounting ears',
            'Hydraulic cylinders: boom cylinder, stick cylinder, bucket cylinder',
            'Slew ring (swing bearing): allows 360° rotation of upperstructure',
            'Slew motor: hydraulic motor powering the swing',
            'Track frame and undercarriage: sprockets, rollers, idlers, track links',
            'Track tension adjustment: too loose = derailment; too tight = premature wear',
            'Cab: ROPS/FOPS protection, seat, controls, visibility considerations',
            'Counterweight: cast iron block at rear; balances boom loads',
            'Quick coupler attachments: thumbs, augers, compactors, hydraulic hammers',
          ],
          resources: [
            {
              label: 'Excavator Component Reference — Anatomy, Hydraulics & Inspection',
              url: '/reference/excavator-anatomy',
              type: 'reference',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'What component allows an excavator\'s upperstructure to rotate 360 degrees independently of the tracks?',
              options: [
                'The swing motor alone',
                'The slew ring (swing bearing) driven by the slew motor',
                'The track drive sprockets',
                'The hydraulic pump',
              ],
              correctIndex: 1,
              explanation: 'The slew ring is a large bearing that connects the upperstructure to the undercarriage. The hydraulic slew motor drives the rotation. Both must be inspected for cracks and proper lubrication.',
            },
            {
              question: 'During a pre-shift inspection, you notice cracks at the mounting ears of the bucket. What should you do?',
              options: [
                'Monitor the cracks throughout the shift',
                'Weld the cracks before operating',
                'Remove the machine from service immediately',
                'Reduce dig depth to reduce stress on the bucket',
              ],
              correctIndex: 2,
              explanation: 'Cracks at bucket mounting ears indicate imminent catastrophic failure. Small cracks expand rapidly under load stress. The machine must be removed from service and repaired by qualified personnel before resuming operation.',
            },
            {
              question: 'What is the risk of running excavator tracks that are too tight?',
              options: [
                'Track derailment',
                'Premature wear on sprockets, rollers, and track links',
                'Reduced digging force',
                'Hydraulic system overpressure',
              ],
              correctIndex: 1,
              explanation: 'Tracks that are too tight accelerate wear on sprockets, idlers, and track links, leading to costly early replacement. Tracks that are too loose risk derailment. Correct tension per the manufacturer\'s spec is critical.',
            },
            {
              question: 'What is the primary purpose of the counterweight on a crawler excavator?',
              options: [
                'To protect the rear of the machine from collision damage',
                'To counterbalance boom and load weight during operation',
                'To provide ballast for traveling on steep slopes',
                'To house the hydraulic reservoir and cooling system',
              ],
              correctIndex: 1,
              explanation: 'The counterweight is a heavy cast-iron block at the rear of the upperstructure. Its sole purpose is to counterbalance the weight of the boom, stick, bucket, and any load, preventing the machine from tipping forward. Never operate with a missing or damaged counterweight.',
            },
            {
              question: 'What are "mounting ears" on an excavator bucket?',
              options: [
                'The protective rubber guards on the bucket sides',
                'The steel plates with pin holes that attach the bucket to the stick',
                'Wear pads on the bottom of the bucket',
                'Hydraulic fittings for thumb attachments',
              ],
              correctIndex: 1,
              explanation: 'Mounting ears are the reinforced steel plates on the back of the bucket through which the attachment pins pass to connect the bucket to the stick. Cracks at the mounting ears are a removal-from-service condition because they indicate the bucket could separate under load.',
            },
            {
              question: 'Which component directly converts hydraulic pressure into the linear force that moves the boom up and down?',
              options: [
                'The slew motor',
                'The track drive motor',
                'The boom hydraulic cylinder',
                'The main hydraulic pump',
              ],
              correctIndex: 2,
              explanation: 'Hydraulic cylinders convert fluid pressure into linear (pushing/pulling) force. The boom cylinder extends to raise the boom and retracts to lower it. Separate cylinders control the stick and bucket.',
            },
            {
              question: 'What is the purpose of the stick (dipper arm) on an excavator?',
              options: [
                'It houses the hydraulic pump and motor',
                'It connects the boom to the bucket and controls digging reach and depth',
                'It is the structural member that supports the counterweight',
                'It drives the track sprockets for propulsion',
              ],
              correctIndex: 1,
              explanation: 'The stick (also called the dipper arm or arm) connects the end of the boom to the bucket. Extending the stick increases reach; retracting it increases digging force and depth. The stick cylinder controls this movement.',
            },
            {
              question: 'During a pre-shift inspection, you find the track has come partially off the sprocket on one side. What is the correct action?',
              options: [
                'Operate slowly to the nearest level area, then re-tension the track',
                'Tag the machine out of service and notify a mechanic',
                'Reverse the machine to reseat the track',
                'Reduce bucket load and complete the shift',
              ],
              correctIndex: 1,
              explanation: 'A derailed or partially derailed track is a mechanical failure requiring repair before operation. Operating on a partially tracked machine risks complete derailment, loss of control, and machine rollover. Tag out and call for service.',
            },
          ],
        },
        {
          id: '2a-m2-s2',
          title: 'Skid Steer Loader Systems & ROPS/FOPS',
          durationHours: 1.5,
          learningObjectives: [
            'Identify the major components of a skid steer loader',
            'Explain the ROPS and FOPS requirements for skid steers and when each standard applies',
            'Describe the primary hazards unique to skid steer operation',
            'State the seat belt and reverse alarm requirements under 29 CFR 1926.602',
          ],
          topics: [
            'Skid steer vs. excavator: key operational differences',
            'Lift arms: radial vs. vertical lift path; how to choose the right machine',
            'Attachment system: universal quick-attach plate; approved vs. unapproved attachments',
            'Drive system: independent wheel drive on each side for skid steering',
            'ROPS (Rollover Protective Structure) requirements',
            'Pre-July 15 2019: SAE J320a, J394, J395, J396, J397 or ISO 3471:2008',
            'Post-July 15 2019: ISO 3471:2008 required (unified standard)',
            'FOPS (Falling Object Protective Structure): required when overhead hazard present',
            'ROPS/FOPS modification or structural damage = immediate removal from service',
            'Seat belt requirement: SAE J386-1969 standard; mandatory with ROPS',
            'Reverse signal alarm: required when operator\'s view to rear is obstructed (1926.602)',
            'Scissor point guarding on loader arms (1926.602)',
            'Rollover risk: primary hazard on slopes and soft ground',
            'Pinching hazards: between lift arms and attachment frame during lowering',
          ],
          resources: [
            {
              label: 'Skid Steer Systems — ROPS/FOPS & Hazards Reference',
              url: '/reference/2a-m2-s2',
              type: 'reference',
              required: true,
            },

            {
              label: '29 CFR 1926.1001 — ROPS for material handling equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1001',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA SHIB — Skid Steer Loader Safety Hazards (PDF)',
              url: 'https://www.osha.gov/sites/default/files/publications/SHIB011209.pdf',
              type: 'osha',
              required: false,
            },
            {
              label: 'OSHA SHIB — Skid Steer Loader Hazards',
              url: 'https://www.osha.gov/sites/default/files/publications/shib011209.pdf',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'A skid steer loader manufactured in 2022 must meet which ROPS standard?',
              options: [
                'SAE J320a',
                'SAE J394',
                'ISO 3471:2008',
                'Either SAE J395 or ISO 3471:2008',
              ],
              correctIndex: 2,
              explanation: 'Equipment manufactured after July 15, 2019 must meet ISO 3471:2008 — the unified international ROPS standard. Older SAE standards (J320a, J394, J395, J396, J397) only apply to equipment manufactured before that date.',
            },
            {
              question: 'Under OSHA 29 CFR 1926.602, when is a reverse signal alarm required on a skid steer?',
              options: [
                'Always, regardless of visibility',
                'Only when operating at night',
                'When the operator\'s view to the rear is obstructed',
                'Only when reversing over 5 mph',
              ],
              correctIndex: 2,
              explanation: 'OSHA 1926.602(a)(6) requires an audible reverse alarm when the operator\'s rear view is obstructed. Alternatively, a designated employee must signal it is safe to back up. Most skid steer cabs obstruct the rear view, making a backup alarm effectively mandatory.',
            },
            {
              question: 'An operator drops a skid steer into a shallow ditch and the ROPS shows a visible bend. What is the required action?',
              options: [
                'Straighten the bend and return to service',
                'Mark the damage and report it at the end of the shift',
                'Remove the machine from service immediately — damaged ROPS cannot protect the operator',
                'Have the site safety officer evaluate whether the ROPS is still functional',
              ],
              correctIndex: 2,
              explanation: 'Any structural damage or modification to a ROPS requires immediate removal from service. A bent ROPS has unknown residual strength — it cannot reliably protect the operator in a subsequent rollover. Only a manufacturer-approved rebuild restores certification.',
            },
            {
              question: 'Where are "scissor points" on a skid steer, and why must they be guarded?',
              options: [
                'At the bucket attachment; they can pinch the load',
                'Between the lift arms and the front frame; they can amputate fingers and hands during arm lowering',
                'At the drive axles; they can catch loose clothing',
                'Behind the cab; they are the hinge points for the rear door',
              ],
              correctIndex: 1,
              explanation: 'Scissor points are the areas where the lift arms and front frame come together as the arms are lowered. OSHA 1926.602 requires guards at all scissor points that create a hazard to the operator or bystanders. Unguarded scissor points are a commonly cited OSHA violation.',
            },
            {
              question: 'What is the primary rollover hazard for a skid steer loader?',
              options: [
                'High center of gravity combined with soft or sloped ground',
                'Excessive hydraulic pressure in the lift circuit',
                'Spinning out during tight turns on pavement',
                'Forward tipping when the bucket is lowered',
              ],
              correctIndex: 0,
              explanation: 'Skid steers have a relatively high center of gravity compared to their short wheelbase. Soft, sloped, or uneven ground reduces their stability dramatically. Never operate a skid steer on slopes that exceed the manufacturer\'s rated angle.',
            },
            {
              question: 'A worker standing near a skid steer is struck by the descending lift arm. Which hazard category does this represent?',
              options: [
                'Struck-by hazard from a swinging load',
                'Pinch/crush hazard from the lift arm',
                'Caught-in hazard at the scissor point',
                'Struck-by hazard from equipment travel',
              ],
              correctIndex: 2,
              explanation: 'Being caught between the lift arm and the frame as the arm descends is a caught-in/between hazard at the scissor point. This is distinct from a simple struck-by incident — the person is trapped and crushed rather than hit by a moving object.',
            },
            {
              question: 'The load capacity plate on a skid steer has been removed or is unreadable. What must you do?',
              options: [
                'Estimate the capacity based on machine size and use it conservatively',
                'Do not operate the machine until the plate is replaced',
                'Use the previous operator\'s recollection of the rated capacity',
                'Reduce all loads to 50% as a safety margin',
              ],
              correctIndex: 1,
              explanation: 'OSHA requires load capacity to be clearly displayed. An unreadable or missing plate means the operator has no way to verify the rated capacity — operating without this information risks overloading the machine and causing a tip-over. The machine must be taken out of service.',
            },
          ],
        },
        {
          id: '2a-m2-s3',
          title: 'Hydraulic Systems — Safety & Inspection',
          durationHours: 1.5,
          learningObjectives: [
            'Explain hydraulic pressure hazards specific to excavating equipment',
            'Identify the correct method to check for hydraulic leaks safely',
            'Describe the minimum hydraulic hose safety factor requirement',
            'Recognize signs of hydraulic fluid contamination',
          ],
          topics: [
            'Hydraulic pressure in excavators: systems routinely exceed 2,000 psi',
            'Hydraulic injection injury: high-pressure fluid can penetrate skin and cause amputation/death',
            'Correct leak detection: use cardboard or a mirror — NEVER your bare hand',
            'Minimum hose safety factor: 4:1 burst pressure to maximum working pressure',
            'Pressure trapping in hoses: always depressurize before disconnecting',
            'Fluid condition: amber/red = good; milky = water contamination; dark/burnt = overheating',
            'Filter locations: reservoir, return line, case drain; inspect and replace per manufacturer schedule',
            'Hot oil spray hazard: burst hose under pressure causes severe burn injuries',
            'Hose routing inspection: avoid sharp bends, pinch points, and contact with moving parts',
            'Hose removal-from-service criteria: bulges, cracks, abrasion through outer cover, leaking fittings',
          ],
          resources: [
            {
              label: 'Hydraulic Systems — Safety & Inspection Reference',
              url: '/reference/2a-m2-s3',
              type: 'reference',
              required: true,
            },

            {
              label: '29 CFR 1926.602 — Material handling & earthmoving equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'You suspect a hydraulic hose is leaking but cannot see fluid. How should you locate the leak?',
              options: [
                'Run your hand slowly along the hose to feel for moisture',
                'Hold a rag against the hose while the machine operates',
                'Use a piece of cardboard to catch fluid spray from a safe distance',
                'Pressurize the system fully and observe through the cab window',
              ],
              correctIndex: 2,
              explanation: 'NEVER use your hand to find hydraulic leaks. High-pressure fluid can inject into skin at pressures that penetrate flesh without leaving an obvious wound — leading to amputation or death. Cardboard (or a mirror) detects the spray safely from a distance.',
            },
            {
              question: 'What is the minimum burst-pressure safety factor required for hydraulic hoses on construction equipment?',
              options: ['2:1', '3:1', '4:1', '6:1'],
              correctIndex: 2,
              explanation: 'OSHA and industry standards require hydraulic hoses to have a minimum 4:1 safety factor — meaning a hose rated for 3,000 psi working pressure must burst at no less than 12,000 psi. Hoses that fail this standard must be replaced.',
            },
            {
              question: 'Your excavator\'s hydraulic fluid appears milky white rather than its normal amber color. What does this indicate?',
              options: [
                'Normal appearance after adding fresh fluid',
                'Water contamination in the hydraulic system',
                'The fluid is at optimal operating temperature',
                'Excessive air in the hydraulic circuit',
              ],
              correctIndex: 1,
              explanation: 'Milky hydraulic fluid indicates water contamination, which can occur from a failed cylinder seal, a cracked cooler, or condensation. Water in hydraulic fluid causes cavitation, rust, and seal deterioration. The system must be serviced before operation.',
            },
            {
              question: 'What immediate danger does a hydraulic injection injury pose?',
              options: [
                'Surface burns that heal within a few days',
                'Fluid absorption through the skin causing nausea',
                'High-pressure fluid penetrating the skin, causing internal damage requiring emergency surgery — often resulting in amputation',
                'Skin irritation from hydraulic additives',
              ],
              correctIndex: 2,
              explanation: 'Hydraulic injection injuries look minor (small entry wound) but are life-threatening. Fluid injected under high pressure spreads through tissue causing necrosis. The injury requires emergency surgery and often results in amputation of the affected limb. Any suspected injection injury is a medical emergency.',
            },
            {
              question: 'Before disconnecting a hydraulic hose from an excavator, what must you do first?',
              options: [
                'Wear rubber gloves for insulation',
                'Depressurize the hydraulic circuit',
                'Cool the system by idling the engine for 5 minutes',
                'Nothing — quick-connect fittings auto-release safely',
              ],
              correctIndex: 1,
              explanation: 'Hydraulic circuits remain pressurized even after the engine is shut off. Always relieve pressure per the manufacturer\'s procedure before disconnecting any hose or fitting. Failing to depressurize can cause the fitting to blow off with lethal force.',
            },
            {
              question: 'A hydraulic hose on your excavator has a visible bulge in the middle. The hose is not yet leaking. What should you do?',
              options: [
                'Wrap the bulge with duct tape to reinforce it',
                'Monitor it during the shift and replace at end of day',
                'Remove the machine from service — a bulging hose indicates imminent failure',
                'Reduce operating pressure and continue working',
              ],
              correctIndex: 2,
              explanation: 'A bulge indicates the hose\'s inner wire reinforcement has failed. The outer cover is holding the pressure — temporarily. Hose failure under excavator pressures (2,000+ psi) causes explosive fluid release that can injure bystanders and cause equipment runaway.',
            },
            {
              question: 'Which of the following is NOT considered hydraulic fluid contamination?',
              options: [
                'Water mixed into the fluid',
                'Metal particles from internal wear',
                'The fluid being warmer than usual after heavy work',
                'Dirt particles entering through an improperly sealed fill cap',
              ],
              correctIndex: 2,
              explanation: 'Fluid temperature rising during heavy work is normal — hydraulic systems generate heat. Water, metal particles, and dirt are all forms of contamination that degrade the fluid and damage pumps, valves, and cylinders.',
            },
          ],
        },
      ],
    },
    {
      id: '2a-m3',
      title: 'Safe Operation & Inspections',
      orderInCourse: 3,
      estimatedHours: 5,
      sessions: [
        {
          id: '2a-m3-s1',
          title: 'Pre-Shift Inspection — Excavators & Skid Steers',
          durationHours: 2,
          learningObjectives: [
            'Conduct a systematic 360° pre-shift inspection of excavating equipment',
            'Identify conditions that require immediate removal from service',
            'Explain the OSHA basis for pre-shift inspections',
            'Complete a proper inspection in 10–15 minutes',
          ],
          topics: [
            'OSHA basis: 29 CFR 1926.20 and 1926.600 — "frequent and regular" inspections by a competent person',
            'Timing: before each shift and after each machine relocation',
            '360° walk-around: start at a fixed point and work around the entire machine',
            'Walk-around checks: leaks under the machine, structural damage, ground conditions',
            'Fluid levels: engine oil, hydraulic fluid (level and color), coolant, fuel',
            'Hydraulic hose inspection: damage, kinks, chafing, cracked outer cover, leaking fittings',
            'Undercarriage (excavators): track tension, roller condition, sprocket wear, pin security',
            'Boom, stick, bucket: structural cracks, weld seam integrity, tooth wear and security',
            'Skid steer lift arms: hydraulic cylinder pins, arm pivot bolts, scissor point guards',
            'Cab safety items: seat belt function, mirror alignment, windows (no cracks blocking visibility)',
            'Operational checks: horn, backup alarm, all controls responsive, brakes hold under load',
            'Fire extinguisher: present, mounted securely, charged (pin and gauge)',
            'Immediate removal-from-service conditions (no exceptions):',
            '  — Active hydraulic leak from any hose or fitting',
            '  — Non-functional brakes or steering',
            '  — Damaged or modified ROPS/FOPS',
            '  — Non-functional seat belt',
            '  — Structural cracks in boom, stick, or bucket mounting ears',
            '  — Non-functional horn or backup alarm',
            '  — Missing or discharged fire extinguisher',
          ],
          resources: [
            {
              label: 'Pre-Shift Inspection Reference & Checklist',
              url: '/reference/2a-m3-s1',
              type: 'reference',
              required: true,
            },

            {
              label: '29 CFR 1926.600 — Equipment safety general',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.600',
              type: 'osha',
              required: true,
            },
            {
              label: '29 CFR 1926.602 — Material handling & earthmoving equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'During pre-shift inspection, you find the seat belt latch is broken. The job is urgent. What is the correct action?',
              options: [
                'Use the machine carefully at reduced speed until the part arrives',
                'Tie the belt in a knot as a temporary fix',
                'Tag the machine out of service and notify your supervisor',
                'Operate only in low-risk areas until repairs are made',
              ],
              correctIndex: 2,
              explanation: 'A non-functional seat belt is a removal-from-service condition with no exceptions. ROPS protection only works if the operator is restrained inside the cab during a rollover. Operating without a working seat belt violates OSHA 1926.602 and 230 CMR 6.00.',
            },
            {
              question: 'What is the primary OSHA regulation that requires pre-shift inspections of excavating equipment?',
              options: [
                '29 CFR 1926.550',
                '29 CFR 1926.650',
                '29 CFR 1926.600 and 1926.20',
                '29 CFR 1910.178',
              ],
              correctIndex: 2,
              explanation: '29 CFR 1926.20 requires employers to establish safety programs, and 1926.600 specifically requires frequent and regular inspections of construction equipment by a competent person. Together they form the basis for daily pre-shift inspections.',
            },
            {
              question: 'When should a pre-shift inspection be performed after moving an excavator to a new location on the same day?',
              options: [
                'Only at the start of the shift; no additional inspection needed',
                'After each machine relocation, before resuming work',
                'At the end of the day to document the condition',
                'Only if the move involved traveling more than one mile',
              ],
              correctIndex: 1,
              explanation: 'OSHA requires inspections before each shift AND after each machine move. New ground conditions, travel damage, and changed environmental factors all create new hazards that must be assessed before resuming digging.',
            },
            {
              question: 'You notice engine oil dripping from under an excavator during pre-shift inspection. The level is slightly low but the machine runs normally. What is the correct action?',
              options: [
                'Top off the oil and operate, monitoring the level throughout the shift',
                'Tag the machine out of service — active oil leaks indicate a mechanical defect',
                'Use the machine until the oil level reaches the "add" mark, then stop',
                'Note the leak in the inspection log and notify the foreman at the end of the day',
              ],
              correctIndex: 1,
              explanation: 'An active engine oil leak is a mechanical defect that must be repaired before operation. Operating with a known leak can lead to sudden engine seizure, fire risk, and environmental contamination. The machine must be tagged out and the leak repaired.',
            },
            {
              question: 'Which of the following is NOT on the list of immediate removal-from-service conditions for excavating equipment?',
              options: [
                'Non-functional seat belt',
                'A boom hydraulic cylinder with a slow external seep',
                'Structural crack in the stick',
                'Non-functional backup alarm on a skid steer',
              ],
              correctIndex: 1,
              explanation: 'A slow external seep from a cylinder rod seal is a defect that requires repair but may not immediately prevent operation depending on its severity — this is a judgment call for the competent person. The others (seat belt, structural cracks, non-functional backup alarm) are all unambiguous removal-from-service conditions.',
            },
            {
              question: 'What is the correct sequence for a pre-shift walk-around inspection of an excavator?',
              options: [
                'Start with the cab interior, then check the engine, then check the undercarriage',
                'Start at any fixed reference point and move consistently around the entire machine in one direction',
                'Spot-check whatever areas you can see easily from the ground',
                'Begin with fluid levels every time — they are the most critical items',
              ],
              correctIndex: 1,
              explanation: 'Starting at a fixed point and moving consistently around the machine ensures nothing is missed. Random spot checks are prone to skipping items. The walk-around method is the industry-standard approach for systematic pre-shift inspections.',
            },
            {
              question: 'The fire extinguisher on an excavator has a gauge reading in the red zone. What action is required?',
              options: [
                'The machine can continue to operate — fire extinguishers are supplemental safety items',
                'Note it in the log and replace the extinguisher during the next scheduled service',
                'Remove the machine from service — a discharged or low-pressure extinguisher is a removal-from-service condition',
                'Operate with reduced speed near potential ignition sources',
              ],
              correctIndex: 2,
              explanation: 'A fire extinguisher in the red zone is discharged or low-pressure and will not work in an emergency. A working, accessible fire extinguisher is required to be present on the machine at all times — its absence or failure is a removal-from-service condition.',
            },
            {
              question: 'During a pre-shift inspection of a skid steer, you find the backup alarm makes no sound when you engage reverse. The machine runs fine otherwise. Can you operate it?',
              options: [
                'Yes, assign a spotter to stand behind the machine during all reversing',
                'Yes, but only on job sites where reversing is not required',
                'No, a non-functional backup alarm is a removal-from-service condition',
                'Yes, if the site supervisor approves the work plan',
              ],
              correctIndex: 2,
              explanation: 'A non-functional backup alarm (when the operator\'s rear view is obstructed) is a removal-from-service condition. Note that OSHA does allow a designated spotter as an alternative to the alarm — but assigning a spotter retroactively to an already-operating machine does not satisfy the requirement. The machine must be fixed before resuming.',
            },
          ],
        },
        {
          id: '2a-m3-s2',
          title: 'OSHA Subpart P — Excavation Safety',
          durationHours: 2,
          learningObjectives: [
            'State the excavation depth threshold that requires a protective system',
            'Define "competent person" and list their inspection responsibilities',
            'Classify soil into Type A, B, or C using visual and manual tests',
            'Select the appropriate protective system for a given scenario',
          ],
          topics: [
            '29 CFR 1926.650–652: OSHA Subpart P — Excavations',
            'The 5-foot rule: excavations ≥5 ft deep ALWAYS require a protective system',
            'Exception under 5 ft: no system required ONLY IF competent person finds no cave-in hazard',
            'Competent person: can identify hazards, knows soils analysis, has authority to stop work',
            'Competent person inspection: required before work begins and "as needed" throughout shift',
            'Post-event inspection: required after rain, freeze-thaw, or any event that may increase hazard',
            'Access and egress: trenches ≥4 ft require a stairway, ladder, or ramp within 25 lateral feet',
            'Soil Classification — Type A (most stable):',
            '  — Unconfined compressive strength ≥1.5 tsf (144 kPa)',
            '  — Examples: hard clay, silty clay, caliche, hardpan',
            '  — DISQUALIFIERS: fissured, subject to vibration, previously disturbed, sloped layer',
            'Soil Classification — Type B:',
            '  — Strength 0.5–1.5 tsf (48–144 kPa)',
            '  — Examples: angular gravel, silt, previously disturbed Type A',
            'Soil Classification — Type C (least stable, most aggressive protection):',
            '  — Strength <0.5 tsf (<48 kPa)',
            '  — Examples: granular soils, submerged soils, layered systems dipping into excavation',
            'Testing methods: thumb penetration, dry strength, plasticity, visual for fissures',
            'Protective systems — four design options:',
            '  1. Sloping: Type A=¾:1 (53°), Type B=1:1 (45°), Type C=1½:1 (34°)',
            '  2. Manufacturer tabulated data (written documentation required)',
            '  3. OSHA appendix tables',
            '  4. Professional engineer design',
            'Trench box (shield): portable, must resist cave-in forces; remove bottom-up with simultaneous backfill',
            'Spoil pile setback: minimum 2 feet from trench edge',
            'Water accumulation: must be controlled; submerged soils default to Type C',
          ],
          resources: [
            {
              label: 'OSHA Subpart P — Excavation Safety Reference',
              url: '/reference/2a-m3-s2',
              type: 'reference',
              required: true,
            },

            {
              label: '29 CFR 1926.650 — Excavations: scope and definitions',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.650',
              type: 'osha',
              required: true,
            },
            {
              label: '29 CFR 1926.651 — Specific excavation requirements',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.651',
              type: 'osha',
              required: true,
            },
            {
              label: '29 CFR 1926.652 — Protective systems',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.652',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA Subpart P Appendix A — Soil Classification',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926SubpartPAppA',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA Excavation Training Materials (OSHA 2226)',
              url: 'https://www.osha.gov/sites/default/files/publications/OSHA2226.pdf',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'At exactly what excavation depth does OSHA Subpart P require a protective system with NO exceptions?',
              options: ['3 feet', '4 feet', '5 feet', '6 feet'],
              correctIndex: 2,
              explanation: 'At 5 feet or deeper, a protective system is ALWAYS required — period. Between 0 and 5 feet, no system is required only if the competent person determines no cave-in hazard exists. The 5-foot threshold is one of the most commonly tested numbers on the MA hoisting exam.',
            },
            {
              question: 'Soil testing shows an unconfined compressive strength of 0.8 tsf, the soil has been previously disturbed, and there is standing water at the bottom. How should this soil be classified?',
              options: ['Type A', 'Type B', 'Type C', 'Stable Rock'],
              correctIndex: 2,
              explanation: 'Water accumulation automatically downgrades soil to Type C, regardless of strength. Even though 0.8 tsf would normally indicate Type B, the presence of water in the trench bottom requires the most conservative classification.',
            },
            {
              question: 'What is the minimum required spoil pile setback from the edge of an open trench?',
              options: ['1 foot', '2 feet', '3 feet', '4 feet'],
              correctIndex: 1,
              explanation: 'OSHA 1926.651 requires spoil, equipment, and materials to be kept at least 2 feet from the edge of any excavation. Spoil closer than 2 feet adds surcharge load that can trigger a cave-in.',
            },
            {
              question: 'A competent person inspects a trench before work begins and finds no hazards. Rain begins during the shift. What must happen?',
              options: [
                'Continue work; the initial inspection covers the full shift',
                'Inspect again only if the rain lasts more than 30 minutes',
                'Remove workers from the trench and re-inspect before resuming',
                'Reduce the trench depth by one foot and continue',
              ],
              correctIndex: 2,
              explanation: 'OSHA requires the competent person to inspect "as needed throughout the shift" and specifically after any rain, freeze-thaw cycle, or other event that may increase hazard. Workers must exit the trench during re-inspection.',
            },
            {
              question: 'A trench is 4 feet deep. Workers need to enter it. Is a ladder or egress point required?',
              options: [
                'No — ladders are only required at 5 feet or deeper',
                'No — the 4-foot depth does not trigger egress requirements',
                'Yes — egress is required for any trench 4 feet deep or deeper',
                'Yes — but only if the worker will be in the trench for more than 30 minutes',
              ],
              correctIndex: 2,
              explanation: 'OSHA 1926.651 requires a means of egress (ladder, stairway, or ramp) for any trench 4 feet or deeper. This is a separate threshold from the protective system requirement (5 feet). Workers must be within 25 feet lateral travel of the egress point.',
            },
            {
              question: 'Unconfined compressive strength testing shows 1.2 tsf. The soil is fissured. How must it be classified?',
              options: [
                'Type A — 1.2 tsf exceeds the 1.0 tsf threshold for Type A',
                'Type B — 1.2 tsf falls in the Type B range and fissuring requires downgrade from Type A',
                'Type C — fissuring is an automatic downgrade to Type C',
                'Stable Rock — strength above 1.0 tsf qualifies as stable',
              ],
              correctIndex: 1,
              explanation: 'Although 1.2 tsf is between 0.5 and 1.5 tsf (the Type B range), the key issue is that fissured soil cannot be classified as Type A even if it exceeds 1.5 tsf. Fissuring is an explicit disqualifier for Type A. The 1.2 tsf strength puts it squarely in Type B territory.',
            },
            {
              question: 'What is the minimum required horizontal-to-vertical slope ratio for a Type B soil excavation?',
              options: ['¾:1 (53°)', '1:1 (45°)', '1½:1 (34°)', '2:1 (27°)'],
              correctIndex: 1,
              explanation: 'Type B soil requires a minimum 1:1 slope — 1 foot horizontal for every 1 foot of vertical depth. Type A allows ¾:1 and Type C requires 1½:1. Memorize these three ratios: they are tested on the 2A exam.',
            },
            {
              question: 'Who qualifies as a "competent person" for excavation purposes under OSHA Subpart P?',
              options: [
                'Any licensed hoisting engineer',
                'A person capable of identifying cave-in hazards, trained in soils analysis, and with authority to correct hazards',
                'A professional engineer registered in Massachusetts',
                'The most senior worker on the job site',
              ],
              correctIndex: 1,
              explanation: 'OSHA defines a competent person as someone who can identify existing and predictable hazards, is knowledgeable in applicable soil analysis, protective systems, and regulations, and has the authority to take prompt corrective action. A PE is needed only for engineer-designed protective systems.',
            },
            {
              question: 'You are digging a trench in Type C soil and reach a depth of 6 feet. Which protective system is NOT an option under OSHA Subpart P?',
              options: [
                'Sloping at 1½:1 ratio',
                'Installing a manufacturer-approved trench box',
                'Shoring with tabulated data',
                'Relying on the fact that no workers will enter the trench',
              ],
              correctIndex: 3,
              explanation: 'The protective system requirement at 5 feet or deeper applies to the excavation itself — not just when workers are in the trench. An operator positioned at the edge of an unprotected 6-foot trench while working is also protected by Subpart P requirements.',
            },
            {
              question: 'What is the correct procedure when removing a trench box from a completed trench?',
              options: [
                'Remove the box completely, then backfill from the bottom',
                'Remove the box from the bottom upward while simultaneously backfilling to maintain protection',
                'Backfill completely to the top, then pull the box straight out',
                'Leave the box in place and bury it with the backfill to save time',
              ],
              correctIndex: 1,
              explanation: 'OSHA requires trench boxes to be removed from the bottom upward, with backfill placed simultaneously to maintain cave-in protection for any workers still finishing up at the trench. Removing the box entirely before backfilling exposes workers to a cave-in.',
            },
          ],
        },
        {
          id: '2a-m3-s3',
          title: 'Operating Hazards — SAE Hand Signals & Site Safety',
          durationHours: 1,
          learningObjectives: [
            'Demonstrate the 8 standard SAE hand signals required by 230 CMR 6.00',
            'Identify operating hazards specific to excavating equipment',
            'Explain utility location requirements before digging',
            'Apply swing radius and exclusion zone rules on a job site',
          ],
          topics: [
            'SAE J1307-2023: the standard hand signal set required by MA 230 CMR 6.00',
            'Key hand signals: Raise/Boom Up, Lower/Boom Down, Swing, Travel, Stop, Emergency Stop, Move Bucket In/Out',
            'Emergency STOP signal: crossed arms across chest — all operators must respond immediately',
            'Signaler positioning: must be visible to operator at all times; never in swing radius',
            'Utility location (Dig Safe): call 811 before any digging — required by MA law',
            'Swing radius exclusion zone: no persons in the full working radius during operation',
            'Trench edge proximity: do not position tracks within 2x the trench depth from edge',
            'Prohibition on straddling open trenches (230 CMR 6.00)',
            'Electrocution hazard: maintain minimum 10-foot clearance from energized overhead lines',
            'Excavator stability: avoid sudden stops during swing with a loaded bucket',
            'Slope operation: position boom downhill when possible for stability',
            'Blind swing areas: use spotters; use mirrors and cameras but never rely on them alone',
          ],
          resources: [
            {
              label: 'Hand Signals, Site Safety & Hazards Reference',
              url: '/reference/2a-m3-s3',
              type: 'reference',
              required: true,
            },

            {
              label: '230 CMR 6.00 — Hand signal requirements',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'SAE J1307 Hand Signals — Quick Reference Guide',
              url: '/hand-signals',
              type: 'reference',
              required: true,
            },
            {
              label: 'Dig Safe — Massachusetts 811 call-before-you-dig',
              url: 'https://digsafe.com',
              type: 'reference',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'What is the universal Emergency STOP hand signal recognized under SAE J1307?',
              options: [
                'One hand raised with palm facing out',
                'Both arms raised above the head',
                'Crossed arms held in front of the chest',
                'Rapid up-and-down motion with one hand',
              ],
              correctIndex: 2,
              explanation: 'Crossed arms across the chest is the universally recognized Emergency STOP signal. Every operator on site must respond immediately to this signal — there are no exceptions and no delays are acceptable.',
            },
            {
              question: 'Before digging on any Massachusetts job site, what must the operator or contractor do?',
              options: [
                'Call 811 (Dig Safe) and wait for utility locations to be marked',
                'Check the property deed for any listed easements',
                'Notify the local police department of excavation plans',
                'Nothing additional is required if the site plan shows no utilities',
              ],
              correctIndex: 0,
              explanation: 'Massachusetts law requires calling 811 (Dig Safe) before any excavation. Utilities must be located and marked before digging begins — failure to call before you dig can result in fines, liability for damage, and worker fatalities from struck utilities.',
            },
            {
              question: 'What is the minimum clearance an excavator must maintain from energized overhead power lines?',
              options: ['5 feet', '8 feet', '10 feet', '15 feet'],
              correctIndex: 2,
              explanation: 'OSHA requires a minimum 10-foot clearance from energized overhead lines at voltages up to 50kV. Higher voltages require greater clearance. If the excavator cannot maintain 10 feet, the utility must be de-energized or insulated before work begins.',
            },
            {
              question: 'The signaler for your excavator steps away to answer a radio call, leaving no one visible to direct you. You still have digging to complete. What should you do?',
              options: [
                'Continue working carefully until the signaler returns',
                'Ask a nearby worker to take over signaling',
                'Stop all machine movement until the designated signaler returns',
                'Use the horn to signal your intentions and proceed',
              ],
              correctIndex: 2,
              explanation: '230 CMR 6.00 requires an approved signaler who is visible to the operator at all times. If the signaler is unavailable or not visible, all movement must stop. An informal substitute is not permitted — only the designated, approved signaler may direct the operator.',
            },
            {
              question: 'How far should excavator tracks be positioned from the edge of an open trench?',
              options: [
                'At least 2 feet from the edge',
                'At a distance no less than twice the depth of the trench',
                'At the edge is acceptable if tracks are on solid ground',
                'No minimum distance — the competent person judges each situation',
              ],
              correctIndex: 1,
              explanation: 'A commonly applied rule of thumb is to position tracks no closer than twice the depth of the trench from its edge. This prevents the machine\'s weight from adding surcharge load that could trigger a cave-in. Some references use 2 feet minimum, but the twice-depth rule is more protective on deeper excavations.',
            },
            {
              question: 'An excavator operator is swinging a loaded bucket when the signaler gives the Stop signal. What is the correct response?',
              options: [
                'Complete the current swing arc to a safe position, then stop',
                'Stop immediately, even mid-swing',
                'Slow down and finish lowering the bucket before stopping',
                'Acknowledge the signal and stop after the current task cycle',
              ],
              correctIndex: 1,
              explanation: 'A Stop signal requires an immediate halt to all movement. Completing the current arc or task cycle after receiving a Stop signal violates the signal protocol and could result in an injury. Only an Emergency Stop signal requires this level of immediate response, but the standard Stop signal is still an immediate command.',
            },
          ],
        },
      ],
    },
    {
      id: '2a-m4',
      title: 'OSHA Compliance & Exam Review',
      orderInCourse: 4,
      estimatedHours: 5,
      sessions: [
        {
          id: '2a-m4-s1',
          title: '29 CFR 1926.602 — Equipment Operation Requirements',
          durationHours: 2,
          learningObjectives: [
            'Apply OSHA 1926.602 rules for earthmoving equipment operation',
            'Explain access road requirements for construction equipment',
            'State the braking system standards for excavating equipment',
            'Describe the prohibition on unauthorized equipment modifications',
          ],
          topics: [
            '29 CFR 1926.602: the primary OSHA standard for earthmoving equipment',
            'Seat belts: SAE J386-1969 required on all equipment with ROPS',
            'Braking standards by equipment type:',
            '  — Loaders/dozers: SAE J237',
            '  — Graders: SAE J236',
            '  — Scrapers: SAE J319b',
            '  — High-speed equipment (>15 mph): SAE J321a fender requirements',
            'Access roads: employer must ensure roads are constructed and maintained to safely support equipment',
            'No modifications without written manufacturer approval — voids safety certifications (ROPS, load capacity)',
            'Front-end loader requirements: scissor point guarding, load capacity display, operator training',
            'Reverse signal alarm: required when rear view is obstructed; audible above ambient noise',
            'Alternative to alarm: designated employee signals safety before each backup movement',
            'Operator training requirement: operators must be trained per 1910.178(l) or equivalent',
            'Common violations: missing seat belts, no backup alarm, unguarded scissor points, unauthorized ROPS modifications',
          ],
          resources: [
            {
              label: '29 CFR 1926.602 — Equipment Operation Reference',
              url: '/reference/2a-m4-s1',
              type: 'reference',
              required: true,
            },

            {
              label: '29 CFR 1926.602 — Material handling & earthmoving equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'A skid steer operator wants to add a custom steel cab guard to improve visibility. The modification is not in the manufacturer\'s manual. What does OSHA require?',
              options: [
                'The modification is permitted if it does not reduce visibility',
                'Written manufacturer approval is required before any modification',
                'The modification must be approved by the site safety officer',
                'No approval is needed for non-structural modifications',
              ],
              correctIndex: 1,
              explanation: '29 CFR 1926.602 prohibits modifications without written manufacturer approval. Unauthorized modifications void ROPS/FOPS certifications, load ratings, and other safety certifications — even if the modification seems harmless.',
            },
            {
              question: 'Which SAE standard governs braking performance for loader and dozer equipment?',
              options: ['SAE J236', 'SAE J237', 'SAE J319b', 'SAE J386'],
              correctIndex: 1,
              explanation: 'SAE J237 covers braking for loaders and dozers. SAE J236 is for graders, J319b for scrapers, and J386 covers seat belt performance requirements.',
            },
            {
              question: 'Under OSHA 1926.602, what is the employer\'s responsibility regarding access roads used by construction equipment?',
              options: [
                'The employer must post speed limits on all access roads',
                'The employer must ensure access roads are constructed and maintained to safely support the equipment',
                'Access roads are the responsibility of the property owner, not the employer',
                'Access roads only need to meet requirements if workers travel on them on foot',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.602(a)(1) places direct responsibility on the employer to ensure that access roadways can safely support the equipment that will use them. An employer who routes a 70,000-pound excavator over an inadequate bridge or soft ground is in violation.',
            },
            {
              question: 'SAE J386-1969 governs which safety component on excavating equipment?',
              options: [
                'ROPS structural strength',
                'Seat belt performance',
                'Hydraulic hose pressure ratings',
                'Braking system stopping distance',
              ],
              correctIndex: 1,
              explanation: 'SAE J386-1969 is the seat belt standard referenced by OSHA 1926.602. It establishes the performance requirements that seat belts on ROPS-equipped equipment must meet. A seat belt that does not meet J386 is not compliant.',
            },
            {
              question: 'Your loader\'s service brakes can stop and hold the machine when empty, but not when the bucket is fully loaded. Is this compliant with OSHA?',
              options: [
                'Yes — braking systems only need to hold the machine when unloaded',
                'No — braking systems must stop and hold the machine at maximum rated load',
                'Yes — as long as the operator can use the parking brake as a backup',
                'Only non-compliant if the machine exceeds 5 mph',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.602 (via SAE J237) requires the service braking system to stop and hold the equipment at its fully rated load. A braking system that fails under load is a defect that requires repair before operation.',
            },
            {
              question: 'Which of the following represents a common OSHA 1926.602 citation on construction sites?',
              options: [
                'Operators wearing hard hats while in the cab',
                'Skid steers operating without scissor point guards',
                'Excavators traveling with the bucket raised for visibility',
                'Operators using hand signals instead of radio communication',
              ],
              correctIndex: 1,
              explanation: 'Missing or inadequate scissor point guarding on front-end loaders and skid steers is one of the most frequently cited violations under OSHA 1926.602. Guards must be in place whenever the machine is operated.',
            },
            {
              question: 'An operator installs a commercially available counterweight extension on an excavator to handle heavier loads. The extension was not specifically approved by the excavator manufacturer. Is this permitted?',
              options: [
                'Yes, if the extension was tested by an independent engineer',
                'Yes, as long as the total weight does not exceed the machine\'s rated capacity',
                'No — any modification requires written approval from the original equipment manufacturer',
                'Yes, if the site safety officer reviews and signs off on the modification',
              ],
              correctIndex: 2,
              explanation: 'OSHA 1926.602 and manufacturer standards prohibit any modification without the original manufacturer\'s written approval. Third-party testing or on-site sign-off does not substitute for OEM approval. Unauthorized counterweight additions can dangerously alter stability and void the machine\'s certifications.',
            },
          ],
        },
        {
          id: '2a-m4-s2',
          title: 'Practice Exam 1 — Regulations & Equipment',
          durationHours: 1.5,
          learningObjectives: [
            'Apply regulatory knowledge to scenario-based questions',
            'Distinguish between MGL, 230 CMR, and OSHA requirements',
            'Identify correct answers using process of elimination',
          ],
          topics: [
            'Exam strategy: read all options before selecting; eliminate clearly wrong answers first',
            'Critical numbers to memorize for the 2A exam:',
            '  — 70%: minimum passing score',
            '  — 60 days: wait after failed attempt',
            '  — 5 feet: Subpart P protective system threshold (no exceptions)',
            '  — 2 feet: minimum spoil pile setback from trench edge',
            '  — 25 feet: maximum lateral travel to egress from trench',
            '  — 4 feet: minimum trench depth requiring egress access point',
            '  — 1.5 tsf: Type A soil minimum strength',
            '  — 0.5 tsf: Type C soil maximum strength',
            '  — 2,000+ psi: typical excavator hydraulic system pressure',
            '  — 4:1: minimum hydraulic hose burst-to-working-pressure ratio',
            '  — 10 feet: minimum clearance from energized overhead power lines',
            '  — 2 feet: minimum distance between tracks and trench edge',
            'Common trick questions: "and" vs. "or" conditions; "always" vs. "unless"',
          ],
          resources: [
            {
              label: 'Practice Exam 1 — Critical Numbers & Strategy Reference',
              url: '/reference/2a-m4-s2',
              type: 'reference',
              required: true,
            },

            {
              label: 'MA OPSI — Hoisting exam content overview',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'A trench is being dug in Type C soil and is 7 feet deep. The contractor wants to slope the trench sides. What is the minimum required horizontal-to-vertical slope ratio for Type C soil?',
              options: ['¾:1', '1:1', '1½:1', '2:1'],
              correctIndex: 2,
              explanation: 'Type C soil — the least stable classification — requires a minimum 1½ horizontal to 1 vertical (1½:1) slope. This translates to a 34° angle. Type B requires 1:1 (45°), and Type A allows ¾:1 (53°).',
            },
            {
              question: 'Which of the following is NOT a manual test method used to classify soil per OSHA Subpart P Appendix A?',
              options: [
                'Thumb penetration test',
                'Dry strength test',
                'pH strip test',
                'Plasticity test',
              ],
              correctIndex: 2,
              explanation: 'OSHA Appendix A manual tests include thumb penetration, dry strength, plasticity, and visual inspection for fissures and layering. A pH test is not a soil classification method used in excavation safety.',
            },
            {
              question: 'An excavator operator is digging within 8 feet of overhead power lines. What must happen before work begins?',
              options: [
                'A spotter must be assigned',
                'The operator must be informed of the line voltage',
                'The utility must be de-energized or the work halted until safe clearance is established',
                'Work may proceed as long as the boom does not contact the lines',
              ],
              correctIndex: 2,
              explanation: 'OSHA requires a minimum 10-foot clearance from energized lines. At 8 feet, the operator is already inside the exclusion zone. The utility must be de-energized, relocated, or insulated before work can proceed. Working at 8 feet is a violation even with a spotter.',
            },
            {
              question: 'Which regulatory body administers the Massachusetts hoisting engineer exam?',
              options: [
                'OSHA (Occupational Safety and Health Administration)',
                'OPSI (Office of Public Safety and Inspections)',
                'DOT (Department of Transportation)',
                'NIOSH (National Institute for Occupational Safety and Health)',
              ],
              correctIndex: 1,
              explanation: 'The Massachusetts Office of Public Safety and Inspections (OPSI) administers the hoisting engineer exam and issues licenses. OSHA sets the safety regulations but does not administer state licensing.',
            },
            {
              question: 'What is the unconfined compressive strength threshold below which soil must be classified as Type C?',
              options: ['Less than 1.5 tsf', 'Less than 1.0 tsf', 'Less than 0.5 tsf', 'Less than 0.25 tsf'],
              correctIndex: 2,
              explanation: 'Type C is defined as soil with unconfined compressive strength less than 0.5 tsf (tons per square foot). This is the weakest classification and requires the most aggressive protective systems. Memorize: A ≥ 1.5 tsf, B = 0.5–1.5 tsf, C < 0.5 tsf.',
            },
            {
              question: 'An excavation in Type A soil is 4 feet deep. No protective system has been installed. Is this compliant?',
              options: [
                'Yes — Type A soil at 4 feet does not require a protective system if the competent person approves',
                'No — all excavations over 3 feet require a protective system',
                'Yes — no protective system is ever required in Type A soil under 5 feet',
                'No — Type A soil always requires sloping',
              ],
              correctIndex: 0,
              explanation: 'At less than 5 feet, OSHA allows no protective system IF the competent person determines no cave-in hazard exists. This is not a blanket exception — it requires an actual competent person evaluation. At 5 feet or deeper, a system is always required regardless of soil type.',
            },
            {
              question: 'A worker at the bottom of a 6-foot trench needs to exit quickly. The nearest ladder is 30 feet away. Is this compliant?',
              options: [
                'Yes — there is no maximum distance requirement for egress',
                'No — OSHA requires egress within 25 feet of lateral travel for all trenches 4 feet or deeper',
                'Yes — 30 feet is acceptable if a rope or handhold is provided',
                'No — for a 6-foot trench, egress must be within 10 feet',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.651 requires that employees working in trenches 4 feet or deeper must have egress (ladder, stairway, or ramp) within 25 feet of lateral travel. At 30 feet, this requirement is violated and the employer must add an additional egress point.',
            },
            {
              question: 'You are excavating and hit what appears to be bedrock at 3 feet. Vertical walls are left above the rock. Which soil classification applies?',
              options: [
                'Type A — hard rock is the most stable classification',
                'Stable Rock — if it is natural solid mineral that can be excavated vertically and remains intact',
                'Type B — rock requires additional verification before stable rock classification',
                'Type C — any previously disturbed area defaults to Type C',
              ],
              correctIndex: 1,
              explanation: 'OSHA recognizes "Stable Rock" as a separate category above Type A: natural solid mineral matter that can be excavated with vertical sides and remains intact while exposed. True bedrock qualifies. The competent person must verify it is intact and not fractured or weathered before relying on this classification.',
            },
          ],
        },
        {
          id: '2a-m4-s3',
          title: 'Practice Exam 2 — Operations & Exam Day Prep',
          durationHours: 1.5,
          learningObjectives: [
            'Apply operational knowledge to scenario-based questions',
            'Identify exam-day logistics and requirements',
            'Build confidence through timed practice',
          ],
          topics: [
            'Exam format: multiple choice, 30–40 questions, 70% to pass',
            'Exam day: government-issued photo ID required; arrive early',
            'What to study the night before: the critical numbers list and hand signals',
            'If you fail: 60-day wait required before retesting — use the time wisely',
            'Scenario categories likely on the 2A exam:',
            '  — Pre-shift inspection: what to do when you find a defect',
            '  — Excavation: soil classification and protective system selection',
            '  — Regulations: who needs a license, penalties, exemptions',
            '  — Equipment: component identification, hydraulic hazards',
            '  — Operations: hand signals, swing radius, trench proximity',
          ],
          resources: [
            {
              label: 'Practice Exam 2 & Exam Day Prep Reference',
              url: '/reference/2a-m4-s3',
              type: 'reference',
              required: true,
            },

            {
              label: 'Cranes101 — 2A License Exam Prep',
              url: 'https://cranes101.com/ma-hoisting-license-2a-all-excavators/',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'You are operating a skid steer and a co-worker walks into the working area without warning. What is the correct immediate action?',
              options: [
                'Sound the horn and continue at reduced speed',
                'Stop all machine movement immediately until the co-worker clears the area',
                'Slow down and ask the signaler to wave the co-worker off',
                'Finish the current movement, then stop and address the hazard',
              ],
              correctIndex: 1,
              explanation: '230 CMR 6.00 and OSHA both require that no unauthorized persons be within the working radius during operation. The ONLY correct response is an immediate full stop. Completing any movement with a person in the hazard zone violates regulations and risks a fatality.',
            },
            {
              question: 'A fellow operator tells you his excavator\'s backup alarm stopped working but his boss said to "just use a spotter." Is this acceptable under OSHA?',
              options: [
                'No — a working alarm is always required; spotters are not an acceptable substitute',
                'Yes — a designated employee signaling safety before backup is an acceptable alternative',
                'Yes — but only if the spotter is a competent person',
                'No — the machine must be shut down until the alarm is repaired',
              ],
              correctIndex: 1,
              explanation: '29 CFR 1926.602(a)(6) allows either a working reverse alarm OR a designated employee who signals that it is safe to back up. A spotter performing this role is an acceptable alternative — but the spotter must be designated and performing this function specifically, not just a nearby worker.',
            },
            {
              question: 'What is the correct procedure for removing a trench box (shield) from a completed excavation?',
              options: [
                'Remove the box completely, then backfill',
                'Backfill completely first, then remove the box',
                'Remove the box from the bottom up as backfill is placed simultaneously',
                'The box can be left in place and buried with the backfill',
              ],
              correctIndex: 2,
              explanation: 'Trench box removal begins from the bottom and works upward while backfill is placed simultaneously. This method maintains protection for any workers still in the trench and prevents the open trench from being exposed without protection during removal.',
            },
            {
              question: 'You are operating an excavator and notice the bucket is drifting down slowly when you hold the joystick in neutral. What does this indicate?',
              options: [
                'Normal behavior — all excavators drift slightly due to gravity',
                'Internal hydraulic cylinder seal leak; the machine should be removed from service for inspection',
                'The hydraulic fluid is too cold and needs warm-up time',
                'The boom lock is not engaged; engage it and continue',
              ],
              correctIndex: 1,
              explanation: 'Slow drift in a neutral joystick position indicates an internal seal leak in the boom or stick cylinder. The cylinder is not holding pressure. This is a mechanical defect — continued operation can lead to sudden uncontrolled movement. The machine should be inspected and repaired.',
            },
            {
              question: 'What document(s) do you need to bring to the Massachusetts 2A hoisting exam?',
              options: [
                'Only your training certificate',
                'Your employer\'s letter of authorization and training records',
                'Government-issued photo ID',
                'Proof of OSHA 30 completion and a training certificate',
              ],
              correctIndex: 2,
              explanation: 'The MA hoisting exam requires a government-issued photo ID (driver\'s license, passport, etc.). Training certificates are part of your application package, but on exam day, your photo ID is the critical document.',
            },
            {
              question: 'Soil classification reveals Type A soil with one section of the trench wall showing visible fissures (cracks running through the wall). How must the competent person handle this?',
              options: [
                'Reclassify the entire trench as Type B due to the fissuring',
                'Note the fissures and continue monitoring without changing the classification',
                'The fissured section must be treated as at least Type B; remaining solid sections may stay Type A',
                'Reclassify the entire trench as Type C for maximum safety',
              ],
              correctIndex: 0,
              explanation: 'Fissuring is an automatic disqualifier for Type A classification. If fissuring is found in any part of the trench wall, the competent person should treat the affected zone (at minimum) as Type B or lower — and may need to reclassify the entire excavation depending on the extent and pattern of fissuring.',
            },
            {
              question: 'Which scenario correctly describes the "thumb penetration test" for soil classification?',
              options: [
                'Press your thumb into a soil sample — if it penetrates more than ¼ inch, the soil is Type C',
                'Press your thumb firmly into the soil face — if it penetrates easily, the soil is Type C; if it only makes an impression, it is Type B; if no impression, it is Type A',
                'Press a standard metal probe into the soil; measure depth at 10 pounds of force',
                'Draw your thumbnail across the soil — if the scratch remains, the soil is Type A',
              ],
              correctIndex: 1,
              explanation: 'The thumb penetration test: press your thumb firmly into the soil. Easy penetration → Type C (weak). Impression only with difficulty → Type B. No impression → potentially Type A. This is a quick field test that must be combined with other visual tests for a complete classification.',
            },
            {
              question: 'You complete the 2A exam and are told your score is 68%. What is your next step?',
              options: [
                'Request a regrade — scores within 2% of passing are automatically rounded up',
                'Wait 60 days before retaking the exam; review the subject areas where you lost points',
                'Wait 30 days and schedule a retest immediately',
                'Appeal to OPSI for an oral examination to demonstrate competency',
              ],
              correctIndex: 1,
              explanation: 'A score below 70% means you did not pass. There is no rounding up, no appeal for an oral exam, and no 30-day retest window. You must wait the full 60-day mandatory waiting period. Use that time to study the specific content areas where you lost points.',
            },
          ],
        },
      ],
    },
  ],
};
