import { LicenseRestriction } from '../types';

export const restriction_2a1c: LicenseRestriction = {
  code: '2A/1C',
  name: 'Excavators, Backhoes, Loaders & Skid Steers',
  description: 'The most common combo license. Covers excavators and track hoes (2A) plus loader-backhoes and wheel loaders (1C).',
  equipmentCovered: ['Excavators', 'Track hoes', 'Loader-backhoes', 'Wheel loaders', 'Skid steers'],
  totalHours: 24,
  modules: [
    {
      id: '2a1c-m1',
      title: 'Legal & Regulatory Foundation',
      orderInCourse: 1,
      estimatedHours: 6,
      sessions: [
        {
          id: '2a1c-m1-s1',
          title: 'MGL Chapter 146 §§ 53–54A',
          durationHours: 2,
          learningObjectives: [
            'State the minimum age, exam passing score, and application fee for a 2A/1C license',
            'Identify the three threshold conditions under MGL §53 that trigger a hoisting license requirement',
            'List the key exemptions under MGL §53',
            'Explain the license duration and renewal cycle and the role of §§54–54A',
          ],
          topics: [
            'MGL §53 — who must hold a hoisting license and the catch-all clause',
            'License threshold: over 10 ft OR over 500 lbs OR bucket over ¼ cubic yard',
            'Minimum age requirement: 18 years old',
            'Exam passing score: 70% minimum; 60-day wait after a failed attempt',
            '$75 non-refundable application fee per restriction class',
            'License valid for 2 years; renewal before expiration',
            'MGL §54 — examination and issuance; §54A — apprentice licenses',
            '2A/1C combined classification: excavators and skid steers (2A) plus loader-backhoes, wheel loaders, and telescoping boom trucks (1C)',
            'Exemptions: agricultural operators, public utility supervised programs, industrial lift trucks on company property, vocational schools, approved apprenticeship programs',
            'Application through the MA Division of Occupational Licensure (DOL)',
          ],
          resources: [
            {
              label: 'MGL Chapter 146 — Licensing Requirements Reference',
              url: '/reference/2a1c-m1-s1',
              type: 'reference',
              required: true,
            },

            {
              label: 'MGL Chapter 146 § 53 — Licensing requirement',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146/Section53',
              type: 'regulation',
              required: true,
            },
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: true,
            },
            {
              label: 'Apply for a Hoisting Engineer License',
              url: 'https://www.mass.gov/how-to/apply-for-a-hoisting-engineer-license',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'A site crew runs an excavator (2A) and a loader-backhoe (1C). Which single condition alone triggers the MA hoisting license requirement for either machine?',
              options: [
                'Lifting 400 lbs to 8 ft with a ⅛ cubic yard bucket',
                'Lifting 600 lbs to 9 ft with a ⅛ cubic yard bucket',
                'Lifting 400 lbs to 8 ft with a ⅛ cubic yard bucket on a public road',
                'Lifting 400 lbs to 9 ft with a ⅛ cubic yard bucket inside a fenced yard',
              ],
              correctIndex: 1,
              explanation: 'The threshold under MGL §53 is OR, not AND: over 10 ft OR over 500 lbs OR bucket over ¼ cubic yard. Lifting 600 lbs exceeds the 500 lb limit, triggering the requirement on that condition alone — regardless of height or bucket size.',
            },
            {
              question: 'What is the minimum passing score on the Massachusetts 2A/1C hoisting engineer exam?',
              options: ['60%', '65%', '70%', '75%'],
              correctIndex: 2,
              explanation: 'The passing score is 70% for all MA hoisting license classes, including the 2A/1C combo. Score below 70% and you must wait 60 days before retesting — use that time to review your weak areas.',
            },
            {
              question: 'Which of the following operators is EXEMPT from holding a Massachusetts hoisting license?',
              options: [
                'A landscaper running a skid steer on a residential job site',
                'A farmhand operating a backhoe exclusively on agricultural land',
                'A utility contractor running a wheel loader on a city street',
                'A homeowner renting an excavator to dig their own foundation',
              ],
              correctIndex: 1,
              explanation: 'Agricultural operators working on their own farmland are explicitly exempt under MGL §53. Construction, utility, and residential excavation work all require a license regardless of who owns the property — there is no general homeowner exemption.',
            },
            {
              question: 'How long is a Massachusetts 2A/1C hoisting engineer license valid before renewal is required?',
              options: ['1 year', '2 years', '3 years', '5 years'],
              correctIndex: 1,
              explanation: 'All MA hoisting licenses, including the 2A/1C combo, are valid for 2 years. Always verify the current renewal cycle at mass.gov — renewal requirements can change.',
            },
            {
              question: 'What is the minimum age to obtain a Massachusetts 2A/1C hoisting engineer license?',
              options: ['16', '17', '18', '21'],
              correctIndex: 2,
              explanation: 'MGL Chapter 146 sets the minimum age at 18 years old. Applicants under 18 cannot obtain a hoisting license regardless of experience or training.',
            },
            {
              question: 'What is the non-refundable application fee for each restriction class when applying for a Massachusetts hoisting license?',
              options: ['$25', '$50', '$75', '$100'],
              correctIndex: 2,
              explanation: 'The application fee is $75 per restriction class as of current MA regulations. Because the 2A/1C combo covers two restriction classes, plan accordingly. The fee is non-refundable even if you fail the exam or your application is denied.',
            },
          ],
        },
        {
          id: '2a1c-m1-s2',
          title: 'MGL §§ 64–67 + 230 CMR 6.00 Overview',
          durationHours: 2,
          learningObjectives: [
            'Explain the role of 230 CMR 6.00 relative to MGL Chapter 146',
            'Summarize the safety and employer obligations imposed by MGL §§ 64–67',
            'List the 230 CMR 6.00 operating rules that apply to both 2A and 1C equipment',
            'State the SAE hand signal standard required by 230 CMR 6.00',
          ],
          topics: [
            'MGL §64 — general safety requirements for hoisting machinery',
            'MGL §65 — operator must not exceed rated capacity under any circumstance',
            'MGL §66 — employer responsibility to verify operator licenses',
            'MGL §67 — accident reporting requirements',
            '230 CMR 6.00 — implementing regulation: minimum safety standards for hoisting machinery in MA',
            'SAE J1307 hand signals required for both excavating (2A) and crane/loader (1C) operations',
            'Only the approved signaler may direct operator movements',
            'No persons within the full working radius during boom/bucket/load operation',
            'No unauthorized personnel on the machine; operator plus one apprentice under direct supervision',
            'Operators must follow all manufacturer specifications',
          ],
          resources: [
            {
              label: '230 CMR 6.00 & MGL §§64-67 Operating Rules Reference',
              url: '/reference/2a1c-m1-s2',
              type: 'reference',
              required: true,
            },

            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'SAE J1307 Hand Signals — Quick Reference Guide',
              url: '/hand-signals',
              type: 'reference',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'Which statement best describes the relationship between MGL Chapter 146 and 230 CMR 6.00?',
              options: [
                'MGL Chapter 146 is federal law; 230 CMR 6.00 is state law',
                'MGL Chapter 146 is the statute passed by the legislature; 230 CMR 6.00 is the implementing regulation',
                'They are two different names for the same regulation',
                '230 CMR 6.00 supersedes MGL Chapter 146 in all cases',
              ],
              correctIndex: 1,
              explanation: 'MGL (Massachusetts General Law) is statute — passed by the legislature and signed by the governor. 230 CMR 6.00 is a regulation that implements and expands MGL Chapter 146 with specific technical and operational requirements for hoisting machinery.',
            },
            {
              question: 'Under 230 CMR 6.00, who is the ONLY person authorized to direct the movements of a 2A excavator or 1C boom truck operator on a job site?',
              options: [
                'The general contractor\'s site superintendent',
                'Any crew member present at the job site',
                'The approved signaler assigned to the machine',
                'Either the operator or the site safety officer',
              ],
              correctIndex: 2,
              explanation: '230 CMR 6.00 requires that only the approved signaler direct the operator. Taking direction from anyone else — even a supervisor — violates the regulation. The single exception is a universal Emergency Stop, which any person may give.',
            },
            {
              question: 'Under MGL §66, who bears legal responsibility for ensuring a hoisting operator holds a valid 2A/1C license?',
              options: [
                'The operator alone',
                'Both the operator and the employer',
                'The general contractor only',
                'OPSI, which verifies licenses on every job site',
              ],
              correctIndex: 1,
              explanation: 'MGL §66 places responsibility on both the licensed operator to maintain a valid license AND the employer who directs the work. An employer who knowingly uses an unlicensed operator faces separate penalties.',
            },
            {
              question: 'Which SAE standard specifies the hand signals required by 230 CMR 6.00 for both 2A and 1C equipment?',
              options: ['SAE J386-1969', 'SAE J1307', 'SAE J320a', 'SAE J237'],
              correctIndex: 1,
              explanation: 'SAE J1307 is the standard hand signal set required by 230 CMR 6.00 for hoisting and excavating machinery in Massachusetts. SAE J386 covers seat belts, J320a covers ROPS, and J237 covers braking performance.',
            },
            {
              question: 'Beyond the licensed operator, who else may be on a 2A/1C machine during operation under 230 CMR 6.00?',
              options: [
                'No additional personnel — operator only',
                'One apprentice under the direct supervision of the operator',
                'Two helpers if the site superintendent approves',
                'As many as can safely fit in the cab',
              ],
              correctIndex: 1,
              explanation: '230 CMR 6.00 permits one apprentice in addition to the licensed operator, but only under direct supervision. Unauthorized passengers on the machine at any time violate the regulation.',
            },
            {
              question: 'Under MGL §65, what is the operator\'s obligation regarding the rated capacity of a 1C loader-backhoe or boom truck?',
              options: [
                'Capacity may be exceeded by 10% for short-duration lifts',
                'The operator must never exceed rated capacity under any circumstance',
                'Capacity limits apply only to crane lifts, not loader work',
                'The employer, not the operator, is responsible for capacity decisions',
              ],
              correctIndex: 1,
              explanation: 'MGL §65 requires that the operator never exceed the equipment\'s rated capacity under any circumstance. Exceeding rated capacity is both a statutory violation and a direct cause of tip-overs and structural failures.',
            },
          ],
        },
        {
          id: '2a1c-m1-s3',
          title: 'Renewal, Compliance & Penalties',
          durationHours: 2,
          learningObjectives: [
            'State the renewal deadline and explain that no grace period permits continued operation',
            'List the civil and criminal penalties for operating without a valid 2A/1C license',
            'Explain employer obligations under MGL §66 and accident reporting under MGL §67',
            'Describe the reinstatement process after a license lapse',
          ],
          topics: [
            'Renewal deadline: before the 2-year expiration date',
            'No official "grace period" under current law — an expired license is an invalid license',
            'Civil penalty: up to $500 per day for unlicensed operation per MGL §53',
            'Criminal penalties for repeat or egregious violations',
            'Employer liability: MGL §66 makes employers responsible for verifying operator licenses',
            'Accident reporting obligations under MGL §67',
            'Reinstatement after lapse: re-application and potentially re-examination',
            'Documenting compliance: keeping license copies available on the job site',
          ],
          resources: [
            {
              label: 'Renewal, Penalties & Licensing Compliance Reference',
              url: '/reference/2a1c-m1-s3',
              type: 'reference',
              required: true,
            },

            {
              label: 'MA Hoisting License Renewal (mass.gov)',
              url: 'https://www.mass.gov/how-to/renew-a-hoisting-license',
              type: 'reference',
              required: true,
            },
            {
              label: 'MGL Chapter 146 §§ 64–67',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146',
              type: 'regulation',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'Your 2A/1C license expired last month. You need the income and plan to "renew next week." Can you legally operate an excavator today?',
              options: [
                'Yes, there is a 30-day grace period after expiration',
                'Yes, as long as you have proof your renewal application was submitted',
                'No — operating with an expired license violates MGL §53',
                'Yes, if your employer signs a waiver of liability',
              ],
              correctIndex: 2,
              explanation: 'An expired license is an invalid license. There is no grace period that permits continued operation. Operating with an expired 2A/1C license subjects both you and your employer to civil penalties of up to $500 per day.',
            },
            {
              question: 'What is the maximum civil penalty per day for operating hoisting equipment without a valid Massachusetts license?',
              options: ['$100/day', '$250/day', '$500/day', '$1,000/day'],
              correctIndex: 2,
              explanation: 'MGL §53 allows civil penalties of up to $500 per day for each day of unlicensed operation. Each day is a separate violation, so the totals add up quickly. Employers who knowingly use unlicensed operators also face liability.',
            },
            {
              question: 'A general contractor directs an unlicensed worker to "just run the wheel loader for the afternoon." No accident occurs. What is the legal consequence?',
              options: [
                'No consequence if no accident occurs',
                'The worker faces a verbal warning only',
                'Both the worker and the contractor can face civil penalties under MGL §53',
                'Only the contractor faces penalties; workers are protected from individual liability',
              ],
              correctIndex: 2,
              explanation: 'MGL §53 creates liability for both the person operating without a license and the employer who directs or permits that operation. The absence of an accident is irrelevant — unlicensed operation is itself the violation, and each day is counted separately.',
            },
            {
              question: 'After an accident involving a 2A/1C machine on a Massachusetts job site, what does MGL §67 require?',
              options: [
                'Report only if someone was hospitalized',
                'No reporting is required if property damage is under $5,000',
                'Report the accident as required by law and cooperate with any investigation',
                'Only OSHA reporting is required; state reporting is optional',
              ],
              correctIndex: 2,
              explanation: 'MGL §67 requires reporting accidents involving hoisting machinery and full cooperation with any investigation. Failure to report compounds any penalties the operator or employer may face.',
            },
            {
              question: 'You let your 2A/1C license lapse by failing to renew before expiration. What is required to become licensed again?',
              options: [
                'Simply pay the $75 fee and the license is reinstated automatically',
                'Re-application with OPSI and potentially a new examination, depending on the lapse',
                'A supervisor co-signs your renewal form and no exam is required',
                'No action needed — MA sends a courtesy renewal automatically',
              ],
              correctIndex: 1,
              explanation: 'A lapsed license requires re-application with OPSI, and depending on how long it has been expired, re-examination may be required. Always renew before expiration to avoid this process entirely.',
            },
            {
              question: 'Under MGL §66, an employer who uses a properly licensed 2A/1C operator but never checks the license status is relying on which assumption?',
              options: [
                'That license verification is solely the operator\'s responsibility',
                'A mistaken one — MGL §66 makes the employer responsible for verifying the operator\'s valid license',
                'That OPSI will notify the employer if a license lapses',
                'That verification is only required for crane (1C) work, not excavation',
              ],
              correctIndex: 1,
              explanation: 'MGL §66 places an independent duty on the employer to verify that each operator holds a current, valid license for the equipment being used. An employer cannot shift this duty to the operator or assume the state will notify them of a lapse.',
            },
          ],
        },
      ],
    },
    {
      id: '2a1c-m2',
      title: 'Equipment Systems & Components',
      orderInCourse: 2,
      estimatedHours: 6,
      sessions: [
        {
          id: '2a1c-m2-s1',
          title: 'Excavator Anatomy & Controls',
          durationHours: 2,
          learningObjectives: [
            'Identify and name the major structural components of a crawler excavator',
            'Explain the function of the boom, stick (arm), and bucket cylinders',
            'Describe the slew ring and how 360° rotation is achieved',
            'Explain the role of the counterweight and undercarriage maintenance checkpoints',
          ],
          topics: [
            'Upperstructure vs. undercarriage: the two main assemblies',
            'Boom: the main lifting arm; stick (dipper arm): controls reach and depth',
            'Bucket: cutting edge, teeth, side cutters, mounting ears',
            'Hydraulic cylinders: boom cylinder, stick cylinder, bucket cylinder',
            'Slew ring (swing bearing) and slew motor: allow 360° rotation of upperstructure',
            'Track frame and undercarriage: sprockets, rollers, idlers, track links',
            'Track tension: too loose = derailment; too tight = premature wear',
            'Counterweight: cast-iron block at rear balances boom and load',
            'Cab: ROPS/FOPS protection, seat, controls, visibility',
            'Quick coupler attachments: thumbs, augers, compactors, hydraulic hammers',
          ],
          resources: [
            {
              label: 'Excavator & Track Hoe — Component Reference',
              url: '/reference/2a1c-m2-s1',
              type: 'reference',
              required: true,
            },

            {
              label: 'Excavator Component Reference — Anatomy, Hydraulics & Inspection',
              url: '/reference/2a-m2-s1',
              type: 'reference',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'What component allows an excavator\'s upperstructure to rotate 360 degrees independently of the tracks?',
              options: [
                'The track drive sprockets',
                'The slew ring (swing bearing) driven by the slew motor',
                'The boom hydraulic cylinder',
                'The main hydraulic pump',
              ],
              correctIndex: 1,
              explanation: 'The slew ring is a large bearing connecting the upperstructure to the undercarriage, and the hydraulic slew motor drives the rotation. Both must be inspected for cracks and proper lubrication.',
            },
            {
              question: 'Which component directly converts hydraulic pressure into the linear force that raises and lowers the boom?',
              options: [
                'The slew motor',
                'The track drive motor',
                'The boom hydraulic cylinder',
                'The main hydraulic pump',
              ],
              correctIndex: 2,
              explanation: 'Hydraulic cylinders convert fluid pressure into linear (pushing/pulling) force. The boom cylinder extends to raise the boom and retracts to lower it. Separate cylinders control the stick and bucket.',
            },
            {
              question: 'What is the primary purpose of the counterweight on a crawler excavator?',
              options: [
                'To protect the rear of the machine from collision damage',
                'To counterbalance boom and load weight during operation',
                'To provide ballast for traveling on steep slopes',
                'To house the hydraulic reservoir and cooling system',
              ],
              correctIndex: 1,
              explanation: 'The counterweight is a heavy cast-iron block at the rear of the upperstructure. Its sole purpose is to counterbalance the weight of the boom, stick, bucket, and load, preventing the machine from tipping forward. Never operate with a missing or damaged counterweight.',
            },
            {
              question: 'What is the function of the stick (dipper arm) on an excavator?',
              options: [
                'It houses the hydraulic pump and motor',
                'It connects the boom to the bucket and controls digging reach and depth',
                'It supports the counterweight',
                'It drives the track sprockets for propulsion',
              ],
              correctIndex: 1,
              explanation: 'The stick (also called the dipper arm or arm) connects the end of the boom to the bucket. Extending the stick increases reach; retracting it increases digging force and depth. The stick cylinder controls this movement.',
            },
            {
              question: 'During a pre-shift inspection you find the track has come partially off the sprocket on one side. What is the correct action?',
              options: [
                'Operate slowly to the nearest level area, then re-tension the track',
                'Tag the machine out of service and notify a mechanic',
                'Reverse the machine to reseat the track',
                'Reduce bucket load and complete the shift',
              ],
              correctIndex: 1,
              explanation: 'A derailed or partially derailed track is a mechanical failure requiring repair before operation. Operating on a partially tracked machine risks complete derailment, loss of control, and rollover. Tag out and call for service.',
            },
            {
              question: 'What is the risk of running excavator tracks that are adjusted too tight?',
              options: [
                'Track derailment',
                'Premature wear on sprockets, rollers, and track links',
                'Reduced digging force',
                'Hydraulic system overpressure',
              ],
              correctIndex: 1,
              explanation: 'Tracks that are too tight accelerate wear on sprockets, idlers, and track links, leading to costly early replacement. Tracks that are too loose risk derailment. Correct tension per the manufacturer\'s spec is critical.',
            },
          ],
        },
        {
          id: '2a1c-m2-s2',
          title: 'Loader & Backhoe Anatomy & Controls',
          durationHours: 2,
          learningObjectives: [
            'Identify the major components of a loader-backhoe (TLB) and a wheel loader',
            'Explain why stabilizers must be deployed before backhoe operation',
            'Describe articulated frame steering and the crush hazard at the articulation joint',
            'Explain the skid steer ROPS/FOPS requirement and scissor-point hazard',
          ],
          topics: [
            'Loader-backhoe (TLB) layout: loader end, articulation point, backhoe end',
            'Loader lift arms: parallel linkage keeps the bucket level during raise/lower',
            'Backhoe boom and dipperstick: digging geometry, reach, and depth',
            'Stabilizers (outriggers): must be fully deployed before backhoe operation to prevent tip-over',
            'Swing seat: rotates ~180° from loader-facing to backhoe-facing position',
            'Wheel loader: articulated frame steering and high-capacity bucket',
            'Articulation joint: severe crush/pinch hazard — never stand between the halves',
            'Skid steer ROPS/FOPS: structural damage or modification = immediate removal from service',
            'Scissor points on skid steer lift arms: must be guarded per 1926.602',
            'Universal quick-attach systems and load distribution / stability',
          ],
          resources: [
            {
              label: 'Loader & Backhoe — Anatomy & Controls Reference',
              url: '/reference/2a1c-m2-s2',
              type: 'reference',
              required: true,
            },

            {
              label: '29 CFR 1926.602 — Material Handling Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'Before beginning backhoe operations with a loader-backhoe, what must the operator do with the stabilizers?',
              options: [
                'Leave them retracted — they are only used on slopes',
                'Deploy them to firm ground so all contact points bear weight',
                'Deploy only the two stabilizers directly behind the backhoe boom',
                'Partially lower them to reduce ground disturbance',
              ],
              correctIndex: 1,
              explanation: 'Both stabilizers must be fully deployed to firm ground before any backhoe digging begins. Without stabilizers deployed, the rear of the machine can lift or tip sideways when the bucket curls under load.',
            },
            {
              question: 'Which feature allows a wheel loader to turn in a tight radius despite its large size?',
              options: [
                'Rear-wheel steering similar to a forklift',
                'Articulated frame steering — the front and rear halves pivot at a central joint',
                'Independent track steering',
                'All-wheel crab steering',
              ],
              correctIndex: 1,
              explanation: 'Wheel loaders use articulated frame steering: the front and rear halves pivot relative to each other at a central joint, allowing a very tight turning radius. This articulation point is a pinch-point hazard — never stand between the halves while the engine is running.',
            },
            {
              question: 'On a loader-backhoe, the operator\'s seat has a swing feature. What is its purpose?',
              options: [
                'It allows the operator to lean away from the backhoe during digging',
                'It rotates about 180° so the operator faces the backhoe controls when switching from loader work',
                'It tilts the operator to improve visibility over the loader bucket',
                'It locks the operator in position during travel on rough terrain',
              ],
              correctIndex: 1,
              explanation: 'The swing seat rotates approximately 180° so the operator faces the backhoe attachment and its dedicated control levers, rather than the loader controls. Always come to a complete stop before swinging the seat.',
            },
            {
              question: 'An operator drops a skid steer into a shallow ditch and the ROPS shows a visible bend. What is the required action?',
              options: [
                'Straighten the bend and return to service',
                'Mark the damage and report it at the end of the shift',
                'Remove the machine from service immediately — a damaged ROPS cannot protect the operator',
                'Have the site safety officer judge whether the ROPS is still functional',
              ],
              correctIndex: 2,
              explanation: 'Any structural damage or modification to a ROPS requires immediate removal from service. A bent ROPS has unknown residual strength and cannot reliably protect the operator in a rollover. Only a manufacturer-approved rebuild restores certification.',
            },
            {
              question: 'What is the primary safety concern when operating a wheel loader or loader-backhoe on soft or sloping ground?',
              options: [
                'The load will slip out of the bucket',
                'The machine may tip over because the support surface is destabilized',
                'The hydraulic system will rupture',
                'The operator will lose visibility',
              ],
              correctIndex: 1,
              explanation: 'Loaders are heavy machines with a relatively high center of gravity, especially with a raised bucket. Soft or sloping ground reduces stability and increases tip-over risk. Keep the bucket low and never exceed the manufacturer\'s rated slope angle.',
            },
            {
              question: 'Why must scissor points on a skid steer\'s lift arms be guarded under OSHA 1926.602?',
              options: [
                'They can pinch the load in the bucket',
                'They can amputate fingers or hands when the lift arms are lowered',
                'They catch loose clothing on the drive axles',
                'They are the hinge points for the rear access door',
              ],
              correctIndex: 1,
              explanation: 'Scissor points are where the lift arms and front frame come together as the arms lower. OSHA 1926.602 requires guards at all scissor points that create a hazard. Unguarded scissor points are a commonly cited violation and can cause amputation injuries.',
            },
          ],
        },
        {
          id: '2a1c-m2-s3',
          title: 'Hydraulics Fundamentals',
          durationHours: 2,
          learningObjectives: [
            'Explain Pascal\'s principle and pressure in hydraulic systems',
            'Identify hydraulic pressure relief and flow control components',
            'Recognize signs of hydraulic fluid degradation',
          ],
          topics: [
            'Pascal\'s principle and force multiplication',
            'Pump displacement (cc/rev) and flow (gpm)',
            'Pressure relief valves and safety settings',
            'Proportional and directional control valves',
            'Hydraulic fluid types (ISO VG, viscosity, additives)',
            'Filtering and heat management',
            'Common failure modes (cavitation, overheating)',
          ],
          resources: [
            {
              label: 'Hydraulic Systems — Safety & Inspection Reference',
              url: '/reference/2a1c-m2-s3',
              type: 'reference',
              required: true,
            },

            {
              label: '29 CFR 1926.602 — Material handling & earthmoving equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'If a hydraulic pressure relief valve is set at 3,000 psi, what happens when load pressure exceeds that setting?',
              options: [
                'The pump shuts down automatically',
                'The relief valve opens and diverts flow back to the tank',
                'System pressure slowly climbs above 3,000 psi until the hose bursts',
                'The directional control valve closes automatically',
              ],
              correctIndex: 1,
              explanation: 'Relief valves are normally-closed valves that open at a set cracking pressure, diverting excess flow back to the tank. This protects cylinders, hoses, and the pump from overpressure damage — they do not shut the pump off.',
            },
            {
              question: 'You suspect a hydraulic hose is leaking but cannot see fluid. How should you locate the leak?',
              options: [
                'Run your hand slowly along the hose to feel for moisture',
                'Hold a rag against the hose while the machine operates',
                'Use a piece of cardboard to catch fluid spray from a safe distance',
                'Pressurize the system fully and watch through the cab window',
              ],
              correctIndex: 2,
              explanation: 'NEVER use your hand to find hydraulic leaks. High-pressure fluid can inject into skin without leaving an obvious wound, leading to amputation or death. Cardboard (or a mirror) detects the spray safely from a distance.',
            },
            {
              question: 'A hydraulic cylinder has a bore area of 10 in² and the system pressure is 2,000 psi. What is the theoretical pushing force?',
              options: ['200 lbs', '2,000 lbs', '20,000 lbs', '200,000 lbs'],
              correctIndex: 2,
              explanation: 'Force = Pressure × Area = 2,000 psi × 10 in² = 20,000 lbs. This is Pascal\'s principle at work — large-bore cylinders generate tens of thousands of pounds of force at typical construction equipment pressures.',
            },
            {
              question: 'Your excavator\'s hydraulic fluid appears milky white rather than its normal amber color. What does this indicate?',
              options: [
                'Normal appearance after adding fresh fluid',
                'Water contamination in the hydraulic system',
                'The fluid is at optimal operating temperature',
                'The fluid has reached optimal operating viscosity',
              ],
              correctIndex: 1,
              explanation: 'Milky hydraulic fluid indicates water contamination — from a failed cylinder seal, a cracked cooler, or condensation. Water causes cavitation, rust, and seal deterioration. The system must be serviced before operation.',
            },
            {
              question: 'You hear a whining or grinding noise from the hydraulic pump on your wheel loader. This most likely indicates:',
              options: [
                'The hydraulic fluid is too hot',
                'Cavitation — the pump is not receiving adequate fluid (low level or clogged strainer)',
                'The pressure relief valve is stuck open',
                'The hydraulic oil filter is brand new',
              ],
              correctIndex: 1,
              explanation: 'Cavitation occurs when the pump tries to move more fluid than is supplied to its inlet, so air fills the void. The whine or grinding comes from air bubbles imploding inside the pump, causing pitting and accelerated wear. Check fluid level and the inlet strainer immediately.',
            },
            {
              question: 'What is the minimum burst-pressure safety factor required for hydraulic hoses on construction equipment?',
              options: ['2:1', '3:1', '4:1', '6:1'],
              correctIndex: 2,
              explanation: 'OSHA and industry standards require hydraulic hoses to have a minimum 4:1 safety factor — a hose rated for 3,000 psi working pressure must burst at no less than 12,000 psi. Hoses that fail this standard must be replaced.',
            },
          ],
        },
      ],
    },
    {
      id: '2a1c-m3',
      title: 'Safe Operation & Inspections',
      orderInCourse: 3,
      estimatedHours: 6,
      sessions: [
        {
          id: '2a1c-m3-s1',
          title: 'Pre-Shift Inspection & Daily Walkthrough',
          durationHours: 2,
          learningObjectives: [
            'Conduct a systematic 360° pre-shift inspection of excavators, loaders, and backhoes',
            'Identify conditions that require immediate removal from service',
            'Explain the OSHA basis for pre-shift and post-relocation inspections',
            'Apply boom-truck-specific inspection items (ATB, wire rope, outriggers) for 1C equipment',
          ],
          topics: [
            'OSHA basis: 29 CFR 1926.20 and 1926.600 — frequent and regular inspections by a competent person',
            'Timing: before each shift AND after each machine relocation',
            '360° walk-around: start at a fixed point and work around the entire machine in one direction',
            'Structural cracks: boom, stick, bucket mounting ears, weld seams, boom-to-turntable welds',
            'Hydraulic hose condition: abrasion, kinks, bulges, weeping fittings',
            'Track tension and undercarriage (excavators); tire condition and pressure (loaders/backhoes)',
            'Bucket and attachment security: pins, retaining clips, quick-attach mechanism',
            'Boom truck items: anti-two-block (ATB) function test, LMI function, wire rope discard criteria, outrigger floats',
            'Cab safety items: seat belt, mirrors, horn, backup alarm, fire extinguisher charge',
            'Removal-from-service conditions and the "Do Not Operate" tag-out procedure',
          ],
          resources: [
            {
              label: 'Pre-Shift Inspection Reference & Checklist',
              url: '/reference/2a1c-m3-s1',
              type: 'reference',
              required: true,
            },

            {
              label: '29 CFR 1926.600 — Equipment safety general',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.600',
              type: 'osha',
              required: true,
            },
            {
              label: '29 CFR 1926.602 — Material handling & earthmoving equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'During a pre-shift inspection you notice a hydraulic hose has a small bulge but no visible leak. What should you do?',
              options: [
                'Continue operating — it is just cosmetic',
                'Document the defect and tag the machine "Do Not Operate"',
                'Apply sealant and continue operating',
                'Monitor it and replace at the end of the week',
              ],
              correctIndex: 1,
              explanation: 'A bulge indicates the hose\'s inner reinforcement has delaminated and the outer cover is temporarily holding the pressure. Failure is imminent. The hose must be replaced before operation to prevent a sudden loss of hydraulic power or high-pressure fluid spray.',
            },
            {
              question: 'When must a pre-shift inspection be performed after moving an excavator to a new location on the same day?',
              options: [
                'Only at the start of the shift; no additional inspection needed',
                'After each machine relocation, before resuming work',
                'At the end of the day to document the condition',
                'Only if the move involved traveling more than one mile',
              ],
              correctIndex: 1,
              explanation: 'OSHA requires inspections before each shift AND after each machine move. New ground conditions, travel damage, and changed environmental factors all create new hazards that must be assessed before resuming work.',
            },
            {
              question: 'During a pre-shift inspection of a loader-backhoe you find the seat belt latch is broken. The job is urgent. What is the correct action?',
              options: [
                'Use the machine at reduced speed until the part arrives',
                'Tie the belt in a knot as a temporary fix',
                'Tag the machine out of service and notify your supervisor',
                'Operate only in low-risk areas until repairs are made',
              ],
              correctIndex: 2,
              explanation: 'A non-functional seat belt is a removal-from-service condition with no exceptions. ROPS protection only works if the operator is restrained inside the cab during a rollover. Operating without a working seat belt violates OSHA 1926.602 and 230 CMR 6.00.',
            },
            {
              question: 'On a 1C boom truck pre-shift inspection, you find the anti-two-block (ATB) device is not functioning. What must you do?',
              options: [
                'Operate carefully and watch the load block closely',
                'Tag the machine "Do Not Operate" — ATB must be functional before any crane use',
                'Operate at reduced height to prevent two-blocking',
                'Continue operating until a replacement arrives',
              ],
              correctIndex: 1,
              explanation: 'A non-functional ATB device is a go/no-go item under OSHA 1926 Subpart CC. Two-blocking can snap the wire rope or destroy the boom. The machine must not be used for crane lifts until the ATB is repaired and tested.',
            },
            {
              question: 'You find a crack at the weld connecting an excavator bucket to its mounting ears. What is the correct response?',
              options: [
                'Monitor the crack throughout the shift',
                'Weld the crack yourself before operating',
                'Remove the machine from service immediately',
                'Reduce dig depth to lower stress on the bucket',
              ],
              correctIndex: 2,
              explanation: 'Cracks at bucket mounting ears indicate imminent catastrophic failure — small cracks expand rapidly under load stress. The machine must be removed from service and repaired by qualified personnel before resuming operation.',
            },
            {
              question: 'The fire extinguisher mounted on a wheel loader has a gauge reading in the red zone. What action is required?',
              options: [
                'Continue operating — extinguishers are supplemental safety items',
                'Note it in the log and replace it at the next scheduled service',
                'Remove the machine from service — a discharged or low-pressure extinguisher is a removal-from-service condition',
                'Operate at reduced speed near potential ignition sources',
              ],
              correctIndex: 2,
              explanation: 'A fire extinguisher in the red zone is discharged or low-pressure and will not work in an emergency. A working, accessible fire extinguisher must be present on the machine at all times — its absence or failure is a removal-from-service condition.',
            },
          ],
        },
        {
          id: '2a1c-m3-s2',
          title: 'Operating Hazards & Safe Procedures',
          durationHours: 2,
          learningObjectives: [
            'State the excavation depth threshold that requires a protective system under OSHA Subpart P',
            'Apply swing-radius exclusion zones and utility-location requirements',
            'Identify overhead power line clearance requirements for excavators (2A) and boom trucks (1C)',
            'Describe safe travel and load-handling procedures for loaders and loader-backhoes',
          ],
          topics: [
            'OSHA Subpart P (1926.650–652): protective system required at 5 ft deep — no exceptions',
            'Under 5 ft: no system required only if a competent person finds no cave-in hazard',
            'Egress: trenches 4 ft or deeper need a ladder, stairway, or ramp within 25 ft of lateral travel',
            'Spoil pile setback: minimum 2 ft from the trench edge',
            'Swing radius exclusion zone: no persons within the full working radius (230 CMR 6.00)',
            'Utility location: call 811 (Dig Safe) before any ground disturbance',
            'Overhead power lines: 10 ft minimum clearance for excavators; 20 ft for boom truck cranes (1926.1408)',
            'Loader/loader-backhoe travel: bucket low; on ramps the loaded bucket faces uphill',
            'Crush and pinch points: bucket, arm, boom articulation, wheel loader articulation joint',
            'Weather and ground conditions: wind, rain, freeze-thaw, soft or sloped ground',
          ],
          resources: [
            {
              label: 'Operating Hazards & Safe Procedures Reference',
              url: '/reference/2a1c-m3-s2',
              type: 'reference',
              required: true,
            },

            {
              label: '29 CFR 1926.650 — Excavations: scope and definitions',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.650',
              type: 'osha',
              required: true,
            },
            {
              label: '29 CFR 1926.1408 — Power Line Safety (Cranes)',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1408',
              type: 'osha',
              required: true,
            },
            {
              label: 'Dig Safe — Massachusetts 811 call-before-you-dig',
              url: 'https://digsafe.com',
              type: 'reference',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'At exactly what excavation depth does OSHA Subpart P require a protective system with NO exceptions?',
              options: ['3 feet', '4 feet', '5 feet', '6 feet'],
              correctIndex: 2,
              explanation: 'At 5 feet or deeper, a protective system (sloping, shoring, or a shield) is ALWAYS required. Between 0 and 5 feet, no system is required only if the competent person determines no cave-in hazard exists. The 5-foot threshold is one of the most commonly tested numbers on the MA hoisting exam.',
            },
            {
              question: 'Before digging on any Massachusetts job site with an excavator or backhoe, what must the operator or contractor do?',
              options: [
                'Call 811 (Dig Safe) and wait for utility locations to be marked',
                'Check the property deed for any listed easements',
                'Notify the local police department of excavation plans',
                'Nothing additional if the site plan shows no utilities',
              ],
              correctIndex: 0,
              explanation: 'Massachusetts law requires calling 811 (Dig Safe) before any excavation. Utilities must be located and marked before digging begins — failure to call can result in fines, liability for damage, and worker fatalities from struck utilities.',
            },
            {
              question: 'What is the minimum clearance an excavator must maintain from energized overhead power lines rated up to 50 kV?',
              options: ['5 feet', '8 feet', '10 feet', '15 feet'],
              correctIndex: 2,
              explanation: 'OSHA requires a minimum 10-foot clearance from energized overhead lines at voltages up to 50 kV. If the excavator cannot maintain 10 feet, the utility must be de-energized or insulated before work begins. Note that boom truck crane work (Subpart CC) requires a larger 20-foot clearance for lines up to 350 kV.',
            },
            {
              question: 'A worker walks into the swing radius of your excavator while you are repositioning the boom. What is the correct immediate action?',
              options: [
                'Sound the horn and proceed carefully',
                'Ask the signaler to wave them off, then proceed',
                'Stop all machine movement until the worker clears the radius',
                'Slow the swing and maintain visual contact',
              ],
              correctIndex: 2,
              explanation: '230 CMR 6.00 prohibits any persons within the full working radius during boom/bucket operation. The only correct action is to stop and wait until the area is clear — no exceptions, regardless of how slowly you move.',
            },
            {
              question: 'You are traveling a wheel loader up a ramp with a loaded bucket. In which direction should the load face?',
              options: [
                'Downhill, so you can see where you are going',
                'Uphill, to keep weight over the drive axle and improve stability',
                'Direction does not matter on grades under 15%',
                'Downhill, so the bucket can be lowered quickly if needed',
              ],
              correctIndex: 1,
              explanation: 'With a loaded bucket on a ramp, always travel with the load facing uphill. This keeps the heavy end toward the uphill slope, reducing the risk of tipping forward over the load if you stop suddenly or a tire slips.',
            },
            {
              question: 'A trench is 4 feet deep and workers need to enter it. Is a means of egress required?',
              options: [
                'No — egress is only required at 5 feet or deeper',
                'No — a 4-foot depth does not trigger egress requirements',
                'Yes — egress is required for any trench 4 feet deep or deeper, within 25 ft of lateral travel',
                'Yes — but only if workers stay in the trench more than 30 minutes',
              ],
              correctIndex: 2,
              explanation: 'OSHA 1926.651 requires a means of egress (ladder, stairway, or ramp) for any trench 4 feet or deeper, located within 25 feet of lateral travel for any worker. This is a separate threshold from the 5-foot protective-system requirement.',
            },
          ],
        },
        {
          id: '2a1c-m3-s3',
          title: 'Hand Signals & Communication Procedures',
          durationHours: 2,
          learningObjectives: [
            'Demonstrate the SAE J1307 hand signals required by 230 CMR 6.00 for 2A and 1C equipment',
            'Identify the designated signaler\'s positioning and responsibilities',
            'Apply the Emergency Stop signal and explain when it takes absolute priority',
            'Explain when radio communication may substitute for hand signals',
          ],
          topics: [
            '230 CMR 6.00 requires SAE J1307 hand signals for all 2A and 1C equipment operations',
            'Only the approved signaler may direct the operator',
            'SAE J1307 signals: raise/lower, boom up/down, extend/retract boom, swing, travel, stop, emergency stop',
            'Emergency Stop: crossed arms across the chest — any person may give it and it takes absolute priority',
            'Signaler positioning: clear line of sight to the operator at all times; never in the swing radius',
            'Operator must stop immediately if signaler contact is lost',
            'One signaler per machine — no relay or substitute except for Emergency Stop',
            'Radio communication: acceptable when both parties have reliable two-way radios and clear communication',
            'Conflicting signals: stop until resolved; Emergency Stop always wins',
            'Night operations: illuminated signals or radio required',
          ],
          resources: [
            {
              label: 'Hand Signals & Communication Reference',
              url: '/reference/2a1c-m3-s3',
              type: 'reference',
              required: true,
            },

            {
              label: '230 CMR 6.00 — Hoisting Machinery (mass.gov)',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
            {
              label: 'SAE J1307 Hand Signals — Quick Reference Guide',
              url: '/hand-signals',
              type: 'reference',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'What is the universal Emergency STOP hand signal recognized under SAE J1307?',
              options: [
                'One hand raised with palm facing out',
                'Both arms raised above the head',
                'Arms crossed at the wrists in front of the chest',
                'Pointing downward with both hands',
              ],
              correctIndex: 2,
              explanation: 'Arms crossed at the wrists in front of the chest is the universal Emergency Stop signal per SAE J1307. Every operator on site must respond immediately, and any person — not just the signaler — may give it. It takes absolute priority over all other instructions.',
            },
            {
              question: 'Under 230 CMR 6.00, who is the ONLY person authorized to direct a 2A/1C operator\'s movements on a job site?',
              options: [
                'The general contractor\'s site superintendent',
                'Any crew member present at the job site',
                'The approved signaler assigned to the machine',
                'Either the operator or the site safety officer',
              ],
              correctIndex: 2,
              explanation: '230 CMR 6.00 requires that only the approved signaler direct the operator. Taking direction from anyone else — even a supervisor — violates the regulation. The single exception is the universal Emergency Stop, which any person may give.',
            },
            {
              question: 'You are operating a boom truck and lose sight of your signaler mid-swing. What must you do?',
              options: [
                'Slow the swing and look for the signaler',
                'Complete the swing to a safe position, then stop',
                'Stop all machine movement immediately',
                'Switch to radio and ask the signaler to reposition',
              ],
              correctIndex: 2,
              explanation: 'If visual contact with the signaler is lost at any time, 230 CMR 6.00 requires the operator to stop immediately. A signaler you cannot see cannot safely direct the machine, and no relay or substitution is permitted.',
            },
            {
              question: 'A coworker who is not the designated signaler gives you a "hoist up" signal because the signaler briefly stepped away. What should you do?',
              options: [
                'Comply — it is a simple lift and they clearly mean well',
                'Comply only if the coworker is a licensed operator',
                'Do not hoist — only the approved signaler may direct your movements',
                'Hoist slowly and watch for the signaler to return',
              ],
              correctIndex: 2,
              explanation: '230 CMR 6.00 allows only the approved signaler to direct the operator. Taking direction from any other person violates the regulation regardless of how simple the movement or how experienced the coworker is. Wait for the signaler or stop operations.',
            },
            {
              question: 'You receive a "hoist up" hand signal from your signaler and simultaneously a verbal "stop" from the site superintendent. What is the correct response?',
              options: [
                'Follow the superintendent — they have overall authority',
                'Follow the signaler — they are the designated authority for movements',
                'Stop all motion and wait until you receive a single, clear, unambiguous signal',
                'Follow whichever instruction you judge to be safer',
              ],
              correctIndex: 2,
              explanation: 'Conflicting signals require the operator to stop. Neither the superintendent\'s verbal instruction nor the signaler\'s hand signal takes priority in a conflict — the correct action is to stop until the conflict is resolved and a single clear signal is received.',
            },
            {
              question: 'When is radio communication an acceptable substitute for hand signals on a 2A/1C operation?',
              options: [
                'Never — 230 CMR 6.00 requires hand signals at all times',
                'When both the operator and signaler have reliable two-way radios and clear communication',
                'Only during night operations when visibility is reduced',
                'Only when a supervisor approves the deviation',
              ],
              correctIndex: 1,
              explanation: 'Radio communication is an acceptable alternative to hand signals provided both parties have reliable two-way radios and communication is clear. The same one-signaler-per-machine rule applies. If communication becomes unclear, the operator must stop.',
            },
          ],
        },
      ],
    },
    {
      id: '2a1c-m4',
      title: 'OSHA Compliance & Exam Review',
      orderInCourse: 4,
      estimatedHours: 6,
      sessions: [
        {
          id: '2a1c-m4-s1',
          title: '29 CFR 1926 Highlights for Operators',
          durationHours: 2,
          learningObjectives: [
            'Apply OSHA 1926.602 rules for earthmoving equipment (2A excavators and 1C loaders/backhoes)',
            'Explain how OSHA 1926 Subpart CC applies to telescoping boom trucks (1C)',
            'State the prohibition on unauthorized equipment modifications',
            'Identify common OSHA citations across excavation and material-handling work',
          ],
          topics: [
            '29 CFR 1926.602 — primary standard for earthmoving equipment (excavators, loaders, backhoes)',
            'Seat belts: SAE J386-1969 required on all equipment with ROPS',
            'Reverse signal alarm required when the operator\'s rear view is obstructed',
            'No modifications without written manufacturer approval — voids ROPS and load certifications',
            '29 CFR 1926 Subpart CC — Cranes & Derricks: applies to 1C boom trucks',
            '1926.1408 power line safety; 1926.1412 inspection; 1926.1416/1417 operational aids and operator qualification',
            '29 CFR 1926.650 — Excavations (Subpart P) for trenching work',
            'PPE: hard hat, safety glasses, hearing protection, high-visibility vest',
            'Lock-out / Tag-out (LOTO) before maintenance on powered equipment',
            'Common violations: unguarded scissor points, no backup alarm, missing seat belt, ATB not functional',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1926 Highlights Reference',
              url: '/reference/2a1c-m4-s1',
              type: 'reference',
              required: true,
            },

            {
              label: '29 CFR 1926.602 — Material handling & earthmoving equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926 Subpart CC — Cranes & Derricks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1400',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'A skid steer operator wants to add a custom steel cab guard not listed in the manufacturer\'s manual. What does OSHA require?',
              options: [
                'The modification is permitted if it does not reduce visibility',
                'Written manufacturer approval is required before any modification',
                'The site safety officer must approve the modification',
                'No approval is needed for non-structural modifications',
              ],
              correctIndex: 1,
              explanation: '29 CFR 1926.602 prohibits modifications without written manufacturer approval. Unauthorized modifications void ROPS/FOPS certifications, load ratings, and other safety certifications — even if the modification seems harmless.',
            },
            {
              question: 'Under OSHA 1926.602, when is a reverse signal alarm required on a skid steer or wheel loader?',
              options: [
                'Always, regardless of visibility',
                'Only when operating at night',
                'When the operator\'s view to the rear is obstructed',
                'Only when reversing over 5 mph',
              ],
              correctIndex: 2,
              explanation: 'OSHA 1926.602(a)(6) requires an audible reverse alarm when the operator\'s rear view is obstructed. Alternatively, a designated employee must signal that it is safe to back up. Most enclosed cabs obstruct the rear view, making a backup alarm effectively mandatory.',
            },
            {
              question: 'Which OSHA standard governs the operation of a 1C telescoping boom truck used as a crane on a construction site?',
              options: [
                '29 CFR 1926.502 — Fall Protection',
                '29 CFR 1926 Subpart CC — Cranes and Derricks in Construction',
                '29 CFR 1926.21 — Safety Training',
                '29 CFR 1910.178 — Powered Industrial Trucks',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926 Subpart CC (Cranes and Derricks in Construction) covers telescoping boom trucks used as cranes. Loader-backhoes and wheel loaders, by contrast, fall under 1926.602 (Material Handling Equipment).',
            },
            {
              question: 'SAE J386-1969 governs which safety component on 2A/1C equipment?',
              options: [
                'ROPS structural strength',
                'Seat belt performance',
                'Hydraulic hose pressure ratings',
                'Braking system stopping distance',
              ],
              correctIndex: 1,
              explanation: 'SAE J386-1969 is the seat belt standard referenced by OSHA 1926.602. It sets the performance requirements that seat belts on ROPS-equipped equipment must meet. A seat belt that does not meet J386 is not compliant.',
            },
            {
              question: 'A boom truck operator on a construction site has not been certified or qualified per OSHA 1926.1417. How does OSHA treat this?',
              options: [
                'A de minimis violation with no penalty',
                'An other-than-serious violation',
                'A serious violation — the employer can be cited and fined',
                'Only a verbal warning for a first offense',
              ],
              correctIndex: 2,
              explanation: 'Operator qualification/certification requirements under 1926.1417 are serious violations. OSHA can cite the employer for non-compliance. Note that MA licensing and OSHA qualification are independent requirements — both must be met.',
            },
            {
              question: 'Which of the following is a commonly cited OSHA 1926.602 violation on construction sites?',
              options: [
                'Operators wearing hard hats inside the cab',
                'Skid steers operating without scissor point guards',
                'Excavators traveling with the bucket lowered',
                'Operators using hand signals instead of radio',
              ],
              correctIndex: 1,
              explanation: 'Missing or inadequate scissor point guarding on front-end loaders and skid steers is one of the most frequently cited violations under OSHA 1926.602. Guards must be in place whenever the machine is operated.',
            },
          ],
        },
        {
          id: '2a1c-m4-s2',
          title: 'Practice Exam 1 – Mixed Content',
          durationHours: 2,
          learningObjectives: [
            'Apply regulatory, equipment, and safety knowledge to scenario-based questions',
            'Recall the critical numbers tested across both 2A and 1C content',
            'Identify the correct answer when competing options appear plausible',
            'Practice time management and process-of-elimination strategies',
          ],
          topics: [
            'Scenario-based questions combining regulation, equipment, and safety',
            'Critical numbers to memorize: 70% passing, 60-day retest wait, $75 fee per class, age 18, 2-year license',
            'Excavation numbers: 5 ft protective system, 4 ft egress, 25 ft to egress, 2 ft spoil setback',
            'Clearance numbers: 10 ft from overhead lines (excavator); 20 ft (boom truck crane)',
            'Load chart and outrigger fundamentals for 1C equipment',
            'Time management and reading "and" vs. "or" / "always" vs. "unless" carefully',
          ],
          resources: [
            {
              label: 'Practice Exam 1 — Critical Numbers & Strategy Reference',
              url: '/reference/2a1c-m4-s2',
              type: 'reference',
              required: true,
            },

            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'You are about to excavate near a utility pole. When must utilities be located before you dig?',
              options: [
                'Only if you plan to dig within 10 feet of the pole',
                'Always — call 811 (Dig Safe) and wait for markings before any ground disturbance',
                'Only if the pole appears to be in your swing radius',
                'Never; it is solely the site supervisor\'s job',
              ],
              correctIndex: 1,
              explanation: 'Massachusetts law requires calling 811 (Dig Safe) before any excavation. Utilities must be located and marked before digging begins — there is no minimum-distance exception. Failure to call can cause fines, liability, and fatalities from struck utilities.',
            },
            {
              question: 'A hydraulic hose on your loader-backhoe is weeping (small drips) from a connection. Can you operate the machine?',
              options: [
                'Yes, if the leakage is minimal',
                'No — any active leak is a defect that requires removal from service',
                'Yes, but only for brief operations',
                'Yes, if you monitor it closely',
              ],
              correctIndex: 1,
              explanation: 'Any active hydraulic leak is a defect requiring removal from service. A weeping connection can worsen suddenly, leading to loss of hydraulic power, high-pressure spray, or loss of control. Tag the machine out until repaired.',
            },
            {
              question: 'A boom truck load chart shows 5,000 lbs capacity at 30 ft radius. Your rigging weighs 400 lbs. What is the maximum net load you can lift on the hook?',
              options: [
                '5,400 lbs — rigging weight is additive',
                '5,000 lbs — rigging weight does not count',
                '4,600 lbs — rated capacity minus rigging weight',
                '4,500 lbs — apply a 10% safety deduction',
              ],
              correctIndex: 2,
              explanation: 'Rated capacity is the TOTAL suspended load. Subtract all rigging weight (400 lbs) from the chart capacity (5,000 lbs) to get the maximum net hook load: 4,600 lbs. Never add rigging weight on top of rated capacity.',
            },
            {
              question: 'On a 40-question MA hoisting exam with a 70% passing score, what is the minimum number of correct answers needed to pass?',
              options: ['24 correct', '26 correct', '28 correct', '30 correct'],
              correctIndex: 2,
              explanation: '70% of 40 questions = 28 correct answers needed to pass. Getting 27 or fewer means you score below 70% and must wait 60 days before retesting.',
            },
            {
              question: 'You are digging a trench that reaches 5 feet deep in Type C soil. What does OSHA Subpart P require?',
              options: [
                'No protection is required if no worker enters the trench',
                'A protective system (sloping at 1½:1, shoring, or a shield) is required',
                'Protection is required only above 6 feet',
                'A competent person can waive protection in Type C soil',
              ],
              correctIndex: 1,
              explanation: 'At 5 feet or deeper, a protective system is always required regardless of soil type. Type C — the least stable — requires the most aggressive protection: sloping at 1½:1 (34°), a manufacturer-rated shield, or engineered shoring.',
            },
            {
              question: 'Your renewed 2A/1C license is issued by OPSI today. When can you legally operate hoisting equipment again?',
              options: [
                'After a 30-day waiting period',
                'After a 60-day waiting period',
                'Immediately — there is no waiting period for a renewal',
                'Only after a new practical exam',
              ],
              correctIndex: 2,
              explanation: 'Once your renewed license is issued by OPSI, you are legal to operate immediately — there is no waiting period for a renewal. The 60-day wait applies only after a FAILED exam attempt, which is a different situation.',
            },
          ],
        },
        {
          id: '2a1c-m4-s3',
          title: 'Practice Exam 2 & Review',
          durationHours: 2,
          learningObjectives: [
            'Complete a comprehensive second practice exam across all 2A and 1C content areas',
            'Reinforce go/no-go inspection decisions and operating-safety rules',
            'Recall exam-day logistics and requirements',
            'Build confidence and identify remaining weak areas through timed practice',
          ],
          topics: [
            'Comprehensive scenario-based questions across all four modules',
            'Final review: soil classification, protective systems, swing radius, hand signals',
            'Final review: load chart reading, outrigger and stabilizer setup, ATB and LMI',
            'Inspection go/no-go decisions and removal-from-service conditions',
            'Exam format: multiple choice, approximately 30–40 questions, 70% to pass',
            'Exam day logistics: government-issued photo ID, arrive early, no phones in the exam room',
          ],
          resources: [
            {
              label: 'Practice Exam 2 & Exam Day Prep Reference',
              url: '/reference/2a1c-m4-s3',
              type: 'reference',
              required: true,
            },

            {
              label: 'Apply for a Hoisting Engineer License',
              url: 'https://www.mass.gov/how-to/apply-for-a-hoisting-engineer-license',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'A typical MA hoisting exam has approximately how many questions and what is the passing score?',
              options: [
                '20 questions, 60% passing',
                '30–40 questions, 70% passing',
                '40 questions, 80% passing',
                '50 questions, 75% passing',
              ],
              correctIndex: 1,
              explanation: 'The standard MA hoisting exam is approximately 30–40 multiple-choice questions with a 70% minimum passing score. The same format and passing threshold apply to all restriction classes.',
            },
            {
              question: 'If you fail the MA hoisting exam, how soon can you retake it?',
              options: [
                'Immediately, at any time',
                '7 days after the failed attempt',
                '30 days after the failed attempt',
                '60 days after the failed attempt',
              ],
              correctIndex: 3,
              explanation: 'You must wait 60 days after a failed attempt before retesting. Use that time to study the specific content areas where you lost points rather than rushing back unprepared.',
            },
            {
              question: 'Which defect is a go/no-go condition requiring immediate removal from service on a 1C boom truck?',
              options: [
                'Minor dirt accumulation on the outrigger beams',
                'A non-functional anti-two-block (ATB) device',
                'A slightly worn rubber pad on one outrigger float',
                'A small cosmetic dent on the carrier fender',
              ],
              correctIndex: 1,
              explanation: 'A non-functional ATB device is a hard stop — the machine cannot be used for crane lifts. Dirt, cosmetic dents, and normal wear should be documented but are not go/no-go conditions. The ATB failure must be repaired and retested before returning to service.',
            },
            {
              question: 'A wheel loader is traveling a job-site road with a loaded bucket raised to full height. Why is this unsafe?',
              options: [
                'The elevated bucket increases wind resistance and fuel use',
                'The high center of gravity greatly increases tip-over risk on uneven ground or in turns',
                'The bucket obscures the headlights',
                'It is only unsafe if the load exceeds 2,000 lbs',
              ],
              correctIndex: 1,
              explanation: 'Traveling with the bucket elevated raises the center of gravity, making the machine highly susceptible to tipping on slopes, soft ground, or in turns. The carry position (12–18 inches off the ground) keeps the center of gravity low and stable.',
            },
            {
              question: 'A trench in Type B soil is 7 feet deep and the contractor wants to slope the walls. What is the minimum required horizontal-to-vertical slope ratio?',
              options: ['¾:1 (53°)', '1:1 (45°)', '1½:1 (34°)', '2:1 (27°)'],
              correctIndex: 1,
              explanation: 'Type B soil requires a minimum 1:1 slope — 1 foot horizontal for every 1 foot of vertical depth (45°). Type A allows ¾:1 (53°) and Type C requires 1½:1 (34°). Memorize these three ratios for the exam.',
            },
            {
              question: 'On exam day, what is the best strategy for a question about a regulation you do not recognize?',
              options: [
                'Skip it — it likely will not appear again',
                'Use process of elimination to remove clearly wrong answers, then choose the best remaining option',
                'Guess "C" — it is statistically the most common answer',
                'Leave it blank — wrong answers are penalized more than blanks',
              ],
              correctIndex: 1,
              explanation: 'Process of elimination is the most effective strategy when unsure. MA hoisting exams do not penalize wrong answers, so always answer every question. Eliminating one or two clearly wrong choices significantly improves your odds on the rest.',
            },
          ],
        },
      ],
    },
  ],
};
