import { LicenseRestriction } from '../types';

export const restriction_3a: LicenseRestriction = {
  code: '3A',
  name: 'Pile driving / derricks / cableways',
  description: 'Pile drivers, fixed derricks, cableways.',
  equipmentCovered: ['Pile drivers', 'Fixed derricks', 'Cableways'],
  totalHours: 20,
  modules: [
    {
      id: '3a-m1',
      title: 'Foundation',
      orderInCourse: 1,
      estimatedHours: 5,
      sessions: [
        {
          id: '3a-m1-s1',
          title: 'Regulations',
          durationHours: 2,
          learningObjectives: [
            'Identify the Massachusetts statutes and regulations that govern pile driving, derrick, and cableway operations',
            'State the minimum age, exam passing score, and application fee for the 3A license',
            'Explain how 230 CMR 6.00 extends and implements MGL Chapter 146 for 3A equipment',
            'Describe the federal OSHA standards that apply to pile driving and derrick work in Massachusetts',
          ],
          topics: [
            'MGL Chapter 146 — the foundational hoisting licensing statute',
            'MGL §53 — who must hold a hoisting license; 3A equipment is covered',
            'Minimum age: 18 years old; exam passing score: 70%',
            '$75 non-refundable application fee per restriction class',
            '60-day waiting period after a failed attempt',
            'License duration: 2-year cycle; renewal before expiration',
            '230 CMR 6.00 — MA implementing regulation; sets operating and inspection minimums for pile drivers, derricks, and cableways',
            'OSHA 29 CFR 1926.603 — federal standard specific to pile driving equipment',
            'OSHA 29 CFR 1926 Subpart CC — Cranes and Derricks in Construction (§1926.1436 covers derricks)',
            'Relationship between MA state regulations and federal OSHA: whichever is more protective controls',
            'Application through the MA Division of Occupational Licensure (DOL)',
          ],
          resources: [
            {
              label: 'MGL Chapter 146 §53 — Licensing requirement',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146/Section53',
              type: 'regulation',
              required: true,
            },
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.603 — Pile Driving Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.603',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.1436 — Derricks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1436',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'What is the minimum passing score on the Massachusetts 3A hoisting engineer exam?',
              options: ['60%', '65%', '70%', '75%'],
              correctIndex: 2,
              explanation: 'The passing score for all Massachusetts hoisting engineer exams is 70%. Score below that and you must wait 60 days before retesting — use that time to focus on your weak areas.',
            },
            {
              question: 'Which regulation specifically governs pile driving equipment safety at the federal level?',
              options: [
                '29 CFR 1926 Subpart N (Helicopters)',
                '29 CFR 1926.603 (Pile driving equipment)',
                '29 CFR 1910.180 (Crawler and locomotive cranes)',
                '29 CFR 1926 Subpart R (Steel Erection)',
              ],
              correctIndex: 1,
              explanation: '29 CFR 1926.603 is the specific OSHA standard for pile driving equipment. It covers boiler and pressure vessel requirements, hose safety chains, stop blocks, leads, and operator signaling rules.',
            },
            {
              question: 'Which federal regulation covers derrick operations in construction?',
              options: [
                '29 CFR 1926.550 (Cranes, old standard)',
                '29 CFR 1926.1436 within Subpart CC',
                '29 CFR 1910.179 (Overhead and gantry cranes)',
                '29 CFR 1926.603 (Pile driving equipment)',
              ],
              correctIndex: 1,
              explanation: 'OSHA 29 CFR 1926.1436 (within Subpart CC — Cranes and Derricks in Construction) is the current standard for derricks. The old 1926.550 was superseded. Exam questions may test whether candidates know which subpart applies.',
            },
            {
              question: 'How long is a Massachusetts 3A hoisting engineer license valid before renewal is required?',
              options: ['1 year', '2 years', '3 years', '5 years'],
              correctIndex: 1,
              explanation: 'All Massachusetts hoisting licenses are valid for 2 years. Renewal must occur before expiration — there is no official grace period under current MA law.',
            },
            {
              question: 'When MA 230 CMR 6.00 and a federal OSHA standard apply to the same operation and they conflict, which takes precedence?',
              options: [
                'Federal OSHA always prevails because federal law supersedes state law',
                'State 230 CMR 6.00 always prevails because it is more specific',
                'Whichever standard is more protective of employees applies',
                'The operator chooses which standard to follow',
              ],
              correctIndex: 2,
              explanation: 'Under the OSH Act, states with approved plans may enforce standards at least as protective as OSHA. In Massachusetts, where both apply, the more protective standard controls. This principle is important for exam questions that present conflicting requirements.',
            },
            {
              question: 'What is the non-refundable application fee for the 3A restriction class?',
              options: ['$25', '$50', '$75', '$100'],
              correctIndex: 2,
              explanation: 'The fee is $75 per restriction class and is non-refundable even if the exam is failed or the application is denied. Applicants for multiple restrictions pay $75 for each class.',
            },
          ],
        },
        {
          id: '3a-m1-s2',
          title: 'Licensing',
          durationHours: 1.5,
          learningObjectives: [
            'List the application steps and documentation required for a 3A hoisting license',
            'Explain the role of the MA Division of Occupational Licensure in issuing and enforcing 3A licenses',
            'Identify which pile driving, derrick, and cableway operations legally require a 3A license',
            'Describe employer obligations when hiring 3A-licensed operators',
          ],
          topics: [
            'MA Division of Occupational Licensure (DOL) — licensing authority',
            'Application process: online application, photo ID, fee, exam scheduling',
            'Exam content for 3A: regulations, equipment, safety, rigging, signals',
            'Operations requiring a 3A license: pile driving in construction, fixed derrick lifts, cableway operation',
            'Restriction class 3A versus other restriction classes (e.g., 1C crane, 2A excavating)',
            'Employer duty to verify license before assigning operators',
            'License must be on person or immediately available during operation',
            'License suspension and revocation: grounds and process under MGL Chapter 146',
            'Operating under a suspended license — additional penalties',
          ],
          resources: [
            {
              label: 'Apply for a Hoisting Engineer License (mass.gov)',
              url: 'https://www.mass.gov/how-to/apply-for-a-hoisting-engineer-license',
              type: 'reference',
              required: true,
            },
            {
              label: 'MGL Chapter 146 — Full Text',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146',
              type: 'regulation',
              required: true,
            },
            {
              label: 'Education Requirements for Hoisting Engineer License (mass.gov)',
              url: 'https://www.mass.gov/info-details/education-requirements-for-hoisting-engineer-license',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'Which Massachusetts agency issues the 3A hoisting engineer license?',
              options: [
                'Massachusetts Department of Public Safety',
                'Massachusetts Division of Occupational Licensure (DOL)',
                'Massachusetts Department of Labor Standards',
                'Massachusetts Office of Consumer Affairs and Business Regulation',
              ],
              correctIndex: 1,
              explanation: 'The MA Division of Occupational Licensure (DOL) administers all hoisting engineer licenses. Know this agency name — exam questions may test whether you can identify the correct licensing authority.',
            },
            {
              question: 'A contractor assigns an operator to drive piles with a diesel hammer on a construction site. The operator holds only a 2A (excavating machinery) license. Is this legal?',
              options: [
                'Yes, because pile drivers are also ground-engaging equipment',
                'No, pile driving requires a separate 3A restriction class',
                'Yes, if a licensed 3A operator is present to supervise',
                'Yes, as long as the operator has five years of experience',
              ],
              correctIndex: 1,
              explanation: 'Pile driving is covered under restriction class 3A, not 2A. Each restriction class covers specific equipment — holding one class does not authorize operation of equipment in another class.',
            },
            {
              question: 'Where must a 3A license be during machine operation?',
              options: [
                'Posted on the machine cab',
                'On the operator\'s person or immediately available',
                'Filed at the general contractor\'s office',
                'No requirement — the license is kept at home',
              ],
              correctIndex: 1,
              explanation: 'The operator must have the license on their person or immediately available for inspection during operation. Inspectors and compliance officers may request to see it at any time.',
            },
            {
              question: 'Which of the following is a valid ground for license suspension under MGL Chapter 146?',
              options: [
                'Working more than 10 hours per day on a construction site',
                'Operating equipment without maintaining a current inspection certificate',
                'Failing to renew on time by more than 30 days',
                'Only criminal convictions may trigger suspension',
              ],
              correctIndex: 1,
              explanation: 'MGL Chapter 146 authorizes suspension or revocation for safety violations, operating unsafe equipment, and similar regulatory violations — not only criminal offenses. Operating equipment without required inspection certificates is a citable violation.',
            },
            {
              question: 'An employer discovers their 3A pile driver operator\'s license expired last week. What is the employer\'s legal obligation?',
              options: [
                'The employer may continue operation for 30 days while the operator renews',
                'The employer must immediately remove the operator from pile driving until the license is renewed',
                'The employer only needs to notify the DOL — the operator may continue working',
                'The operator may continue if they have 10+ years of experience',
              ],
              correctIndex: 1,
              explanation: 'MGL Chapter 146 makes employers liable for knowingly using unlicensed operators. An expired license means no valid license — the operator must be immediately removed from covered operations until renewal is complete.',
            },
          ],
        },
        {
          id: '3a-m1-s3',
          title: 'Renewal',
          durationHours: 1.5,
          learningObjectives: [
            'Explain the 2-year renewal cycle and the steps for renewing a 3A license on time',
            'Summarize the civil and criminal penalties for unlicensed pile driving, derrick, and cableway operation',
            'Describe the reinstatement process after a lapsed or suspended 3A license',
            'Identify the accident reporting requirements under MGL Chapter 146',
          ],
          topics: [
            'Renewal period: every 2 years; renew before expiration to avoid lapse',
            'Online renewal process through the MA DOL portal',
            'Continuing education requirements (if any) as a condition of renewal',
            'Civil penalty for unlicensed operation: up to $500 per day per violation',
            'Criminal penalties for repeat or willful violations',
            'Employer liability for knowingly using unlicensed operators',
            'Reinstatement after lapse: re-application, potential re-examination',
            'MGL §67 — accident reporting: operators must report accidents and cooperate with investigation',
            'Insurance and bonding implications of license lapses',
          ],
          resources: [
            {
              label: 'MGL Chapter 146 §§ 64–67 — Safety, Penalties & Renewal',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146',
              type: 'regulation',
              required: true,
            },
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'What is the maximum civil penalty per day for operating a pile driver without a valid Massachusetts 3A license?',
              options: ['$100/day', '$250/day', '$500/day', '$1,000/day'],
              correctIndex: 2,
              explanation: 'MGL Chapter 146 allows civil penalties of up to $500 per day for each day of unlicensed operation. Each day of continued violation counts separately — a week of unlicensed operation could produce $3,500 in penalties.',
            },
            {
              question: 'After your 3A license expires, what is the first step to legally resume pile driving work?',
              options: [
                'Wait 60 days and then return to work',
                'File an accident report with the DOL',
                'Complete the renewal application and receive the renewed license',
                'Notify your employer in writing and continue working under their supervision',
              ],
              correctIndex: 2,
              explanation: 'There is no right to continue working during a lapse — you must renew first and receive the updated license. The 60-day wait applies only to failed exam attempts, not license renewals.',
            },
            {
              question: 'Under MGL §67, what must an operator do following an accident involving pile driving equipment that results in injury?',
              options: [
                'File a report only if a fatality occurred',
                'Report the accident as required by law and cooperate with any investigation',
                'Report only to the general contractor; the GC handles all government notifications',
                'No reporting is required if damage is under $5,000',
              ],
              correctIndex: 1,
              explanation: 'MGL §67 requires accident reporting for hoisting machinery incidents. Operators must report and cooperate with investigations — failing to report compounds any penalties and can result in license suspension.',
            },
            {
              question: 'If a 3A operator\'s license lapses for 6 months and they wish to return to pile driving work, what is most likely required?',
              options: [
                'Simply paying the $75 renewal fee',
                'Re-application to the DOL, which may include re-examination',
                'A letter from the employer attesting to continued competency',
                'Only a 30-day waiting period before the lapsed license is automatically restored',
              ],
              correctIndex: 1,
              explanation: 'A significantly lapsed license requires re-application to the DOL and may require re-examination. The DOL has discretion to require a new exam — plan ahead and renew on time to avoid this process.',
            },
            {
              question: 'Who bears legal responsibility for ensuring a pile driver operator holds a valid 3A license?',
              options: [
                'The operator alone',
                'Both the operator and the employer',
                'Only the general contractor on the project',
                'The state DOL — they enforce it independently',
              ],
              correctIndex: 1,
              explanation: 'MGL Chapter 146 places responsibility on both the operator (who must hold and carry the license) and the employer (who must verify and not knowingly assign unlicensed workers). Both may face penalties for violations.',
            },
          ],
        },
      ],
    },
    {
      id: '3a-m2',
      title: 'Equipment',
      orderInCourse: 2,
      estimatedHours: 5,
      sessions: [
        {
          id: '3a-m2-s1',
          title: 'Pile Driver Systems',
          durationHours: 2,
          learningObjectives: [
            'Identify the four major hammer types used in pile driving and state their operating principles',
            'Describe the components of a pile driving leads system (fixed and swinging)',
            'Distinguish the appropriate application of each pile type by material and driving method',
            'Explain the function of the pile template, follower, and cushion in a pile driving system',
          ],
          topics: [
            'Drop hammer: gravity-powered, simplest type; stroke height determines energy',
            'Single-acting diesel hammer: fuel ignited by compression; rated by ram weight and stroke',
            'Double-acting / differential diesel hammer: downstroke assisted by combustion gases',
            'Hydraulic hammer: variable energy settings; low vibration; preferred for sensitive sites',
            'Vibratory hammer: eccentric weights create high-frequency vibration; reduces soil friction; effective in granular soils; not for capacity verification',
            'Fixed leads: attached to crane base, hold hammer in precise alignment; required for batter piles',
            'Swinging (free) leads: suspended from crane boom tip; more flexible; allow slight misalignment',
            'Pile types: timber (round or square); pre-stressed concrete; steel H-pile; steel pipe pile; sheet pile (Z and U profiles)',
            'Pile cushion: absorbs hammer blow and protects pile head; must be replaced when compressed',
            'Hammer cushion: protects the helmet/cap; inspected every 500 blows or per manufacturer spec',
            'Pile template: guides pile to exact location during initial driving; ensures plan accuracy',
            'Follower: extension used when pile head is below leads reach; reduces accuracy; avoided when possible',
            'Pile helmet (driving cap): transmits blow evenly to pile head; matched to pile type',
            'Penetration rate and set: blows per foot tracked; final set recorded as blows per inch',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1926.603 — Pile Driving Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.603',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA Pile Driving eTool',
              url: 'https://www.osha.gov/pile-driving',
              type: 'osha',
              required: false,
            },
            {
              label: 'MA Hoisting Licensing & Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'Which pile driving hammer type works by reducing friction between the pile and soil through high-frequency vibration, rather than impact?',
              options: [
                'Drop hammer',
                'Single-acting diesel hammer',
                'Hydraulic hammer',
                'Vibratory hammer',
              ],
              correctIndex: 3,
              explanation: 'The vibratory hammer uses rotating eccentric weights to create rapid oscillations that temporarily liquefy the surrounding soil, allowing the pile to sink. It does not measure bearing capacity the way impact hammers do.',
            },
            {
              question: 'You are driving batter piles at a precise angle. Which leads type is most appropriate?',
              options: [
                'Swinging (free) leads, because they allow flexible positioning',
                'Fixed leads attached to the crane base, because they hold a precise alignment',
                'Either type — angle does not affect the choice of leads',
                'No leads are required for batter piles',
              ],
              correctIndex: 1,
              explanation: 'Fixed leads are required for batter piles because they keep the hammer and pile at a consistent angle throughout driving. Swinging leads cannot maintain the precise geometry needed for accurate batter work.',
            },
            {
              question: 'What is the primary purpose of the pile cushion in a driving system?',
              options: [
                'To lift the pile from the storage yard to the leads',
                'To absorb the hammer blow energy and protect the pile head from damage',
                'To guide the pile to the correct grid location',
                'To prevent the hammer from rising into the head block',
              ],
              correctIndex: 1,
              explanation: 'The pile cushion (between the drive cap and the pile head) absorbs impact energy and distributes it evenly to avoid spalling or cracking the pile head. It must be replaced when it compresses past the manufacturer\'s limit.',
            },
            {
              question: 'Which pile type would be best suited for a project requiring a continuous subsurface barrier to retain soil and water?',
              options: [
                'Timber pile',
                'Pre-stressed concrete pile',
                'Steel sheet pile',
                'Steel H-pile',
              ],
              correctIndex: 2,
              explanation: 'Steel sheet piles (Z or U profiles) are designed to interlock and form a continuous wall, making them ideal for cofferdams, retaining walls, and waterfront shoring. H-piles and timber piles are bearing members, not barriers.',
            },
            {
              question: 'A follower is used when driving piles. What is a key drawback of using a follower?',
              options: [
                'A follower prevents the use of a diesel hammer',
                'A follower reduces driving accuracy because it introduces misalignment between the hammer and pile',
                'A follower is only usable with vibratory hammers',
                'A follower requires a separate licensed operator',
              ],
              correctIndex: 1,
              explanation: 'Followers extend reach when the pile head is below the bottom of the leads, but they reduce energy transfer efficiency and introduce the possibility of misalignment. Engineers avoid followers whenever possible for this reason.',
            },
            {
              question: 'Final pile set is typically recorded as:',
              options: [
                'Total feet driven per shift',
                'Blows per inch during the last few inches of driving',
                'Minutes required to drive each pile',
                'The distance from the pile head to grade after driving',
              ],
              correctIndex: 1,
              explanation: 'Final set — blows per inch (or per 25 mm) — is the standard measure of pile bearing capacity. The more blows required per inch, the greater the resistance and the closer the pile is to its design capacity.',
            },
          ],
        },
        {
          id: '3a-m2-s2',
          title: 'Derricks & Cableways',
          durationHours: 1.5,
          learningObjectives: [
            'Identify the major types of fixed derricks and describe the structural role of each component',
            'Explain the operating principles of a cableway system, including traction cable and track cable functions',
            'Describe the load chart requirements for derricks under OSHA 29 CFR 1926.1436',
            'State the inspection requirements specific to guy derricks and stiff-leg derricks',
          ],
          topics: [
            'Guy derrick: vertical mast held by a minimum of 6 guys equally spaced; rotating boom; common in structural steel erection',
            'Stiff-leg (stiffleg) derrick: mast supported by two rigid legs and a base frame; does not require guys; limited rotation arc',
            'Gin pole: simple single-mast derrick used for moderate lifts; no boom; load hangs from top',
            'Chicago boom: attached to a building column or framework; boom pivots at a cleat on the structure; common in high-rise construction',
            'Mast: primary vertical structural member; carries compressive load',
            'Boom: pivoting member that positions the load horizontally; angle determines radius and rated capacity',
            'Guys (guy lines): wire ropes from mast top to anchors; carry tension that stabilizes the mast; minimum 6 for guy derricks',
            'Load chart: must show rated capacity at corresponding boom angles and operating radii; required by 1926.1436',
            'New/reinstalled derricks: tested by competent person through full range of motion before first use',
            'Derricks with capacity >6,000 lbs manufactured after Nov 8 2010 must have load-weighing or rated-capacity indicating device',
            'Cableway systems: used to transport materials across a span (rivers, valleys, job sites)',
            'Track cable (static cable): fixed cable spanning the distance; the carriage rides along it',
            'Traction cable (haul cable): moving rope that pulls the carriage and load back and forth',
            'Tower geometry: height, span, and sag determine capacity and clearance',
            'Cableway carriage: the traveling trolley; rated for a specific suspended load',
            'Operating from cableways: load must not exceed rated capacity; dynamic loading from swing must be accounted for',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1926.1436 — Derricks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1436',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926 Subpart CC — Cranes and Derricks in Construction',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926SubpartCC',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'A guy derrick requires a minimum of how many guys, equally spaced?',
              options: ['3', '4', '6', '8'],
              correctIndex: 2,
              explanation: 'OSHA 29 CFR 1926.1436 and ASME B30.6 require a minimum of 6 guys, equally spaced, for a guy derrick. Variations in spacing require approval from a qualified person. Know this number — it appears on exams.',
            },
            {
              question: 'Where must the load chart for a permanently installed derrick be located?',
              options: [
                'In the general contractor\'s office trailer',
                'Posted where it is visible to personnel responsible for operating the equipment',
                'Kept in the operator\'s possession at all times',
                'Filed with the local building department',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.1436 requires permanently installed derrick load charts to be posted visibly for the operating personnel. For non-permanent derricks, the chart must be readily available at the job site.',
            },
            {
              question: 'Which type of derrick is attached to an existing building column or framework and pivots at a cleat?',
              options: ['Guy derrick', 'Stiff-leg derrick', 'Chicago boom', 'Gin pole'],
              correctIndex: 2,
              explanation: 'The Chicago boom is mounted directly to the building structure — a cleat or bracket on a column — and the boom pivots around a limited arc. It is commonly used for hoisting materials during high-rise construction.',
            },
            {
              question: 'In a cableway system, what is the function of the track cable?',
              options: [
                'It pulls the carriage back and forth across the span',
                'It is the fixed, static cable that the carriage rides along',
                'It connects the load hook to the carriage',
                'It is the guy line that stabilizes the cableway tower',
              ],
              correctIndex: 1,
              explanation: 'The track cable (also called the static cable) spans the distance between towers and serves as the rail for the carriage. The traction (haul) cable moves the carriage. Knowing the difference between these two cables is a common exam topic.',
            },
            {
              question: 'A new guy derrick has just been assembled on a construction site. Before placing any loads, what must occur?',
              options: [
                'The operator must drive the derrick under a test load for 30 minutes',
                'A competent person must test the derrick through its full range of motion with no hook load',
                'The general contractor must sign off on the assembly log',
                'No pre-use testing is required if the derrick was used on a prior project',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.1436 requires new or reinstalled derricks to be tested by a competent person through the full operational range — raising/lowering the hook, full boom travel, full swing range — with no load before first use. Documentation is required.',
            },
          ],
        },
        {
          id: '3a-m2-s3',
          title: 'Rigging',
          durationHours: 1.5,
          learningObjectives: [
            'Apply wire rope inspection and removal criteria per OSHA 29 CFR 1926.1413 to 3A equipment',
            'Calculate the effect of sling angle on the tension in each leg of a two-leg bridle hitch',
            'Identify the correct hardware components — shackles, hooks, blocks, and sheaves — used in pile driving and derrick rigging',
            'Describe the daily rigging inspection required before pile driving and derrick operations',
          ],
          topics: [
            'Wire rope construction: strands, wires, core (IWRC vs. fiber); designations such as 6×19 and 6×37',
            'Wire rope inspection: mandatory before each shift; look for broken wires, corrosion, kinking, bird-caging, core failure',
            'Removal criteria (OSHA 1926.1413 / Subpart CC running ropes): 6 randomly distributed broken wires in one rope lay, or 3 in one strand in one lay',
            'Standing/pendant rope removal: more than 2 broken wires in one lay beyond end connections; more than 1 at an end connection',
            'Rope diameter reduction: remove from service if diameter is reduced by more than 1/3 of the nominal diameter (per ASME standards)',
            'Sling types: wire rope, chain, synthetic web, round sling — each with rated capacities',
            'Sling angle effect: as the angle from horizontal decreases, tension in each sling leg increases; at 30° the load per leg is approximately 2× the load at 90°',
            'Shackles: bolt-type vs. screw-pin; load rated in tons; pin must be moused or secured when under load',
            'Wire rope clips (Crosby clips): U-bolt over the dead end, not the live end; "never saddle a dead horse"',
            'Blocks and sheaves: sheave diameter must match wire rope diameter; worn grooves cause accelerated rope wear',
            'Load block (running block) vs. head block (fixed block): understanding reeving arrangements',
            'Guy wire inspection: daily inspection of tension, condition, and anchor security per 230 CMR 6.00 and OSHA 1926.1436',
            'Anti-two-block devices: prevent the load block from striking the head block; required by Subpart CC for equipment where provided',
            'Pre-lift rigging check: verify load weight, center of gravity, rigging rated capacity, and clear lift path',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1926.1413 — Wire Rope Inspection (Subpart CC)',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1413',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.1436 — Derricks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1436',
              type: 'osha',
              required: true,
            },
            {
              label: 'SAE J1307 Hand Signals — Quick Reference Guide',
              url: '/hand-signals',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'Under OSHA 1926.1413, how many randomly distributed broken wires in one rope lay of a running wire rope require removal from service?',
              options: ['3', '6', '10', '12'],
              correctIndex: 1,
              explanation: '6 randomly distributed broken wires in one rope lay (or 3 in one strand in one lay) is the removal threshold for running ropes under Subpart CC. This is one of the most frequently tested wire rope facts on hoisting exams.',
            },
            {
              question: 'When installing a wire rope clip, the U-bolt of the clip must be placed over which part of the rope?',
              options: [
                'The live (standing) end of the rope',
                'The dead (short/tail) end of the rope',
                'Either end — orientation does not matter',
                'Wire rope clips are not approved for use on pile driving equipment',
              ],
              correctIndex: 1,
              explanation: 'The U-bolt bears the bending stress, so it must go over the dead end. "Never saddle a dead horse" is the memory aid: the saddle (base plate) sits on the live end. Reversed clips can reduce rope strength by up to 40%.',
            },
            {
              question: 'A two-leg wire rope bridle is used to lift a load. As the included angle between the sling legs increases (legs spread further apart), what happens to the tension in each leg?',
              options: [
                'Tension decreases as the angle increases',
                'Tension increases as the angle increases',
                'Tension is not affected by sling angle',
                'Tension increases only if the load weight exceeds 1,000 lbs',
              ],
              correctIndex: 1,
              explanation: 'As sling legs spread apart (larger included angle = smaller angle from horizontal), each leg must exert more force to support the same load. At 30° from horizontal, each leg carries nearly 2× the load vs. 90°. Always minimize sling angle spread.',
            },
            {
              question: 'During a daily guy wire inspection before derrick operations, you find one guy has significantly more sag than the others. What should you do?',
              options: [
                'Proceed — slight variation in guy tension is normal',
                'Stop operations and correct the guy tension before use',
                'Reduce the load to 50% of rated capacity and proceed',
                'Use only the remaining guys and remove the slack one',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.1436 requires daily guy tension verification. Unequal tension means the derrick mast is not properly supported — proceeding risks overloading the tight guys and destabilizing the structure. Correct tension before any lifts.',
            },
            {
              question: 'What condition in a wire rope is called "bird-caging"?',
              options: [
                'Broken outer wires that are visible on the surface of the rope',
                'Separation and expansion of the strands and wires caused by a sudden shock load or overload',
                'Corrosion visible at the contact points between strands',
                'Reduction in diameter along a section of the rope',
              ],
              correctIndex: 1,
              explanation: 'Bird-caging occurs when the rope\'s outer strands separate and flare outward — often caused by a sudden release of tension or shock load. A bird-caged rope has permanently distorted geometry and must be removed from service immediately.',
            },
            {
              question: 'Before any lift with a derrick, the operator should verify which of the following?',
              options: [
                'The load weight, center of gravity, rigging rated capacity, and that the lift path is clear',
                'Only that the rigging hardware is free of visible cracks',
                'Only that the load is within the maximum rated capacity shown on the load chart',
                'The weather forecast for the next 12 hours',
              ],
              correctIndex: 0,
              explanation: 'A proper pre-lift check covers: confirmed load weight, estimated center of gravity, rated capacity of all rigging components, and a clear lift path with no personnel underneath. All four elements are required — missing any one creates a serious hazard.',
            },
          ],
        },
      ],
    },
    {
      id: '3a-m3',
      title: 'Operation',
      orderInCourse: 3,
      estimatedHours: 5,
      sessions: [
        {
          id: '3a-m3-s1',
          title: 'Safety',
          durationHours: 2,
          learningObjectives: [
            'Identify the primary hazards specific to pile driving, derrick, and cableway operations',
            'Apply the power line safety rules of OSHA 29 CFR 1926.1408 to 3A equipment operations',
            'Explain ground and load condition requirements before driving piles or making lifts with a derrick',
            'Describe the controls required for noise and vibration hazards during pile driving operations',
          ],
          topics: [
            'Overhead power line hazard: most common fatal accident cause for derricks and pile rigs',
            'OSHA 1926.1408 minimum clearance: 20 feet from energized power lines up to 350 kV during equipment operations',
            'For lines over 350 kV: minimum clearance increases; utility owner must establish minimum approach distance',
            'Encroachment prevention: spotters, proximity alarms, or insulating barriers required',
            'Ground conditions: load-bearing capacity of soil must support pile rig weight plus dynamic pile driving forces',
            'Mat or crane pad requirements when operating on soft or unstable ground',
            'Batter pile stability: inclined driving creates lateral forces; leads and rig must be checked for stability',
            'Rig tipover hazards: never travel with hammer raised high in the leads',
            'Two-blocking (two-blocking hazard): load block contacts head block; can part the wire rope instantly',
            'Stop block requirement per 1926.603: prevents hammer from being raised into the head block',
            'Blocking device: must be placed under the hammer whenever employees are working beneath it',
            'Noise hazards: pile driving exceeds 100 dB(A); hearing protection required; OSHA permissible noise exposures apply',
            'Vibration effects: ground vibration can damage adjacent structures and utilities; pre-construction survey recommended',
            'Blowout hazard: steel pipe piles driven open-end may eject soil or water under pressure',
            'Pit walls and jacked pile access: walls must be sloped or sheeted and braced; access pits need ladders and curbs',
            'Hydrogen sulfide (H2S) awareness: disturbed soils may release hazardous gases during pile installation',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1926.1408 — Power Line Safety (up to 350 kV)',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1408',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.603 — Pile Driving Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.603',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.1436 — Derricks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1436',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'Under OSHA 1926.1408, what is the minimum clearance distance between pile driving equipment and an energized power line rated up to 350 kV during operations?',
              options: ['10 feet', '15 feet', '20 feet', '50 feet'],
              correctIndex: 2,
              explanation: '20 feet is the minimum clearance for power lines up to 350 kV during equipment operations. For lines over 350 kV, the distance increases and must be established by the utility owner. This is among the most important safety numbers on the 3A exam.',
            },
            {
              question: 'A pile driving hammer must never be raised against the head block. Which component is specifically required by OSHA 1926.603 to prevent this?',
              options: [
                'An anti-two-block device with audible alarm',
                'Stop blocks installed on the leads',
                'A proximity sensor on the hammer',
                'A written pre-operational checklist',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.603 specifically requires stop blocks in the leads to prevent the hammer from rising into the head block. In addition, a blocking device capable of safely supporting the hammer weight must be placed under the hammer when workers are below it.',
            },
            {
              question: 'Employees need to work beneath a pile driving hammer that has been temporarily halted. What is the required safety measure?',
              options: [
                'Post a spotter to warn workers if the hammer moves',
                'Place a blocking device capable of supporting the hammer weight under it before work proceeds',
                'Lower the hammer completely to grade before any worker goes underneath',
                'Require all workers below to wear hard hats with chinstraps',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.603 requires a blocking device placed under the hammer at all times while employees are working beneath it. Relying on brakes or a spotter alone is not compliant — a physical block is required.',
            },
            {
              question: 'Pile driving noise typically exceeds which decibel level, requiring mandatory hearing protection?',
              options: ['85 dB(A)', '90 dB(A)', '100 dB(A)', '115 dB(A)'],
              correctIndex: 1,
              explanation: 'OSHA\'s permissible noise exposure limit for an 8-hour shift is 90 dB(A). Pile driving routinely exceeds this, so hearing protection is required. At higher exposures (above 115 dB), any unprotected exposure is prohibited regardless of duration.',
            },
            {
              question: 'You are operating a pile driver on soft, recently filled ground. What action should you take before beginning operations?',
              options: [
                'Begin driving immediately — the weight of the pile will stabilize the ground',
                'Verify that the ground bearing capacity can support the rig weight plus dynamic driving forces; use mats or crane pads if needed',
                'Reduce the pile driving energy by 50% to limit ground disturbance',
                'Only proceed if a geotechnical engineer is on site at all times',
              ],
              correctIndex: 1,
              explanation: 'Ground conditions must be assessed before any pile rig setup. Soft or filled ground may require timber mats or crane pads to distribute the rig\'s weight. A rig tipover on soft ground is a life-safety event — verify bearing capacity first.',
            },
            {
              question: 'An operator is hoisting a pile into the leads. Ground personnel must stay clear during this operation primarily because:',
              options: [
                'Noise from the crane exceeds safe exposure limits during hoisting',
                'A swinging or dropped pile can kill or seriously injure anyone in the fall or swing zone',
                'The pile exhaust fumes are concentrated near the rig during hoisting',
                'OSHA requires a 5-foot exclusion zone during all crane operations',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.603 specifically requires that employees be kept clear while piling is being hoisted. A long, heavy pile swinging on a crane line is an uncontrolled hazard — exclusion zones must be enforced until the pile is stable in the leads.',
            },
          ],
        },
        {
          id: '3a-m3-s2',
          title: 'Inspections',
          durationHours: 1.5,
          learningObjectives: [
            'List the pre-shift inspection items required for a pile driving rig under 230 CMR 6.00 and OSHA 1926.603',
            'Describe the inspection schedule and documentation requirements for derricks under OSHA 1926.1436',
            'Identify the removal-from-service criteria for wire rope, boiler components, and rigging hardware',
            'Explain the process for documenting and reporting equipment defects found during inspection',
          ],
          topics: [
            'Daily (pre-shift) inspection required by 520/230 CMR 6.09: all pile driving equipment inspected before start of work',
            'Pile driving inspection items: leads, stop blocks, hammer, cushions, hoses/safety chains, boiler/pressure vessel, steam/air lines',
            'Steam and air hose safety chain: at least 1/4-inch diameter chain or cable securing each steam or air hose to the hammer',
            'Two shutoff valves required on steam lines to the hammer: one must be a quick-acting lever type within easy reach of the operator',
            'Boiler inspections: must meet ASME Power Boilers (Section I) standards; annually certified',
            'Derrick daily inspection: check guy tension, wire rope, shackles, hook, blocks, boom connections, mast foot',
            'Derrick annual inspection: gudgeon pin (cracks, wear, distortion); foundation support capacity',
            'Cableway inspection: track cable condition and sag, traction cable, carriage wheels and connections, tower anchorage',
            'Wire rope removal criteria: 6 broken wires in one lay (running rope); rope diameter reduction; kinking; bird-caging; corrosion',
            'Chain sling inspection: stretch (>3% elongation), cracks, nicks, gouges, deformed links — remove from service',
            'Hook inspection: throat opening, twist, cracks; latch must function properly',
            'Documentation: defects found must be logged; unsafe equipment must be tagged out and repaired before use',
            'Tag-out procedure: equipment with known defects must be tagged "Do Not Operate" and removed from service',
            'Return to service: only after defect is corrected and verified by a competent person',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1926.603 — Pile Driving Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.603',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.1413 — Wire Rope Inspection',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1413',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.1436 — Derricks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1436',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'Under 230 CMR 6.09, how frequently must all pile driving equipment be inspected?',
              options: ['Weekly', 'Monthly', 'Daily before the start of work', 'After each pile is driven'],
              correctIndex: 2,
              explanation: '230 CMR 6.09 requires daily inspection of all pile driving equipment before work begins. The licensed operator is responsible for conducting and documenting this inspection, and unsafe conditions must be corrected before any operation begins.',
            },
            {
              question: 'OSHA 1926.603 requires steam or air hoses on pile driving equipment to be secured to the hammer with a minimum chain or cable diameter of:',
              options: ['1/8 inch', '3/16 inch', '1/4 inch', '3/8 inch'],
              correctIndex: 2,
              explanation: 'OSHA 1926.603 requires at least 1/4-inch diameter chain or cable to secure steam and air hoses to the hammer, preventing whipping if the hose joint fails. This minimum size is a frequently tested specific number.',
            },
            {
              question: 'A steam line to a pile driving hammer requires how many shutoff valves, and what type must one of them be?',
              options: [
                'One valve, any type',
                'Two valves; one must be a quick-acting lever type within easy reach of the operator',
                'Two valves; both must be ball valves',
                'Three valves; one must be remotely operated',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.603 requires two shutoff valves on steam lines, and one must be a quick-acting lever type within easy reach of the operator so the line can be shut immediately in an emergency.',
            },
            {
              question: 'During a pre-shift inspection of a guy derrick, you notice one guy wire has visible kinking. What is the correct action?',
              options: [
                'Straighten the kink and continue operations',
                'Reduce the load to 75% of rated capacity',
                'Remove the rope from service and replace it before operations begin',
                'Tag the rope and inspect it again at the end of the shift',
              ],
              correctIndex: 2,
              explanation: 'Kinking is a removal-from-service condition. A kinked rope has permanently damaged internal wire geometry — its strength is compromised even after straightening. Replace the rope before any operations proceed.',
            },
            {
              question: 'A derrick hook shows that the throat opening has spread by more than 15% from its original dimension. What action is required?',
              options: [
                'The hook is acceptable if no cracks are visible',
                'The hook must be removed from service immediately',
                'The hook can be used for loads up to 50% of its rated capacity',
                'Reduce the hook\'s rating and stamp the new capacity on it',
              ],
              correctIndex: 1,
              explanation: 'A hook with a throat opening spreading beyond 15% of the original size is deformed and must be removed from service. Deformed hooks cannot be rerated or repaired in the field — replace the hook.',
            },
            {
              question: 'Equipment with a defect found during inspection must be:',
              options: [
                'Repaired when convenient, but may continue operating at reduced capacity',
                'Tagged "Do Not Operate" and removed from service until the defect is corrected and verified by a competent person',
                'Only restricted from use if the defect involves the load-bearing system',
                'Reported to the DOL within 24 hours but may continue operating',
              ],
              correctIndex: 1,
              explanation: 'Any unsafe defect found in inspection requires an immediate tag-out and removal from service. The equipment may not return to service until the defect is corrected and a competent person verifies it is safe to operate.',
            },
          ],
        },
        {
          id: '3a-m3-s3',
          title: 'Signals',
          durationHours: 1.5,
          learningObjectives: [
            'State the SAE standard that governs hand signals for pile driving and derrick equipment under 230 CMR 6.00',
            'Identify who may act as a signaler for a pile driver or derrick operator under Massachusetts regulations',
            'Demonstrate the correct response when an operator loses sight of the signaler during an operation',
            'Describe the use of radio communication as a supplement or substitute for hand signals',
          ],
          topics: [
            'SAE J1307 hand signal standard: required by 230 CMR 6.00 for pile driving and derrick operations',
            'Approved signaler: only one designated person may direct the operator; no one else may give movement signals',
            'Signaler qualifications: must be knowledgeable of the signals and in a safe position with full view of the operation',
            'Stop signal: any person on site may give an emergency stop; operator must obey it immediately',
            'Loss of visual contact rule: if operator cannot see the signaler, all movement must stop immediately',
            'Conflicting signals: if conflicting signals are received, the operator stops until the conflict is resolved; Emergency Stop from either person is always obeyed',
            'Radio / electronic communication: may be used as an alternative to hand signals when both operator and signaler agree; one speaker at a time; "go ahead" protocol',
            'Signal clarity: signaler must be visible and use distinct, unambiguous motions',
            'Dedicated signaler rule: while acting as signaler, that person may not perform other tasks',
            'Common hand signals to know: Hoist, Lower, Stop, Emergency Stop, Swing, Travel, Raise Boom, Lower Boom, Extend Boom, Retract Boom',
            'Internal reference for visual review of all standard signals',
          ],
          resources: [
            {
              label: 'SAE J1307 Hand Signals — Quick Reference Guide',
              url: '/hand-signals',
              type: 'reference',
              required: true,
            },
            {
              label: '230 CMR 6.00 — Hoisting Machinery Regulations',
              url: 'https://www.mass.gov/regulations/230-CMR-600-hoisting-machinery',
              type: 'regulation',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'Under 230 CMR 6.00, which SAE standard specifies the required hand signals for pile driving and derrick operations?',
              options: ['SAE J386', 'SAE J1307', 'SAE J765', 'SAE J237'],
              correctIndex: 1,
              explanation: 'SAE J1307 is the required hand signal standard for hoisting machinery under 230 CMR 6.00. SAE J386 covers seat belts, J765 covers roll-over protection for rough-terrain forklifts, and J237 covers braking — not signals.',
            },
            {
              question: 'During pile driving operations, the designated signaler steps behind a concrete barrier and is no longer visible to the operator. What must the operator do?',
              options: [
                'Slow all movements and proceed with caution',
                'Switch to radio communication immediately',
                'Stop all machine movement immediately until visual contact with the signaler is restored',
                'Ask the nearest worker to relay the signaler\'s hand signals',
              ],
              correctIndex: 2,
              explanation: '230 CMR 6.00 requires the operator to stop all movement immediately if the signaler is not visible. No relay system, radio switch, or reduced-speed workaround satisfies this requirement — stop and wait.',
            },
            {
              question: 'A worker who is NOT the designated signaler spots an immediate danger and gives the Emergency Stop signal. What must the operator do?',
              options: [
                'Ignore the signal — only the designated signaler\'s signals are valid',
                'Stop if convenient, then check with the designated signaler',
                'Obey the Emergency Stop immediately, regardless of who gave it',
                'Continue the current movement to a safe stopping point before stopping',
              ],
              correctIndex: 2,
              explanation: 'The Emergency Stop signal must be obeyed immediately, from any person on the site. Only the Emergency Stop overrides the "designated signaler only" rule — for all other movements, only the approved signaler directs the operator.',
            },
            {
              question: 'While the designated signaler is directing a derrick lift, the site superintendent approaches and begins giving competing hand signals. What is the correct operator response?',
              options: [
                'Follow the superintendent\'s signals, as they have overall site authority',
                'Follow whichever signal the operator judges to be safer',
                'Stop the lift and do not resume until it is determined who the designated signaler is',
                'Follow the signaler\'s signals and ignore the superintendent',
              ],
              correctIndex: 2,
              explanation: 'Conflicting signals require the operator to stop. Only after the conflict is resolved and a single approved signaler is clearly established should operations resume. Following the "higher authority" is not permitted — the regulation designates one signaler only.',
            },
            {
              question: 'When using radio communication as a substitute for hand signals, which protocol must be followed?',
              options: [
                'Both the operator and signaler may speak at the same time for efficiency',
                'Only one person speaks at a time; the other acknowledges before the speaker directs any movement',
                'Radio communication is not permitted under 230 CMR 6.00 — hand signals only',
                'The operator may use radio for hoisting but must use hand signals for all other movements',
              ],
              correctIndex: 1,
              explanation: 'Radio communication is permitted as an alternative, but both parties must follow strict one-speaker-at-a-time protocol to prevent miscommunication. The operator acknowledges each direction before executing it — simultaneous transmission defeats the purpose of the communication system.',
            },
          ],
        },
      ],
    },
    {
      id: '3a-m4',
      title: 'Review',
      orderInCourse: 4,
      estimatedHours: 5,
      sessions: [
        {
          id: '3a-m4-s1',
          title: 'OSHA',
          durationHours: 2,
          learningObjectives: [
            'Integrate the key requirements of 29 CFR 1926.603, 1926.1436, and Subpart CC as they apply to 3A operations',
            'Identify the most frequently cited OSHA violations in pile driving and derrick operations',
            'Apply OSHA competent person and qualified person definitions to 3A job-site scenarios',
            'Explain OSHA\'s multi-employer worksite doctrine and how it affects 3A operators and employers',
          ],
          topics: [
            'OSHA 29 CFR 1926.603 key requirements summary: boilers, hose safety chains (min. 1/4 inch), stop blocks, blocking device, leads, overhead protection (2-inch planking equiv.)',
            'OSHA 29 CFR 1926.1436 key requirements summary: derrick types, load chart, pre-use testing, guy derrick minimum 6 guys, capacity indicator (>6,000 lbs post Nov 2010)',
            'Subpart CC operator qualification: employers must train each derrick operator on equipment they will operate',
            'Competent person: one who can identify existing and predictable hazards and has authority to correct them',
            'Qualified person: one with recognized degree, certificate, professional standing, or extensive knowledge/training to solve the problem at hand',
            'OSHA multi-employer worksite: controlling employer, creating employer, exposing employer, and correcting employer each have distinct duties',
            'Top OSHA citations in pile driving: failure to use safety chains on hose connections; lack of stop blocks; employees within swing/fall zone',
            'Top OSHA citations in derrick work: missing or outdated load charts; failed pre-use testing; improper wire rope inspection',
            'OSHA 1926.1408 power line minimum clearance: 20 feet (up to 350 kV) — applies to all 3A equipment',
            'Recordkeeping: pre-use test records must be retained until derrick is retested or dismantled',
            'OSHA General Duty Clause: employers must provide a workplace free from recognized hazards likely to cause death or serious injury even where no specific standard exists',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1926.603 — Pile Driving Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.603',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926 Subpart CC — Cranes and Derricks in Construction',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926SubpartCC',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.1408 — Power Line Safety (up to 350 kV)',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1408',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'Under OSHA 1926.1436, a derrick manufactured after November 8, 2010 with a rated capacity exceeding 6,000 pounds must be equipped with which of the following?',
              options: [
                'A two-block detection system with audible alarm only',
                'A load-weighing device, load moment indicator, rated capacity indicator, or rated capacity limiter',
                'A certified load test certificate renewed annually',
                'An automatic safety shutoff that stops all operations when capacity is reached',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.1436 requires one of four load-indicating or limiting devices for derricks over 6,000 lbs capacity manufactured after November 8, 2010. Older derricks are grandfathered from this specific requirement but must still comply with all other provisions.',
            },
            {
              question: 'On a multi-employer construction site, a pile driving contractor\'s operator is exposed to an unguarded trench edge created by the excavation subcontractor. Under OSHA\'s multi-employer doctrine, which type of employer is the pile driving contractor in this scenario?',
              options: [
                'Creating employer',
                'Controlling employer',
                'Exposing employer',
                'Correcting employer',
              ],
              correctIndex: 2,
              explanation: 'The exposing employer is the one whose employees are exposed to the hazard — even if they did not create it. The pile driving contractor must take reasonable steps to protect their employees, such as instructing them to avoid the area or requesting abatement.',
            },
            {
              question: 'What does "competent person" mean in the OSHA context, as applied to 3A operations?',
              options: [
                'A person with a professional engineering license',
                'A person capable of identifying existing and predictable hazards who has authority to take corrective action',
                'Any licensed 3A operator with five years of experience',
                'A person designated by the general contractor as the safety officer',
              ],
              correctIndex: 1,
              explanation: 'OSHA\'s "competent person" definition is about two things: the ability to identify hazards AND the authority to correct them. A competent person does not need a PE license but must have the knowledge and authority to act. This distinction appears frequently on licensing exams.',
            },
            {
              question: 'A derrick pre-use test was conducted and documented. How long must this record be retained?',
              options: [
                '30 days',
                '1 year',
                'Until the derrick is retested or dismantled, whichever occurs first',
                'For the life of the contractor\'s insurance policy',
              ],
              correctIndex: 2,
              explanation: 'OSHA 1926.1436 requires pre-use test documentation to be retained until the derrick is re-tested or dismantled — not merely for a fixed time period. The record must include the date, test results, and the name of the tester.',
            },
            {
              question: 'A pile driving hose connection coupling suddenly fails and the hose begins whipping. What equipment was required to prevent this hazard under OSHA 1926.603?',
              options: [
                'A pressure relief valve on the steam supply line',
                'Safety chains or equivalent at each hose connection',
                'A rubber sleeve over each connection point',
                'Hose connections are not regulated by 1926.603',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.603 requires safety chains or equivalent means at each hose connection to prevent the line from thrashing if a coupling disconnects. A whipping steam or air hose can cause fatal injuries — the physical restraint is mandatory.',
            },
            {
              question: 'OSHA\'s General Duty Clause requires employers to:',
              options: [
                'Follow only the specific OSHA standards that apply to their industry',
                'Provide a workplace free from recognized hazards likely to cause death or serious injury, even if no specific standard addresses the hazard',
                'File a hazard report with OSHA before starting pile driving work',
                'Hire only union-certified operators for pile driving operations',
              ],
              correctIndex: 1,
              explanation: 'The General Duty Clause fills gaps in OSHA standards — if a recognized hazard exists and no specific standard addresses it, the employer is still obligated to protect employees. OSHA uses it to cite employers for hazards not explicitly covered by a specific regulation.',
            },
          ],
        },
        {
          id: '3a-m4-s2',
          title: 'Practice 1',
          durationHours: 1.5,
          learningObjectives: [
            'Apply 3A regulatory knowledge to realistic job-site scenarios testing licensing and inspection rules',
            'Identify common misconceptions about pile driving safety requirements that may appear as exam distractors',
            'Demonstrate ability to select the correct action under time pressure typical of the licensing exam',
            'Integrate knowledge from Modules 1 and 2 into multi-step decision-making questions',
          ],
          topics: [
            'Review: MGL Chapter 146 licensing requirements for pile driving, derricks, and cableways',
            'Review: 230 CMR 6.00 operating rules — signaler, exclusion zones, lead conditions',
            'Review: 3A exam structure — 70% passing score, 60-day wait after failure, $75 fee',
            'Scenario drill: determining when a 3A license is required vs. another class',
            'Scenario drill: pre-shift inspection pass/fail decisions for pile driving equipment',
            'Scenario drill: stop-block and hammer-blocking device requirements',
            'Scenario drill: wire rope inspection — identifying removal criteria from descriptions',
            'Common exam distractors: wrong regulations cited, wrong thresholds, wrong equipment types',
            'Pile type selection scenarios: matching pile type to soil and structural requirements',
            'Hammer type selection: when to use vibratory vs. impact; limitations of each',
          ],
          resources: [
            {
              label: 'MGL Chapter 146 §53 — Licensing requirement',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146/Section53',
              type: 'regulation',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.603 — Pile Driving Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.603',
              type: 'osha',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'A licensed 1C crane operator is assigned to operate a Chicago boom derrick on a high-rise project. Is this permitted?',
              options: [
                'Yes, because a Chicago boom is simply an attachment to a crane',
                'No, a Chicago boom is a fixed derrick requiring a 3A license',
                'Yes, if the Chicago boom is rated under 10,000 lbs',
                'Yes, if a licensed 3A operator is present to supervise',
              ],
              correctIndex: 1,
              explanation: 'A Chicago boom is explicitly listed as a fixed derrick type under OSHA 1926.1436. Operating it requires the appropriate license for derricks (3A in Massachusetts) — a crane restriction class (1C) does not cover fixed derricks.',
            },
            {
              question: 'During a pre-shift inspection, you find that one of the six guys on a guy derrick has been accidentally cut, leaving only five. May operations proceed?',
              options: [
                'Yes, at 50% of rated capacity with the remaining five guys',
                'Yes, if the five remaining guys are re-tensioned by a competent person',
                'No, operations must be suspended until the derrick is repaired and has all required guys',
                'Yes, for light picks only (under 1,000 lbs)',
              ],
              correctIndex: 2,
              explanation: 'The minimum number of guys for a guy derrick is 6, equally spaced. Operating with fewer than six is a direct violation of OSHA 1926.1436 and creates a structural instability risk. Operations must stop until the derrick is repaired.',
            },
            {
              question: 'You discover 7 randomly distributed broken wires in a single rope lay of the crane hoist rope on a pile driving rig. The correct action is:',
              options: [
                'Continue operations — 7 broken wires in a lay is within limits',
                'Remove the rope from service immediately — 6 broken wires is the threshold',
                'Reduce the load to 80% of rated capacity and continue',
                'Report the condition to the supervisor and await instructions before continuing',
              ],
              correctIndex: 1,
              explanation: '6 randomly distributed broken wires in one rope lay is the removal threshold under OSHA 1926.1413. With 7, the threshold is exceeded — the rope must be removed immediately. Do not continue or reduce load; replace the rope.',
            },
            {
              question: 'An operator drives a pile near an energized 230 kV power line. What is the minimum required clearance?',
              options: ['10 feet', '15 feet', '20 feet', '35 feet'],
              correctIndex: 2,
              explanation: '20 feet is the minimum clearance for lines up to 350 kV under OSHA 1926.1408. 230 kV falls under this threshold, so 20 feet applies. For voltages over 350 kV, the distance increases based on the utility\'s specifications.',
            },
            {
              question: 'A vibratory hammer is used to install steel sheet piles on a waterfront project. The engineer asks for a pile bearing capacity verification. Can the vibratory hammer provide this?',
              options: [
                'Yes, the number of vibration cycles per inch indicates capacity',
                'Yes, vibratory hammers are more accurate than impact hammers for capacity',
                'No, vibratory hammers cannot be used for capacity verification — an impact hammer is required',
                'No, only a load test after installation can verify capacity',
              ],
              correctIndex: 2,
              explanation: 'Vibratory hammers reduce soil friction through liquefaction but do not deliver measurable impact energy that can be correlated to bearing capacity. Impact hammers (drop, diesel, or hydraulic) are required for driving formulas and dynamic pile testing.',
            },
            {
              question: 'After failing the 3A hoisting exam, a candidate wants to retest as soon as possible. When may they retake the exam?',
              options: ['After 7 days', 'After 30 days', 'After 60 days', 'After 90 days'],
              correctIndex: 2,
              explanation: 'Massachusetts requires a 60-day waiting period after a failed hoisting exam before retesting. This applies to all restriction classes, including 3A. Use this time to study the specific areas where you scored poorly.',
            },
          ],
        },
        {
          id: '3a-m4-s3',
          title: 'Practice 2',
          durationHours: 1.5,
          learningObjectives: [
            'Demonstrate mastery of derrick and cableway operation rules in scenario-based questions',
            'Apply signaling rules, rigging principles, and safety protocols from Modules 2 and 3 under exam conditions',
            'Identify the correct regulatory citation for key pile driving and derrick requirements',
            'Self-assess readiness for the 3A exam and identify remaining study gaps',
          ],
          topics: [
            'Review: OSHA 1926.1436 derrick requirements — load charts, pre-use testing, guy count, capacity devices',
            'Review: SAE J1307 signals — approved signaler, emergency stop, loss-of-visual-contact rule',
            'Review: rigging — sling angles, wire rope removal criteria, clip orientation, daily rigging inspection',
            'Review: inspection schedules — daily pile rig, daily guy tension, annual gudgeon pin',
            'Review: hose safety chains (1/4 inch minimum), two shutoff valves on steam lines',
            'Scenario drill: derrick load chart disputes and load chart placement requirements',
            'Scenario drill: multi-employer scenarios — identifying exposing, creating, and correcting employers',
            'Scenario drill: tag-out decisions after inspection defects are found',
            'Scenario drill: cableway carriage load limits and overload consequences',
            'Exam strategy: cross-checking your answer against the most protective standard',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1926.1436 — Derricks',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.1436',
              type: 'osha',
              required: true,
            },
            {
              label: 'SAE J1307 Hand Signals — Quick Reference Guide',
              url: '/hand-signals',
              type: 'reference',
              required: true,
            },
            {
              label: 'MGL Chapter 146 — Full Text',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146',
              type: 'regulation',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'A stiff-leg derrick does not have any guy wires. How is its mast stabilized?',
              options: [
                'The mast rests directly on the ground without lateral support',
                'Two rigid compression legs (stiff legs) and a base frame provide lateral support',
                'The mast is bolted to the building structure at mid-height and top',
                'Wire rope pendants from the boom tip back to ground anchors stabilize it',
              ],
              correctIndex: 1,
              explanation: 'A stiff-leg derrick uses two rigid diagonal members (stiff legs) connected to a base frame to provide the lateral stability that guys provide on a guy derrick. This makes it suitable for locations where guy anchors cannot be established.',
            },
            {
              question: 'The load chart for a non-permanently installed derrick must be:',
              options: [
                'Permanently attached to the mast',
                'Filed with the building department before use',
                'Readily available at the job site for personnel responsible for the operation',
                'Submitted to OSHA before the derrick is first used',
              ],
              correctIndex: 2,
              explanation: 'OSHA 1926.1436 requires the load chart for non-permanent derricks to be readily available at the job site — not necessarily posted, but accessible to the responsible operating personnel. Permanently installed derricks must have it posted visibly.',
            },
            {
              question: 'During a cableway operation, the carriage is traveling across the span with a rated load. The operator notices the track cable sag is greater than normal. What is the most likely cause and appropriate response?',
              options: [
                'Normal cable stretch — no action needed',
                'Possible overload or cable damage; stop operations and inspect the track cable before continuing',
                'Reduce carriage speed by 50% and complete the current pass',
                'Increase tower height to reduce sag',
              ],
              correctIndex: 1,
              explanation: 'Increased sag in a track cable under a rated load indicates either overloading or cable damage (broken wires or core failure reducing tensile strength). Stop operations and inspect — a parted track cable sends the carriage and load to the ground.',
            },
            {
              question: 'Which of these is a correct statement about the dedicated signaler rule under 230 CMR 6.00?',
              options: [
                'The signaler may also perform labor tasks when the machine is idle',
                'The signaler must be dedicated to signaling and may not perform other tasks while acting as signaler',
                'The signaler may accept guidance from the site superintendent and relay it to the operator',
                'Two signalers may simultaneously direct the same operator for complex lifts',
              ],
              correctIndex: 1,
              explanation: 'While acting as signaler, that person is dedicated solely to that function. Splitting attention between signaling and other tasks creates the risk of missed or incorrect signals. The moment the signaler is needed, they must be fully focused on the operator and the load.',
            },
            {
              question: 'A contractor has a guy derrick assembled on a job site. The project shuts down for 35 days. Under OSHA 1926.1436, what must be done with the derrick boom during this period?',
              options: [
                'No special action is required for shutdowns under 60 days',
                'The boom must be lowered or secured to a stationary member',
                'The boom must be removed from the derrick entirely',
                'A watchman must monitor the derrick daily during the shutdown',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.1436 requires that for service interruptions of 30 days or more, the boom must be laid down or secured to a stationary member. A derrick boom left at working angle without a load is vulnerable to wind and stability failure over an extended idle period.',
            },
            {
              question: 'You are preparing for the 3A exam and reviewing the regulatory framework. Which of the following is the correct hierarchy?',
              options: [
                'OSHA regulations are above MGL Chapter 146, which is above 230 CMR 6.00',
                'MGL Chapter 146 is the state statute; 230 CMR 6.00 implements it; OSHA Subpart CC and 1926.603 are federal standards — the most protective requirement applies',
                '230 CMR 6.00 supersedes all OSHA standards for Massachusetts operations',
                'Only 230 CMR 6.00 applies in Massachusetts; federal OSHA does not have jurisdiction',
              ],
              correctIndex: 1,
              explanation: 'MGL Chapter 146 is the enabling statute; 230 CMR 6.00 is the MA implementing regulation; OSHA provides federal minimums. Massachusetts operators must comply with both state and federal requirements — wherever the standards overlap, the more protective one applies. This layered framework is a core exam concept.',
            },
          ],
        },
      ],
    },
  ],
};
