import { LicenseRestriction } from '../types';

export const restriction_4g: LicenseRestriction = {
  code: '4G',
  name: 'Compact hoisting — specialty',
  description: 'Mini-excavators, compact loaders per 520 CMR 6.00.',
  equipmentCovered: ['Mini-excavators', 'Compact loaders', 'Compact equipment'],
  totalHours: 16,
  modules: [
    {
      id: '4g-m1',
      title: 'Foundation',
      orderInCourse: 1,
      estimatedHours: 4,
      sessions: [
        {
          id: '4g-m1-s1',
          title: '520 CMR 6.00 Scope',
          durationHours: 2,
          learningObjectives: [
            'Explain the purpose and scope of 520 CMR 6.00 and how it governs compact hoisting machinery in Massachusetts',
            'State the gross vehicle weight threshold that defines compact hoisting machinery and distinguishes it from heavier equipment classes',
            'Identify the types of construction activities that trigger 520 CMR 6.00 licensing requirements for compact equipment',
            'Describe the temporary permit system for short-term rental of compact hoisting machinery and its key limitations',
          ],
          topics: [
            '520 CMR 6.00 administered by the MA Office of Public Safety and Inspections (OPSI)',
            'Scope: applies to hoisting machinery used on construction, demolition, alteration, maintenance, and material-handling operations on public or private property',
            'Agricultural exemption: equipment used exclusively for agricultural purposes is excluded',
            'Compact hoisting machinery defined: gross vehicle weight (GVW) not exceeding 10,000 lbs, excluding Class 1, Class 3, and Class 4 machinery',
            'Equipment thresholds: must be capable of lifting ≥ 500 lbs OR ≥ 10 ft, or have bucket capacity > ¼ cubic yard to require licensing',
            'Temporary (short-term rental) permit: GVW limit reduced to 8,000 lbs; non-renewable; issued by a Department-approved rental entity for no more than 14 consecutive days',
            'Temporary permit holders must be ≥ 18 years old with a valid driver\'s license and complete training from the rental entity facilitator',
            'Relationship between 520 CMR 6.00 and MGL Chapter 146: the statute (Chapter 146) authorizes licensing; 520 CMR 6.00 implements the technical requirements',
            'Operator compliance with all applicable ANSI/ASME standards and OSHA 29 CFR 1926 required',
          ],
          resources: [
            {
              label: '520 CMR 6.00 — Hoisting Machinery (law.cornell.edu)',
              url: 'https://www.law.cornell.edu/regulations/massachusetts/department-520-CMR/title-520-CMR-6.00',
              type: 'regulation',
              required: true,
            },
            {
              label: '520 CMR § 6.01 — General Provisions, Scope, Definitions',
              url: 'https://www.law.cornell.edu/regulations/massachusetts/520-CMR-6-01',
              type: 'regulation',
              required: true,
            },
            {
              label: 'MGL Chapter 146 — Hoisting Machinery Licensing Statute',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146',
              type: 'regulation',
              required: true,
            },
            {
              label: 'MA Hoisting Licensing and Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'Under 520 CMR 6.00, what is the maximum gross vehicle weight for equipment to qualify as "compact hoisting machinery" requiring a compact hoisting license?',
              options: ['5,000 lbs', '8,000 lbs', '10,000 lbs', '15,000 lbs'],
              correctIndex: 2,
              explanation: 'Compact hoisting machinery is defined in 520 CMR 6.00 as equipment with a GVW not exceeding 10,000 lbs (excluding Class 1, 3, and 4 machinery). The 8,000 lb figure applies only to the more restricted short-term rental temporary permit.',
            },
            {
              question: 'A homeowner rents a mini-excavator for a weekend landscaping project. Under 520 CMR 6.00, which permit allows them to legally operate it without a full hoisting license?',
              options: [
                'No permit is needed on private residential property',
                'A temporary (short-term rental) permit, if the machine GVW does not exceed 8,000 lbs',
                'A temporary permit is available for any GVW up to 10,000 lbs',
                'Any person 21 or older may operate compact equipment without a permit',
              ],
              correctIndex: 1,
              explanation: '520 CMR 6.00 provides a non-renewable temporary permit for compact hoisting machinery rented from a Department-approved entity, capped at 8,000 lbs GVW, for up to 14 consecutive days. The applicant must be 18+ with a valid driver\'s license and complete the rental entity\'s training.',
            },
            {
              question: 'Which of the following activities would bring a mini-excavator operator under the scope of 520 CMR 6.00?',
              options: [
                'Digging irrigation ditches on a family farm',
                'Excavating a utility trench on a public street',
                'Moving hay bales in a barn using a compact loader',
                'Operating a walk-behind tiller on agricultural land',
              ],
              correctIndex: 1,
              explanation: 'Construction and utility work on public property is squarely within 520 CMR 6.00\'s scope. Agricultural operations on farm property are explicitly exempt. Walk-behind tillers typically do not meet the lifting/bucket capacity thresholds.',
            },
            {
              question: 'What is the maximum duration for a temporary permit to operate rented compact hoisting machinery under 520 CMR 6.00?',
              options: ['7 consecutive days', '14 consecutive days', '30 days per calendar year', '60 days with an extension'],
              correctIndex: 1,
              explanation: 'The temporary permit is non-renewable and valid for no more than 14 consecutive days. It is issued by the Department-approved short-term rental entity, not by the operator\'s own application to OPSI.',
            },
            {
              question: 'Under 520 CMR 6.00, which statute authorizes the state to require hoisting machinery operators to obtain a license?',
              options: ['OSHA 29 CFR 1926', 'MGL Chapter 146', 'ANSI B30.5', '520 CMR 14.00'],
              correctIndex: 1,
              explanation: 'MGL Chapter 146 is the Massachusetts General Law statute that establishes the licensing requirement. 520 CMR 6.00 is the implementing regulation that adds technical standards and operational rules under the authority granted by Chapter 146.',
            },
            {
              question: 'A compact track loader has a GVW of 9,500 lbs, a rated bucket capacity of ½ cubic yard, and can lift loads of up to 2,800 lbs to a height of 11 feet. Does this machine require a license to operate under 520 CMR 6.00?',
              options: [
                'No — it is under the 10,000 lb GVW threshold',
                'Yes — it exceeds the bucket capacity threshold and the lift height threshold',
                'Only if operated on public property',
                'No — compact loaders are exempt if the operator holds a driver\'s license',
              ],
              correctIndex: 1,
              explanation: 'The machine exceeds multiple thresholds that trigger licensing: bucket capacity > ¼ cubic yard, lift height > 10 ft, and load capacity > 500 lbs. Meeting ANY one of these thresholds requires a license regardless of whether the equipment is labeled "compact."',
            },
          ],
        },
        {
          id: '4g-m1-s2',
          title: 'Licensing Requirements',
          durationHours: 2,
          learningObjectives: [
            'State the minimum age, passing score, application fee, and renewal cycle for a compact hoisting license',
            'Describe the application process through the MA Division of Occupational Licensure',
            'Explain the consequences of operating compact hoisting machinery without a valid license',
            'Identify the exemptions under MGL Chapter 146 § 53 that apply to compact equipment operators',
          ],
          topics: [
            'Minimum age requirement: 18 years old (MGL Chapter 146)',
            'Exam passing score: 70% minimum',
            '60-day waiting period after a failed exam attempt',
            '$75 non-refundable application fee per restriction class',
            'License validity: 2 years; renewal required before expiration',
            'Application submitted through the MA Division of Occupational Licensure (DOL)',
            'Exam covers: equipment knowledge, safety procedures, hand signals, inspection requirements',
            'MGL §53 exemptions: agricultural operators, supervised vocational/apprenticeship programs, industrial lift trucks on company property',
            'Civil penalty up to $500 per day for each day of unlicensed operation',
            'Employer liability for knowingly using an unlicensed operator',
            'License must be in the operator\'s possession during operation — available for inspection on demand',
            'Difference between a full hoisting license and the temporary (short-term rental) permit',
          ],
          resources: [
            {
              label: 'MGL Chapter 146 § 53 — Licensing Requirement',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146/Section53',
              type: 'regulation',
              required: true,
            },
            {
              label: 'Apply for a Hoisting Engineer License (mass.gov)',
              url: 'https://www.mass.gov/how-to/apply-for-a-hoisting-engineer-license',
              type: 'reference',
              required: true,
            },
            {
              label: 'MA Hoisting Licensing and Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'What is the minimum passing score on the Massachusetts compact hoisting engineer exam?',
              options: ['60%', '65%', '70%', '75%'],
              correctIndex: 2,
              explanation: 'The required passing score is 70%. A score below 70% triggers a mandatory 60-day wait before a retest — use that time to review weak areas rather than retesting unprepared.',
            },
            {
              question: 'How long must an operator wait after failing the Massachusetts hoisting exam before taking it again?',
              options: ['7 days', '30 days', '60 days', '90 days'],
              correctIndex: 2,
              explanation: 'The 60-day waiting period is fixed by regulation. It cannot be waived or shortened regardless of the margin of failure or the reason for the delay.',
            },
            {
              question: 'Which of the following operators is EXEMPT from holding a Massachusetts hoisting license under MGL Chapter 146 § 53?',
              options: [
                'A landscaper operating a compact track loader on a residential job site',
                'A construction worker running a skid steer on a highway project',
                'A farmhand operating a compact loader exclusively on agricultural land owned by their employer',
                'A demolition crew member running a mini-excavator on a private lot',
              ],
              correctIndex: 2,
              explanation: 'MGL §53 explicitly exempts agricultural operators using equipment exclusively for agricultural purposes. All three of the other scenarios involve construction or maintenance activities that trigger the licensing requirement.',
            },
            {
              question: 'What is the non-refundable application fee per restriction class for a Massachusetts hoisting engineer license?',
              options: ['$25', '$50', '$75', '$100'],
              correctIndex: 2,
              explanation: 'The fee is $75 per restriction class and is non-refundable even if you fail the exam or withdraw your application. If you are applying for multiple restriction classes simultaneously, each class carries its own separate fee.',
            },
            {
              question: 'How long is a Massachusetts hoisting engineer license valid before renewal is required?',
              options: ['1 year', '2 years', '3 years', '5 years'],
              correctIndex: 1,
              explanation: 'Hoisting engineer licenses are valid for 2 years. Renewal must occur before expiration — there is no official grace period, and operating on an expired license is treated as unlicensed operation.',
            },
            {
              question: 'What is the maximum civil penalty per day for operating compact hoisting machinery without a valid Massachusetts license?',
              options: ['$100/day', '$250/day', '$500/day', '$1,000/day'],
              correctIndex: 2,
              explanation: 'MGL Chapter 146 allows civil penalties of up to $500 per day for each day of unlicensed operation. Employers who knowingly deploy unlicensed operators also face liability — the obligation is shared.',
            },
            {
              question: 'When must a compact hoisting operator have their license available on a job site?',
              options: [
                'Only during formal OSHA inspections',
                'At all times during operation — the license must be on their person and available for inspection on demand',
                'Only when operating on public property or public roads',
                'Within 24 hours of a request by an inspector',
              ],
              correctIndex: 1,
              explanation: 'The license must be in the operator\'s possession and available for immediate inspection during any operation. Leaving it in your vehicle or at home does not satisfy this requirement.',
            },
          ],
        },
      ],
    },
    {
      id: '4g-m2',
      title: 'Equipment',
      orderInCourse: 2,
      estimatedHours: 4,
      sessions: [
        {
          id: '4g-m2-s1',
          title: 'Mini-Excavators',
          durationHours: 2,
          learningObjectives: [
            'Identify the major structural components and systems of a mini-excavator and describe the function of each',
            'Explain the difference between zero-tail-swing and conventional-tail-swing machines and when each is preferred',
            'Describe rubber versus steel track configurations and the trade-offs for different job conditions',
            'Name common mini-excavator attachments and state safe procedures for changing them',
          ],
          topics: [
            'Mini-excavator defined: compact crawler excavator typically under 6 metric tons operating weight; falls within compact hoisting machinery GVW ≤ 10,000 lbs',
            'Key structural components: undercarriage (tracks, rollers, idlers, sprocket), carbody (swing bearing, swing motor), upperstructure (cab/canopy, engine, counterweight), boom, arm (dipper stick), bucket, quick coupler',
            'Cab vs. canopy configurations: enclosed cab offers climate control and FOPS/ROPS protection; open canopy reduces machine height for indoor/low-clearance work',
            'ROPS (Roll-Over Protective Structure) and FOPS (Falling Object Protective Structure): required by 29 CFR 1926.602; purpose and operator seat-belt enforcement',
            'Tail-swing types: conventional tail-swing (counterweight extends beyond track width during swing) vs. zero-tail-swing / minimal-swing (counterweight stays within track width); zero-tail preferred in confined spaces',
            'Track types: rubber tracks (protect paved surfaces, quieter, better for soft ground) vs. steel tracks (greater durability on rock/debris, better traction in steep terrain)',
            'Dozer blade: front-mounted grading/backfill blade; lowers machine center of gravity when traveling on slopes',
            'Thumb attachments: fixed or hydraulic; allows grasping irregular objects, handling pipe, placing stone',
            'Hydraulic quick coupler: enables rapid attachment changes; lock verification procedure before operation',
            'Controls: standard ISO/SAE pattern joystick controls — left joystick controls boom, swing; right joystick controls arm and bucket; pattern may differ by manufacturer; confirm before operation',
            'Operating radius and reach: boom/arm geometry determines maximum dig depth, dump height, and reach; never exceed rated digging force',
            'Slew (swing) operation: 360-degree continuous rotation; swing speed control; swing lock for transport',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1926.602 — Material Handling Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926 Subpart P — Excavations',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926_subpart_P',
              type: 'osha',
              required: true,
            },
            {
              label: '520 CMR § 6.01 — Definitions (compact hoisting machinery)',
              url: 'https://www.law.cornell.edu/regulations/massachusetts/520-CMR-6-01',
              type: 'regulation',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'What is the primary advantage of a zero-tail-swing mini-excavator compared to a conventional-tail-swing machine?',
              options: [
                'Greater lifting capacity at extended reach',
                'The counterweight stays within the track width during swing, allowing safe operation in confined spaces',
                'Zero-tail machines can travel on roads without a permit',
                'They have a higher bucket capacity for the same machine weight',
              ],
              correctIndex: 1,
              explanation: 'On a conventional machine, the counterweight swings outside the track footprint and can strike nearby walls, fences, or workers. Zero-tail-swing machines keep the counterweight within the track width, making them the preferred choice for urban trenching, indoor work, and tight job sites.',
            },
            {
              question: 'Under OSHA 29 CFR 1926.602, which protective structure is REQUIRED on compact excavators to protect the operator from rollover?',
              options: [
                'FOPS only',
                'ROPS only',
                'Both ROPS and FOPS',
                'Neither — only large cranes require protective structures',
              ],
              correctIndex: 2,
              explanation: 'OSHA 29 CFR 1926.602 requires ROPS (Roll-Over Protective Structure) on crawler-type equipment and FOPS (Falling Object Protective Structure) in areas with overhead hazards. Most modern mini-excavator cabs incorporate both. The seat belt must be worn whenever ROPS is present.',
            },
            {
              question: 'You are operating a mini-excavator on a job site with freshly poured concrete aprons and asphalt driveways. Which track type causes the least surface damage?',
              options: [
                'Steel tracks, because they grip better',
                'Rubber tracks, because they distribute weight more evenly and do not cut hard surfaces',
                'Both types cause identical damage',
                'Track type does not affect surface damage — only machine weight matters',
              ],
              correctIndex: 1,
              explanation: 'Rubber tracks are specifically designed to protect paved and hard surfaces. Steel tracks can gouge asphalt and chip concrete. Many job sites require rubber-tracked machines or rubber track pads when working on finished surfaces.',
            },
            {
              question: 'After installing a new bucket using the hydraulic quick coupler, what is the FIRST thing the operator must verify before resuming excavation?',
              options: [
                'That the boom is fully extended',
                'That the coupler locking pin or safety lock is fully engaged and the attachment is secure',
                'That the hydraulic fluid level has not dropped',
                'That the swing lock is disengaged',
              ],
              correctIndex: 1,
              explanation: 'Quick coupler accidents most commonly result from an incomplete lock — the attachment appears to be on but releases during operation. Always confirm the safety lock is engaged and perform a short test lift (a few inches off the ground) before applying full digging force.',
            },
            {
              question: 'What does the dozer blade on a mini-excavator primarily help with when the machine must travel on a slope?',
              options: [
                'It acts as a counterweight to the boom when extended',
                'It provides additional traction by digging into the ground surface',
                'When lowered to the ground, it lowers the machine\'s center of gravity and stabilizes the machine on slopes',
                'It is used only for backfilling and has no effect on stability',
              ],
              correctIndex: 2,
              explanation: 'The dozer blade, when lowered so it lightly contacts the ground on the downhill side, acts as a brake and lowers the center of gravity. This is especially important when traveling across or up/down slopes — always orient the machine with the dozer blade on the downhill side when traveling on grades.',
            },
            {
              question: 'A mini-excavator\'s ISO joystick pattern is in use. Which joystick controls boom up/down and arm in/out?',
              options: [
                'Left joystick: boom up/down; Right joystick: arm in/out',
                'Right joystick: boom up/down; Left joystick: arm in/out',
                'Left joystick: arm in/out and swing; Right joystick: boom up/down and bucket curl',
                'Both joysticks share boom and arm functions depending on machine model',
              ],
              correctIndex: 2,
              explanation: 'In ISO (also called SAE) pattern: the left joystick controls arm in/out and upperstructure swing; the right joystick controls boom up/down and bucket curl/dump. Always verify the control pattern for the specific machine before operating — some machines allow pattern switching.',
            },
          ],
        },
        {
          id: '4g-m2-s2',
          title: 'Compact Loaders',
          durationHours: 2,
          learningObjectives: [
            'Identify the major types of compact loaders (skid steer, compact track loader, compact wheel loader) and the key differences between them',
            'Explain rated operating capacity (ROC) and its relationship to tipping load, and describe how load placement affects stability',
            'Compare H-pattern and ISO control patterns for compact loaders and describe safe procedures for operating in each',
            'Describe vertical-lift versus radial-lift arm geometry and the applications each is best suited for',
          ],
          topics: [
            'Compact loader types: skid steer loader (SSL — rubber-tired, all-wheel drive, turns by differential wheel speed), compact track loader (CTL — rubber tracks, better flotation on soft/muddy ground), compact wheel loader (CWL — articulated steering, gentler on turf)',
            'Key components: lift arms, coupler/bucket, operator cab, ROPS/FOPS structure, hydraulic system, engine compartment, hand/foot controls',
            'Rated Operating Capacity (ROC): 50% of the machine\'s full static tipping load; the maximum load that may be carried in normal operation; always on the machine\'s load plate',
            'Tipping load: the weight at which the machine tips forward over the front axle (tires) or front idler (tracks); ROC = 50% of tipping load',
            'Stability factors: load height (higher = less stable), load position (forward of bucket curl = more tipping risk), ground slope, attachment type, tire pressure / track tension',
            'Lift arm geometry: radial-lift arm (arc path, great for ground-level digging and truck loading at mid-height), vertical-lift arm (near-vertical path at full height, better for loading trucks and hoppers at maximum height)',
            'H-pattern controls: left hand lever — forward/reverse travel and left turn; right hand lever — forward/reverse travel and right turn; foot pedals — auxiliary hydraulics or drive speed; intuitive for new operators',
            'ISO (Hand-Foot) controls: hand joysticks control lift/tilt functions; foot pedals control drive; more common on newer machines and familiar to excavator operators',
            'Attachment interface: universal skid steer quick attach plate (flat face coupler) — allows rapid change between bucket, forks, auger, grapple, trencher, sweeper, and many others',
            'Before changing attachments: relieve hydraulic pressure, verify ground is level, set parking brake, exit and re-enter with machine off',
            'Traveling with a load: keep load low (6–12 inches off ground), travel slowly on grades, never carry loads above operators\' eye level on steep terrain',
            'Visibility limitations: rear visibility is restricted on most compact loaders — use mirrors, cameras, and a spotter when backing',
            'OSHA 29 CFR 1926.602: seatbelt required, ROPS required, never carry riders unless a second seat with belt is provided by the manufacturer',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1926.602 — Material Handling Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: true,
            },
            {
              label: '520 CMR § 6.01 — Definitions (compact hoisting machinery)',
              url: 'https://www.law.cornell.edu/regulations/massachusetts/520-CMR-6-01',
              type: 'regulation',
              required: true,
            },
            {
              label: 'MA Hoisting Licensing and Exams (mass.gov)',
              url: 'https://www.mass.gov/hoisting-licensing-and-exams',
              type: 'reference',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'A compact track loader has a rated operating capacity (ROC) of 1,750 lbs. What is the machine\'s approximate full static tipping load?',
              options: ['875 lbs', '1,750 lbs', '3,500 lbs', '5,250 lbs'],
              correctIndex: 2,
              explanation: 'ROC = 50% of full static tipping load. So tipping load = ROC ÷ 0.50 = 1,750 ÷ 0.50 = 3,500 lbs. Never load the machine to or beyond the tipping load — working at ROC already represents the maximum safe operating load.',
            },
            {
              question: 'You are using a skid steer to carry a loaded pallet of masonry blocks. As you raise the load to full height to tip it into a dumpster, what happens to the machine\'s stability?',
              options: [
                'Stability improves because the load is farther from the ground',
                'Stability is unaffected — ROC is constant regardless of lift height',
                'Stability decreases because raising the load shifts the center of gravity forward and upward',
                'Stability only changes if the machine is on a slope',
              ],
              correctIndex: 2,
              explanation: 'Raising a load increases the height of the combined center of gravity of the machine-plus-load system, making the machine more prone to tipping forward. For this reason, manufacturer load charts often specify a reduced ROC at full height. Always travel with the load low.',
            },
            {
              question: 'Which compact loader lift arm geometry is BEST suited for loading a tall dump truck at maximum height with maximum reach?',
              options: [
                'Radial-lift arm, because it provides a longer forward reach at low heights',
                'Vertical-lift arm, because it travels in a near-vertical path and maintains reach and dump height at the top of the stroke',
                'Both geometries perform identically at maximum height',
                'Horizontal-lift arm, which is the standard configuration for dump truck loading',
              ],
              correctIndex: 1,
              explanation: 'Vertical-lift arm geometry maintains consistent reach and dump height across the top of the lift path, making it ideal for loading high-sided trucks and hoppers. Radial-lift arms excel at ground-level digging and mid-height loading but lose reach as the arms approach full height.',
            },
            {
              question: 'Under OSHA 29 CFR 1926.602, a co-worker asks to ride in the bucket of a skid steer to reach a ledge on a wall. What is the correct response?',
              options: [
                'Allow it if the lift is under 6 feet and someone spots from the ground',
                'Allow it if the co-worker signs a waiver and wears a hard hat',
                'Refuse — only the manufacturer-provided passenger seat (if equipped) with a seatbelt may carry a rider',
                'Allow it only if the machine has a ROPS cab rather than a canopy',
              ],
              correctIndex: 2,
              explanation: 'OSHA 29 CFR 1926.602 prohibits carrying riders on equipment not designed for it. The bucket is never an approved personnel platform. The only exception is a manufacturer-designed, ROPS-protected second seat with a seatbelt — not present on most compact loaders.',
            },
            {
              question: 'A compact track loader uses H-pattern controls. What does the operator do with the LEFT hand lever to turn the machine left in place?',
              options: [
                'Push the lever forward',
                'Push the lever forward while pulling the right lever backward simultaneously',
                'Pull the lever backward while pushing the right lever forward simultaneously',
                'Move both levers in the same direction at different speeds',
              ],
              correctIndex: 2,
              explanation: 'Skid steer turning works by differential speed/direction: to spin left in place, pull the left lever back (left wheels reverse) and push the right lever forward (right wheels drive). This counter-rotation spins the machine within its own footprint — the key characteristic of skid steer locomotion.',
            },
            {
              question: 'When traveling down a slope with a loaded bucket on a compact loader, what is the safest position for the load?',
              options: [
                'At full height so the operator can see the ground ahead',
                'Low (6–12 inches off the ground) and tilted back toward the machine',
                'At mid-height (approximately 3 feet) for balance',
                'Load position does not matter on grades — only speed matters',
              ],
              correctIndex: 1,
              explanation: 'Keeping the load low (6–12 inches) and bucket tilted back lowers the center of gravity and places more weight over the rear axle/tracks, reducing forward tip risk on downhill grades. A high load on a slope dramatically increases the risk of the machine tipping forward.',
            },
          ],
        },
      ],
    },
    {
      id: '4g-m3',
      title: 'Operation',
      orderInCourse: 3,
      estimatedHours: 4,
      sessions: [
        {
          id: '4g-m3-s1',
          title: 'Safety & Inspection',
          durationHours: 2,
          learningObjectives: [
            'Conduct a pre-operation inspection of a compact excavator or compact loader using a systematic walkaround procedure',
            'Identify the fluid checks, structural checks, and functional checks required before placing a machine in service',
            'Describe the role of ROPS/FOPS and seat-belt requirements under OSHA 29 CFR 1926.602',
            'Explain the hand-signal requirements under 520 CMR 6.00 and identify the approved signaler\'s role',
          ],
          topics: [
            'Pre-operation inspection purpose: identify defects before they cause failures, injuries, or regulatory violations',
            'Walkaround inspection sequence: start at a fixed point and move methodically around the machine to ensure nothing is missed',
            'Fluid checks: engine oil level and condition, hydraulic fluid level and condition, coolant level, fuel level, DEF (diesel exhaust fluid) level if applicable; look for leaks under the machine',
            'Track/tire inspection: rubber track condition (cuts, tears, delamination, tension), steel track link wear and pin condition, rubber tire inflation and condition on wheel loaders/skid steers',
            'Structural inspection: cracks in boom, arm, or bucket; cracked or bent lift arms; loose or missing fasteners on quick coupler and attachments',
            'Hydraulic hose and fitting inspection: chafing, kinking, abrasion, fittings loose or weeping; never check for hydraulic leaks with bare hands (injection injury risk)',
            'ROPS/FOPS integrity: no cracks, cuts, or missing mounting hardware; must not be modified by welding without manufacturer approval',
            'Seatbelt condition and function: fraying, buckle engagement, retractor function; OSHA 29 CFR 1926.602 requires seat belt use when ROPS is present',
            'Cab/controls check: all gauges and warning lights operational, horn functional, all joystick/lever controls move freely and return to neutral, travel alarm functional',
            'Attachment condition: bucket teeth/cutting edge wear, cracking at welds, pin and bushing play',
            'Removing a machine from service: a defective machine must be tagged out-of-service and not returned to operation until repairs are completed and documented',
            'SAE J1307 hand signals: required by 520 CMR 6.00 for excavating machinery; only an approved signaler may direct operator movement; operator must stop immediately if signaler is not visible',
            'Exclusion zones: no person permitted within the working radius of the machine during operation; compact machines can still seriously injure workers in close proximity',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1926.602 — Material Handling Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: true,
            },
            {
              label: '520 CMR 6.00 — Hoisting Machinery (law.cornell.edu)',
              url: 'https://www.law.cornell.edu/regulations/massachusetts/department-520-CMR/title-520-CMR-6.00',
              type: 'regulation',
              required: true,
            },
            {
              label: 'SAE J1307 Hand Signals — Quick Reference',
              url: '/hand-signals',
              type: 'reference',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'During a pre-operation inspection, you notice hydraulic fluid seeping from a hose fitting under the boom. What is the correct action?',
              options: [
                'Wipe the fitting clean, operate normally, and monitor during the shift',
                'Tag the machine out of service and report the leak to the supervisor before operating',
                'Press your finger on the fitting to feel for pressure before deciding',
                'Tighten the fitting yourself with a wrench and then operate the machine',
              ],
              correctIndex: 1,
              explanation: 'Any hydraulic leak must result in the machine being taken out of service. Pressing bare skin near a hydraulic leak risks hydraulic injection injury — pressurized hydraulic fluid can penetrate skin painlessly and cause severe tissue damage. Never attempt field repairs without proper training and equipment.',
            },
            {
              question: 'Under OSHA 29 CFR 1926.602, what does the presence of ROPS on a compact loader require the operator to do?',
              options: [
                'Nothing additional — ROPS is a passive system that works automatically',
                'Wear a hard hat at all times inside the cab',
                'Fasten the seatbelt before operating the machine',
                'Reduce travel speed to no more than 5 mph',
              ],
              correctIndex: 2,
              explanation: 'ROPS works only if the operator is restrained. OSHA 29 CFR 1926.602 specifically requires that the seatbelt be fastened whenever operating equipment equipped with ROPS. An unbelted operator can be ejected during a rollover and crushed by the very structure designed to protect them.',
            },
            {
              question: 'Under 520 CMR 6.00, who is the ONLY person authorized to direct a compact excavator operator\'s movements on a job site?',
              options: [
                'The general contractor\'s site superintendent',
                'Any worker with a high-visibility vest on the job site',
                'The approved signaler assigned to the machine',
                'The owner of the property where work is occurring',
              ],
              correctIndex: 2,
              explanation: '520 CMR 6.00 requires that only an approved signaler direct operator movements. The operator must stop all movement immediately if the designated signaler is no longer visible — taking direction from unauthorized personnel violates the regulation and creates unsafe conditions.',
            },
            {
              question: 'Which fluid check during a pre-operation inspection presents a specific injection injury hazard if the operator uses their hand to locate the leak?',
              options: [
                'Engine oil',
                'Coolant',
                'Hydraulic fluid',
                'Diesel fuel',
              ],
              correctIndex: 2,
              explanation: 'Pressurized hydraulic fluid (often at 2,000–5,000 PSI in compact equipment) can penetrate bare skin even when the pinhole leak is invisible. The injury may appear minor but can cause severe internal tissue destruction requiring amputation. Always use cardboard or a mirror to locate hydraulic leaks — never bare hands.',
            },
            {
              question: 'You are conducting a walkaround inspection and notice one rubber track has visible delamination and a 4-inch tear. What should you do?',
              options: [
                'Operate the machine cautiously for the rest of the shift and order a replacement track',
                'Tag the machine out of service until the track is inspected by a mechanic and repaired or replaced',
                'Continue operating — rubber tracks are a wear item and cosmetic damage is acceptable',
                'Spray the tear with rubber sealant and continue to operate',
              ],
              correctIndex: 1,
              explanation: 'Delamination and tears in rubber tracks indicate structural failure in progress. A track that fails during operation can throw debris and disable the machine suddenly. Out-of-service the machine and have a qualified mechanic assess before returning it to duty.',
            },
            {
              question: 'A coworker approaches your mini-excavator while you are digging to point out a grade stake location. They enter the swing radius. What must you do?',
              options: [
                'Slow the swing and wave them toward you',
                'Sound the horn as a warning and continue operating at reduced speed',
                'Stop all machine movement until the person is clear of the working radius',
                'Finish the current swing cycle and then stop to talk',
              ],
              correctIndex: 2,
              explanation: '520 CMR 6.00 prohibits persons within the working radius during operation — no exceptions for "quick" tasks. The only correct action is to stop all movement immediately. The compact size of the machine does not reduce the danger of being struck by the boom, arm, or bucket.',
            },
          ],
        },
        {
          id: '4g-m3-s2',
          title: 'Specialized Practices',
          durationHours: 2,
          learningObjectives: [
            'Apply safe operating techniques for working in confined and restricted spaces with compact equipment',
            'Describe procedures for safe excavation near utilities, structures, and excavation walls using compact equipment',
            'Explain proper loading, unloading, and transport procedures for mini-excavators and compact loaders',
            'Identify stability hazards specific to compact equipment and describe mitigation strategies for each',
          ],
          topics: [
            'Confined-space operation: plan the machine\'s swing arc before beginning; identify overhead clearances (power lines, structure beams); use zero-tail-swing machines where available',
            'OSHA 811 / Dig Safe requirements: call Dig Safe (811) before any excavation; wait the required response period; compact machines do not exempt operators from underground utility locate requirements',
            'Proximity to structures: compact equipment can undermine foundation soils; maintain safe setback from walls, footings, and retaining structures; consult a competent person for trench work near structures',
            'Excavation near underground utilities: hand-dig (pothole) to expose utilities before using mechanical equipment; never use a bucket to excavate within the designated tolerance zone of a marked utility',
            'OSHA 29 CFR 1926 Subpart P (Excavations): slope, bench, or shield requirements apply even when using compact equipment; spoil placement minimum 2 feet from trench edge',
            'Trench safety: do not park or operate compact equipment over an unsupported trench or cut; ground vibration from compact machines increases cave-in risk',
            'Working on slopes: always travel straight up or straight down — never traverse a steep slope laterally; if a tipping sensation is felt, lower the load/attachment immediately and stop',
            'Ground bearing capacity: compact equipment can still exceed allowable ground bearing pressure on soft soils, near utilities, or over filled ground; use ground mats or consult engineer if uncertain',
            'Compact loader attachment changes in the field: always relieve hydraulic pressure, park on level ground, set parking brake, exit machine before unhooking attachment; verify coupler lock before lifting',
            'Trailing attachments and transport: retract boom/arm to minimum transport length; engage swing lock on excavators; raise and lock lift arms on loaders; secure machine on trailer with chains to all tie-down points',
            'Loading/unloading from trailers: use ramps rated for machine weight; approach ramp straight-on; keep attachment low and close; never turn on the ramp',
            'Fueling and battery safety: shut down before fueling; no smoking; check for leaks; battery-electric compact machines — follow manufacturer charging and storage procedures; high-voltage precautions',
          ],
          resources: [
            {
              label: 'OSHA 29 CFR 1926 Subpart P — Excavations',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926_subpart_P',
              type: 'osha',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.602 — Material Handling Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: true,
            },
            {
              label: '520 CMR 6.00 — Hoisting Machinery (law.cornell.edu)',
              url: 'https://www.law.cornell.edu/regulations/massachusetts/department-520-CMR/title-520-CMR-6.00',
              type: 'regulation',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'Before beginning any excavation with a compact excavator in Massachusetts, what must the operator (or their employer) do to comply with utility locate requirements?',
              options: [
                'Nothing special — the compact size of the machine exempts it from utility locate requirements',
                'Call 811 (Dig Safe) and wait the required response period before digging',
                'Only call if the excavation is deeper than 2 feet',
                'Request utility records from the municipality and begin digging once received',
              ],
              correctIndex: 1,
              explanation: 'Massachusetts Dig Safe (811) law requires a call before ANY excavation regardless of machine size or depth. The operator must wait the full required response period. Compact equipment can still strike and rupture underground utilities, creating explosion, electrocution, or flooding hazards.',
            },
            {
              question: 'Under OSHA 29 CFR 1926 Subpart P, where must excavated spoil be placed relative to a trench edge?',
              options: [
                'As close to the edge as needed to minimize material handling',
                'At least 2 feet from the edge of the excavation',
                'At least 5 feet from the edge',
                'Spoil placement rules do not apply to mini-excavators',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.651(j) requires spoil to be placed at least 2 feet back from the trench edge to prevent surcharge loading that can cause cave-ins. The compact machine does not change this requirement — the spoil pile weight acts on the trench wall regardless of how it was placed.',
            },
            {
              question: 'You are loading a mini-excavator onto a trailer using drive-up ramps. Which approach angle is required?',
              options: [
                'At a 45-degree angle to the trailer to allow easier alignment once on the deck',
                'Straight-on, perpendicular to the trailer — never at an angle',
                'From the side of the trailer using the dozer blade to lift the machine up',
                'Any angle is acceptable as long as travel speed is kept low',
              ],
              correctIndex: 1,
              explanation: 'Always approach trailer ramps straight-on. An angled approach places asymmetric load on the ramps and can cause the machine to slide sideways off the ramp, resulting in a tip-over. Once on the deck, the machine must be positioned per the trailer manufacturer\'s instructions and all tie-down chains secured.',
            },
            {
              question: 'A compact track loader is being used to dig a footing trench adjacent to an existing building foundation. What is the primary hazard to assess before beginning?',
              options: [
                'Roof drainage from the building',
                'Undermining the existing foundation soils, potentially destabilizing the structure',
                'Exhaust fumes entering the building through windows',
                'Track noise disturbing occupants of the building',
              ],
              correctIndex: 1,
              explanation: 'Excavating near existing foundations can remove the lateral support and bearing capacity that the foundation relies on, causing settlement or structural failure. Always consult a competent person or structural engineer before digging close to any existing footing or foundation — compact machine size does not reduce this risk.',
            },
            {
              question: 'You are operating a skid steer on a grass slope at approximately 15 degrees when the machine begins to feel unstable laterally. What is the correct immediate action?',
              options: [
                'Accelerate to drive through the unstable area quickly',
                'Turn the machine to face the slope directly and drive straight up or down',
                'Lower the bucket to the ground immediately and stop the machine',
                'Steer toward the high side of the slope to counteract tipping',
              ],
              correctIndex: 2,
              explanation: 'The safest immediate response to lateral instability on a slope is to lower the attachment to the ground — this dramatically lowers the center of gravity and grounds the machine. Then stop and assess the situation before moving. Attempting to turn or accelerate on a slope when already unstable can cause a rapid tip-over.',
            },
            {
              question: 'When a compact excavator is transported by trailer, what must be done with the upperstructure (cab/boom) before transport?',
              options: [
                'The boom should be raised to allow the bucket to clear the trailer',
                'The swing lock must be engaged and the boom/arm folded to minimum transport configuration',
                'The bucket must be removed and transported separately',
                'No special preparation is needed for transport — just drive onto the trailer',
              ],
              correctIndex: 1,
              explanation: 'Before transport, the swing lock must be engaged (to prevent the upperstructure from rotating), the boom and arm folded to the minimum transport height and length, and the machine secured with chains at all manufacturer-designated tie-down points. An unsecured, unlocked excavator on a trailer is a road hazard and a serious safety violation.',
            },
          ],
        },
      ],
    },
    {
      id: '4g-m4',
      title: 'Review',
      orderInCourse: 4,
      estimatedHours: 4,
      sessions: [
        {
          id: '4g-m4-s1',
          title: 'Practice 1',
          durationHours: 2,
          learningObjectives: [
            'Apply regulatory knowledge from Modules 1 and 2 to realistic scenario questions',
            'Distinguish between situations that require a full hoisting license versus a temporary permit',
            'Correctly identify machine components and operator responsibilities across mini-excavator and compact loader types',
            'Demonstrate readiness for exam-style questions on 520 CMR 6.00, MGL Chapter 146, and equipment fundamentals',
          ],
          topics: [
            'Review: 520 CMR 6.00 scope, compact hoisting machinery definition, GVW thresholds (10,000 lbs license; 8,000 lbs temp permit)',
            'Review: MGL Chapter 146 licensing requirements — age, fee, passing score, renewal, wait period',
            'Review: agricultural and other exemptions under MGL §53',
            'Review: mini-excavator components — cab/canopy, ROPS/FOPS, tail-swing types, track types, thumb, dozer blade',
            'Review: compact loader types — SSL, CTL, CWL; ROC and tipping load relationship; lift arm geometry',
            'Review: H-pattern vs. ISO controls for compact loaders',
            'Review: coupler safety — lock verification before operation',
            'Scenario practice: determining whether a license or temporary permit applies to a given operator/machine/activity combination',
            'Scenario practice: identifying the correct equipment for a confined-space or surface-sensitive job',
          ],
          resources: [
            {
              label: '520 CMR § 6.01 — Definitions',
              url: 'https://www.law.cornell.edu/regulations/massachusetts/520-CMR-6-01',
              type: 'regulation',
              required: true,
            },
            {
              label: 'MGL Chapter 146 § 53 — Licensing Requirement',
              url: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXX/Chapter146/Section53',
              type: 'regulation',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926.602 — Material Handling Equipment',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.602',
              type: 'osha',
              required: false,
            },
          ],
          selfCheck: [
            {
              question: 'A general contractor\'s employee needs to operate a 7,800 lb GVW compact track loader on a residential construction project for 3 weeks. Which authorization is appropriate?',
              options: [
                'A temporary permit from a rental company — 7,800 lbs is under the 8,000 lb temp permit limit',
                'A full compact hoisting license — the work is professional construction and the duration exceeds the 14-day temp permit limit',
                'No license required — residential construction is exempt',
                'A temporary permit renewed weekly for each 7-day period',
              ],
              correctIndex: 1,
              explanation: 'The temporary permit is non-renewable and valid for a maximum of 14 consecutive days. A 3-week professional construction assignment requires a full hoisting license regardless of machine weight. Temporary permits are intended for homeowners and casual users renting equipment short-term.',
            },
            {
              question: 'Which of the following BEST describes the purpose of the bucket thumb attachment on a mini-excavator?',
              options: [
                'It increases bucket capacity for moving bulk material',
                'It reduces hydraulic pressure needed for digging in hard soil',
                'It allows the operator to grasp irregular objects such as rocks, stumps, and pipe',
                'It converts the bucket into a compaction plate for trench backfill',
              ],
              correctIndex: 2,
              explanation: 'The thumb — fixed or hydraulic — creates a grasping action with the bucket to handle objects that would otherwise fall out during lifting. It is especially useful for material sorting, rock removal, pipe placement, and concrete demolition debris.',
            },
            {
              question: 'A compact loader\'s load plate shows a ROC of 2,000 lbs. The operator needs to move a pallet of concrete blocks weighing 2,400 lbs. What should the operator do?',
              options: [
                'Proceed — the 20% overload is within typical safety margins',
                'Split the pallet into two loads — do not exceed the ROC',
                'Extend the lift arms to their lowest position to lower the center of gravity and then carry the full 2,400 lbs',
                'Only the tipping load (4,000 lbs) matters — ROC is advisory only',
              ],
              correctIndex: 1,
              explanation: 'ROC is the maximum authorized operating load — it is not advisory and may not be exceeded. Exceeding ROC increases the risk of tipping the machine, damaging the hydraulic system, and voiding manufacturer warranties. Split the load or use a larger machine.',
            },
            {
              question: 'An operator holds a valid compact hoisting license but it expired 3 weeks ago. They are observed operating a mini-excavator on a utility project. Which statement is correct?',
              options: [
                'The operator is compliant — there is an automatic 30-day grace period after expiration',
                'The operator is in violation — operating on an expired license is treated as unlicensed operation',
                'The operator is compliant as long as they have applied for renewal',
                'The employer is liable but the operator is not',
              ],
              correctIndex: 1,
              explanation: 'There is no grace period under Massachusetts law. An expired license is not a valid license, and operating on an expired license exposes both the operator and the employer to civil penalties. Renewal must be completed before the expiration date.',
            },
            {
              question: 'On which surface condition is a compact track loader (CTL) most advantageous compared to a rubber-tired skid steer loader (SSL)?',
              options: [
                'Finished concrete inside a warehouse',
                'Soft, muddy, or wet ground with low bearing capacity',
                'Dry paved asphalt in a parking lot',
                'Hard rocky terrain where surface protection is not required',
              ],
              correctIndex: 1,
              explanation: 'Rubber tracks distribute machine weight over a longer, wider footprint (lower ground pressure) than wheels, providing superior flotation on soft and wet ground. Skid steers on soft ground can sink or lose traction. On hard paved surfaces, the advantage reverses — wheel machines are faster and cause less surface damage.',
            },
            {
              question: 'A mini-excavator operator is digging a utility trench. The designated signaler has stepped behind a fence and is no longer visible. What must the operator do immediately?',
              options: [
                'Continue digging carefully while frequently checking for the signaler\'s return',
                'Switch to radio communication with the signaler',
                'Stop all machine movement until the signaler returns to a visible position',
                'Ask the nearest worker to relay signals until the signaler returns',
              ],
              correctIndex: 2,
              explanation: '520 CMR 6.00 requires the operator to stop immediately if the designated signaler is not visible. No relay system and no substitute signaler is authorized — only the approved signaler may direct the machine. Resume only when the designated signaler is visible again.',
            },
            {
              question: 'What is the primary purpose of the rated operating capacity (ROC) marking on a compact loader?',
              options: [
                'To show the maximum weight the machine can lift at any height in any condition',
                'To provide operators with the maximum safe working load under typical operating conditions, set at 50% of tipping load',
                'To indicate the weight of the machine itself for trailer loading calculations',
                'To show how much fuel the machine can carry before the tank overflows',
              ],
              correctIndex: 1,
              explanation: 'ROC = 50% of the full static tipping load, providing a safety margin for dynamic conditions (travel, turning, uneven ground) that reduce stability below the static tipping test value. Always check the machine\'s specific load chart — ROC may be reduced at height or for specific attachments.',
            },
          ],
        },
        {
          id: '4g-m4-s2',
          title: 'Practice 2',
          durationHours: 2,
          learningObjectives: [
            'Apply safety, inspection, and specialized-operations knowledge from Modules 3 and 4 to exam-style questions',
            'Integrate regulatory requirements with practical operational decisions across the full course scope',
            'Identify common violations and unsafe conditions for both mini-excavators and compact loaders',
            'Demonstrate exam readiness across all 4G curriculum topics',
          ],
          topics: [
            'Review: pre-operation inspection sequence — fluids, tracks/tires, structure, hydraulics, ROPS/FOPS, seatbelt, controls',
            'Review: hydraulic injection injury hazard during inspection',
            'Review: OSHA 29 CFR 1926.602 — ROPS, seatbelt, no riders without manufacturer-provided seat',
            'Review: 520 CMR 6.00 signaler and exclusion zone requirements',
            'Review: confined-space and restricted-area techniques; zero-tail-swing selection',
            'Review: Dig Safe (811) call before excavation',
            'Review: OSHA Subpart P — spoil placement at least 2 feet from trench edge; no equipment over unsupported trench',
            'Review: slope operation — travel straight up/down; lower attachment on unstable ground',
            'Review: transport — swing lock, fold boom/arm, chain tie-downs; straight-on ramp approach',
            'Review: attachment change procedures — relieve hydraulic pressure, level ground, park brake, verify lock',
            'Full-exam simulation: mixed questions covering all modules',
          ],
          resources: [
            {
              label: '520 CMR 6.00 — Hoisting Machinery (law.cornell.edu)',
              url: 'https://www.law.cornell.edu/regulations/massachusetts/department-520-CMR/title-520-CMR-6.00',
              type: 'regulation',
              required: true,
            },
            {
              label: 'OSHA 29 CFR 1926 Subpart P — Excavations',
              url: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926_subpart_P',
              type: 'osha',
              required: true,
            },
            {
              label: 'SAE J1307 Hand Signals — Quick Reference',
              url: '/hand-signals',
              type: 'reference',
              required: true,
            },
          ],
          selfCheck: [
            {
              question: 'During a pre-operation inspection, an operator finds a crack at the boom-to-arm pin boss on a mini-excavator. What is the correct response?',
              options: [
                'Continue operating at reduced capacity for the shift and report the crack at end of day',
                'Weld the crack in the field before starting the machine',
                'Tag the machine out of service — structural cracks in boom/arm require professional repair before returning to service',
                'Only remove the machine from service if the crack is more than 2 inches long',
              ],
              correctIndex: 2,
              explanation: 'Structural cracks in the boom or arm are a safety-critical defect. A crack at a pin boss is under severe cyclic loading during normal operation and can propagate rapidly to complete fracture, causing sudden collapse. The machine must be out-of-service until a qualified mechanic performs the repair — no field welding by the operator.',
            },
            {
              question: 'An operator uses their bare fingers to search for a hydraulic leak on a compact loader\'s boom cylinder. What injury risk does this create?',
              options: [
                'Skin irritation from hydraulic fluid contact',
                'Hydraulic injection injury — high-pressure fluid can penetrate skin and cause severe internal tissue damage',
                'Burn injury from hot hydraulic fluid',
                'No significant risk — hydraulic fluid pressure drops when the leak is found',
              ],
              correctIndex: 1,
              explanation: 'Hydraulic injection injury is a medical emergency. Fluid at operating pressure (often 2,000–5,000 PSI) penetrates bare skin painlessly; the entry point may be barely visible. The fluid then spreads through tissue causing severe destruction. Always use cardboard, paper, or a purpose-built leak detector to find hydraulic leaks — never bare hands.',
            },
            {
              question: 'Under 520 CMR 6.00, if conflicting directions are given by the approved signaler and the general contractor\'s foreman simultaneously, what must the operator do?',
              options: [
                'Follow the foreman\'s instruction — the foreman has site authority',
                'Follow the signaler\'s instruction — only the signaler may direct the machine',
                'Stop all movement until the conflict is resolved; if an Emergency Stop is given by either person, stop immediately',
                'Use the operator\'s own judgment about which instruction is safer',
              ],
              correctIndex: 2,
              explanation: 'The approved signaler is the only person authorized to direct the machine under 520 CMR 6.00. If conflicting signals are received, the operator must stop until the conflict is resolved. An Emergency Stop signal from either person takes immediate precedence over all other signals. Never continue operating with conflicting directions.',
            },
            {
              question: 'A compact track loader is operating in a building demolition site where heavy debris is falling from upper floors. What protective structure is specifically required in addition to ROPS?',
              options: [
                'An additional roll bar welded across the cab opening',
                'FOPS (Falling Object Protective Structure)',
                'A crane suspended overhead protection screen',
                'ROPS alone provides adequate protection from falling objects',
              ],
              correctIndex: 1,
              explanation: 'ROPS protects from rollover; FOPS (Falling Object Protective Structure) is designed to protect the operator from objects falling from above. Both are required by OSHA 29 CFR 1926.602 in appropriate conditions. Many compact loader cabs are designed to meet both standards simultaneously.',
            },
            {
              question: 'You are digging a 5-foot-deep utility trench and have placed the spoil pile 18 inches from the trench edge for convenience. Which OSHA standard are you violating?',
              options: [
                'OSHA 29 CFR 1926.602 — material handling equipment rules',
                'OSHA 29 CFR 1926 Subpart P — excavation spoil must be at least 2 feet from the trench edge',
                'OSHA 29 CFR 1926 Subpart Q — concrete and masonry requirements',
                'No violation — 18 inches is within acceptable tolerance',
              ],
              correctIndex: 1,
              explanation: 'OSHA 1926.651(j)(2) requires spoil, equipment, and materials to be kept at least 2 feet from the edge of the excavation. The 18-inch placement violates this standard. Spoil too close to the edge adds surcharge load on the trench wall and increases cave-in risk.',
            },
            {
              question: 'After completing a job with a mini-excavator equipped with a hydraulic thumb, the operator needs to load the machine onto a transport trailer. What is the correct sequence?',
              options: [
                'Drive onto the trailer at an angle to align with the tie-down rings, then fold the boom',
                'Engage the swing lock, fold boom and arm to minimum transport configuration, drive straight-on up the ramp, then secure all chains to manufacturer tie-down points',
                'Drive straight onto the trailer, then lower the boom to the deck and secure just the tracks',
                'Remove the thumb attachment before loading to reduce overall height, then drive on at any angle',
              ],
              correctIndex: 1,
              explanation: 'Proper transport sequence: (1) engage swing lock to prevent upperstructure rotation; (2) fold boom and arm to minimum transport configuration; (3) approach ramp straight-on to avoid asymmetric loading; (4) drive onto the trailer deck; (5) lower attachment; (6) secure machine with chains at all manufacturer-designated tie-down points.',
            },
            {
              question: 'Which of the following BEST summarizes the difference between the 10,000 lb and 8,000 lb GVW thresholds in 520 CMR 6.00?',
              options: [
                '10,000 lbs applies to machines used indoors; 8,000 lbs applies to outdoor construction',
                '10,000 lbs is the threshold for a full compact hoisting license; 8,000 lbs is the stricter limit for the non-renewable temporary (short-term rental) permit',
                '10,000 lbs applies to track machines; 8,000 lbs applies to wheeled machines',
                'Both thresholds are the same limit expressed at different points in the regulation — there is no practical difference',
              ],
              correctIndex: 1,
              explanation: 'The 10,000 lb GVW threshold defines compact hoisting machinery for purposes of the professional hoisting license. The stricter 8,000 lb threshold applies to the temporary (short-term rental) permit, which is designed for occasional, non-professional use and is issued by approved rental entities for up to 14 consecutive days.',
            },
          ],
        },
      ],
    },
  ],
};
